### ISSUE TITLE
Documentation describes invalid values for xFirewall

### ISSUE THREAD

**Issue by jgoldschrafe** [PowerShell/xNetworking#100]
The README.md specifies for xFirewall:

    Action: Permit or Block the supplied configuration.

However, `Permit` is not an allowed value for Action. The allowed values are `NotConfigured`, `Allow`, or `Block`.

**Comment by PlagueHO** [comment]
Good catch!

I have submitted PR #101 to correct the docs (as well as the Action description in the Schema).

Thanks :+1:
