### ISSUE TITLE
AmbiguousParameterSetError with xFirewall resource

### ISSUE THREAD

**Issue by megamorf** [PowerShell/xNetworking#102]
Hey guys,

Even though my dsc configuration seems to ba applied I receive some errors related to the xFirewall resource when I run Start-DscConfiguration.

My configuration contains this section...

```powershell
        foreach($Rule in $Node.CustomFWRules)
        {
            $tmpName = $Rule.Name -replace ' ','-'
            $Message = 'Configuring {0} with {1}' -f $tmpName,($Rule | Out-String)

            Write-Verbose $Message

            xFirewall $tmpName
            {
                Name         = $Rule.Name
                DisplayName  = $Rule.Name
                Group        = $Rule.Group
                Ensure       = 'Present'
                Enabled      = 'True'
                Profile      = ('Domain','Private')
                Direction    = 'Inbound'
                LocalPort    = $Rule.LocalPort
                Protocol     = $Rule.Protocol
                Description  = $Rule.Description
            }

        }
```

... that reads a few firewall rules from my data file. Here's an example

```
 @{
    NodeName      = '*'
    CustomFWRules = @(
        @{Group = 'Domino'; Name = 'Domino POP3'; Description = 'Ticket #53347'; Protocol = 'TCP'; LocalPort = @(110,995) }
    )
}
```

Output from  Start-DscConfiguration:
> VERBOSE: [SRVADM012]: LCM:  [ StartenRessource]  [[xFirewall]Domino-POP3]
VERBOSE: [SRVADM012]: LCM:  [ StartenTesten   ]  [[xFirewall]Domino-POP3]
VERBOSE: [SRVADM012]:                            [[xFirewall]Domino-POP3] Test-TargetResource: Checking settings for firewall rule with Name 'Domino POP3'.
VERBOSE: [SRVADM012]:                            [[xFirewall]Domino-POP3] Test-TargetResource: Find firewall rule with Name 'Domino POP3'.
VERBOSE: [SRVADM012]:                            [[xFirewall]Domino-POP3] Test-TargetResource: Check each defined parameter against the existing firewall rule with Name 'Domino POP3'.
VERBOSE: [SRVADM012]:                            [[xFirewall]Domino-POP3] Get-FirewallRuleProperty: Get all the properties and add filter info to rule map.
VERBOSE: [SRVADM012]:                            [[xFirewall]Domino-POP3] Test-RuleProperties: Profile property value 'Domain, Private' does not match desired state 'Domain,Private'.
VERBOSE: [SRVADM012]:                            [[xFirewall]Domino-POP3] Test-RuleProperties: Test Firewall rule with Name 'Domino POP3' returning False.
VERBOSE: [SRVADM012]:                            [[xFirewall]Domino-POP3] Test-TargetResource: Check Firewall rule with Name 'Domino POP3' returning False.
VERBOSE: [SRVADM012]: LCM:  [ BeendenTesten   ]  [[xFirewall]Domino-POP3]  in 0.5620 Sekunden.
VERBOSE: [SRVADM012]: LCM:  [ StartenFestlegen]  [[xFirewall]Domino-POP3]
VERBOSE: [SRVADM012]:                            [[xFirewall]Domino-POP3] Set-TargetResource: Applying settings for firewall rule with Name 'Domino POP3'.
VERBOSE: [SRVADM012]:                            [[xFirewall]Domino-POP3] Set-TargetResource: Find firewall rule with Name 'Domino POP3'.
VERBOSE: [SRVADM012]:                            [[xFirewall]Domino-POP3] Set-TargetResource: We want the firewall rule with Name 'Domino POP3' to exist since Ensure is set to Present.
VERBOSE: [SRVADM012]:                            [[xFirewall]Domino-POP3] Set-TargetResource: We want the firewall rule with Name 'Domino POP3' to exist and it does. Check for valid properties.
VERBOSE: [SRVADM012]:                            [[xFirewall]Domino-POP3] Set-TargetResource: Check each defined parameter against the existing firewall rule with Name 'Domino POP3'.
VERBOSE: [SRVADM012]:                            [[xFirewall]Domino-POP3] Get-FirewallRuleProperty: Get all the properties and add filter info to rule map.
VERBOSE: [SRVADM012]:                            [[xFirewall]Domino-POP3] Test-RuleProperties: Profile property value 'Domain, Private' does not match desired state 'Domain,Private'.
VERBOSE: [SRVADM012]:                            [[xFirewall]Domino-POP3] Test-RuleProperties: Test Firewall rule with Name 'Domino POP3' returning False.
VERBOSE: [SRVADM012]:                            [[xFirewall]Domino-POP3] Set-TargetResource: Updating existing firewall rule with Name 'Domino POP3'.
Der Parametersatz kann mit den angegebenen benannten Parametern nicht aufgelöst werden.
    + CategoryInfo          : InvalidArgument: (:) [], CimException
    + FullyQualifiedErrorId : AmbiguousParameterSet,Set-NetFirewallRule
    + PSComputerName        : srvadm012
 
>VERBOSE: [SRVADM012]: LCM:  [ BeendenFestlegen]  [[xFirewall]Domino-POP3]  in 0.5000 Sekunden.
Die PowerShell DSC-Ressource "[xFirewall]Domino-POP3" mit SourceInfo "\\homedrive\home$\megamorf\gitlab\DSC-BLNMAIL\MailServerConfig.ps1::64::13::xFirewall" hat beim Ausführen der Funktion "Set-TargetResource" mindestens 
einen Fehler ohne Abbruch ausgegeben. Diese Fehler werden im ETW-Kanal namens "Microsoft-Windows-DSC/Operational" protokolliert. Weitere Informationen finden Sie in diesem Kanal.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : srvadm012

My setup is:
* Windows Server 2012 R2 Datacenter (German)
* WMF5 RTM (the one from February '16)
* xNetworking Resource from Dev branch downloaded yesterday

Unfortunately I don't have the time to troubleshoot this myself at the moment :( Have you encountered this error before?

**Comment by megamorf** [comment]
What struck me as odd was this line:

> VERBOSE: [SRVADM012]: [[xFirewall]Domino-POP3] Test-RuleProperties: Profile property value 'Domain, Private' does not match desired state 'Domain,Private'.

**Comment by PlagueHO** [comment]
@megamorf - I see what you mean. I'll take a look and see if I can figure out why the comparison is failing.

**Comment by PlagueHO** [comment]
@megamorf - good catch on this one. I think I've fixed the issue and submitted a PR to dev. If you want to, you can try out the fix in my xNetworking fork here:
https://github.com/PlagueHO/xNetworking/tree/Issue-102-Firewall-Profile-Comparison-Issue

**Comment by megamorf** [comment]
Thanks for the quick fix Daniel. I'm going to give your fork a shot tomorrow when I'm back at the office.

PS: Thanks for liking some of my blog posts, hehe

**Comment by PlagueHO** [comment]
No problemo @megamorf - and I enjoy your blog!

Thanks for the merge @tysonjhayes :+1:

**Comment by megamorf** [comment]
I can confirm this has solved my issue. Thanks again!
