### ISSUE TITLE
MSFT_xIPAddress: IP Address Test wrong result

### ISSUE THREAD

**Issue by josch710** [PowerShell/xNetworking#104]
Hi,

It seems the Test-Resource of MSFT_xIPAddress delivers a wrong result, if the desired IP address (as string) is a part of the current one.

Example: 
Current IP: 192.168.178.15
Desired IP: 192.168.178.1

The if-clause "if (-not $currentIPs.IPAddress.Contains($IPAddress))" delivers false - so DSC thinks the current IP address is equal to the desired one...

**Comment by PlagueHO** [comment]
Hi @josch710,

That's a good catch! I'll get a PR through for this ASAP (and update the unit tests so it doesn't come back :smile: ). :+1:

**Comment by PlagueHO** [comment]
I have submitted a fix for this in PR #105.

**Comment by josch710** [comment]
Hi @PlagueHO 

Thank you very much for the fast reply...

Is it also possible for me to contribute here with the scripts? Because I would say I am quiet familiar with DSC now and would be great to contribute to the scripts here in the git hub "community"...

**Comment by PlagueHO** [comment]
@josch710 

Glad to help :smile: Hopefully @tysonjhayes will merge this to dev over the next few days (thanks @tysonjhayes).

And you most definitely can help out. Any help with new or existing DSC resources are most welcome :+1: There is a lot of opportunities for enhancing or creating new resources or just bug fixes on existing ones.

The best place to start is [here](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md).

Once you're familiar with the contribution guidelines and other technicalities, you can find something that needs doing, e.g. an issue someone has raised or an enhancement someone has requested and go from there.

Also, a good place to discover stuff and chat with other DSC resource creators etc is on Gitter:
[![Join the chat at https://gitter.im/PowerShell/DscResources](https://badges.gitter.im/Join%20Chat.svg)](https://gitter.im/PowerShell/DscResources?utm_source=badge&utm_medium=badge&utm_campaign=pr-badge&utm_content=badge)

I also wrote a blog series on contributing to the DSC Resource community [here](https://dscottraynsford.wordpress.com/2015/12/14/creating-professional-dsc-resources-part-1/) (appologies for the shameless plug :smile:).

Anyway, welcome to the "community" :+1:

**Comment by tysonjhayes** [comment]
@josch710 the DSC group is very open to contributions so please feel free to join in! As @PlagueHO already pointed out his blog posts and the contributions are a good place to start. I started by adding tests to existing projects and worked my way into features, now I run a few of them. We all have to start some where!

**Comment by PlagueHO** [comment]
Thanks @tysonjhayes :+1:

**Comment by josch710** [comment]
Thanks @tysonjhayes @PlagueHO
