### ISSUE TITLE
[New Resource] DNSGlobalSuffixSearchList

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xNetworking#111]
This would mainly be used to set the "Primary DNS Suffix of this computer":
![2016-04-27_10-00-09](https://cloud.githubusercontent.com/assets/7589164/14835633/e1a62488-0c5e-11e6-88fb-73474fc20395.png)

The cmdlets ```get-dnsclientglobalsetting``` and ```set-dnsclientglobalsetting``` could be used to set this value.

The resource would be quite similar to the xNetBIOS resource I would think.

**Comment by adamcousins** [comment]
Also looking for such a feature
currently using Set-DnsClientGlobalSetting as a work around but would like a dsc block for this.
My use case is AWS Ec2 instance removing default suffix lists and applying my domain and forest lists.
Unfortunetly im not familiar enough with PS to assist building, but with the user base of AWS im sure someone is.

**Comment by PlagueHO** [comment]
@adamcousins - I'll try and get onto this over the next week for you. I'm working on another resource for xNetworking, so I'll try and throw this one at the same time. Will keep you up to date :smile:
