### ISSUE TITLE
xHostFile doesn't update existing entries correctly

### ISSUE THREAD

**Issue by BrianFarnhill** [PowerShell/xNetworking#119]
**Observed behavior**
Create a xHostFile resource that sets a specific value and it applies correctly, but then if I update the resource to change the IP address I see it create a new entry for the same domain name, meaning it is in the host file twice with both the old and new IP addresses, and as the old one is most likely to appear first the change does not apply.

**Expected behavior**
The previous entry should be removed so that a host name only appears once in the host file

**Software versions**
Windows Server 2012 R2, WMF5, xNetworking 2.8.0.0

**Notes on a fix**
A little while back I wrote a host file entry resource (I wasn't aware there was one in this repo) that worked correctly and was dramatically less code as it didn't try to compress all the host entries on to a single line for each IP address like this resource does, the code for this is in [my xComputerManagement repo](https://github.com/BrianFarnhill/xComputerManagement/tree/feature-xhostfileentry). If you guys want I can open a PR to bring that logic in to this resource - or you can look at fixing the issue in the existing logic if thats the preferred approach. Just let me know if you want my code and I'll get that moving.

**Comment by PlagueHO** [comment]
Hi @BrianFarnhill - I guess it comes down to how easy it would be to fix the existing xHosts and what @rchaganti thinks. Your code is nice and trim but would need some localization etc. added to it.

If the fix to the existing code is small and easy then I'd say use the existing code, but if requires more effort then perhaps it would be simpler to merge with your new code.

Of course though we'd want to make sure that it wasn't a breaking change if we could avoid it, so not changing the MOFs and resource names would be ideal

This is just my 2c of course - @tysonjhayes ?

**Comment by rchaganti** [comment]
Thanks for reporting the issue @BrianFarnhill. Agree with @PlagueHO thoughts on this. Since the existing module has localization support and adheres to all style guidelines and so on, I too prefer that we fix the code here. I have not looked at your code and will do so over the weekend. That said, if you want to clone this repo and implement the fix yourself, that is more than welcome! :)

**Comment by BrianFarnhill** [comment]
@PlagueHO @rchaganti I thought I had all the style guidelines in that one covered - I'll check. I don't have the localisation support but that would only take me a few minutes to bake in really. I'll have a look at it and get a PR open if you guys are happy with that then?

**Comment by PlagueHO** [comment]
@BrianFarnhill basically I'm happy as long we end up with a resource that fixes the issue and meets the guidelines and doesn't require a breaking change to get there. I'd like to think that the Unit/Integration tests in place will identify and potential problems changing to the new module, so can we possibly keep the integration and unit tests as is if they have 100% coverage?

@rchaganti  - your call here sir. If @BrianFarnhill is able to bring his version of the resource up to code and fix it fixes the issue with yours, are you happy if it gets slotted in place.

**Comment by PlagueHO** [comment]
@BrianFarnhill  - in the absence of any objections from @rchaganti, we should put your one in place. @tysonjhayes - are you OK with this? I'm happy to review the code if you like?

**Comment by rchaganti** [comment]
Hey guys,
Sorry. Been a little busy and did not notice these emails. Brian, please go ahead and push a PR.

Get Outlook for Android<https://aka.ms/ghei36>



On Sat, Jun 4, 2016 at 5:49 PM -0700, "Daniel Scott-Raynsford" <notifications@github.com<mailto:notifications@github.com>> wrote:


@BrianFarnhill<https://github.com/BrianFarnhill> - in the absence of any objections from @rchaganti<https://github.com/rchaganti>, we should put your one in place. @tysonjhayes<https://github.com/tysonjhayes> - are you OK with this? I'm happy to review the code if you like?

-

**Comment by BrianFarnhill** [comment]
I haven't had a chance to port mine across to this repo and add the localisation yet (Q4 is in full swing for me, so free time is a hard thing to find in between customer engagements!). I'll push it in as soon as I can though, but that might be a couple of weeks from now at this point.

**Comment by BrianFarnhill** [comment]
Just opened the PR on this one guys (as #125) - please go ahead and review when ready
