### ISSUE TITLE
xFirewall: Get-DscConfiguration fails

### ISSUE THREAD

**Issue by janegilring** [PowerShell/xNetworking#12]
When xFirewall is used in a DSC configuration, Get-DscConfiguration fails with the error:
"Unable to cast object of type 'System.Management.Automation.PSObject' to type 'System.Collections.IList'."

**Comment by tysonjhayes** [comment]
If you could walk me through a bit more of this.

Basically are you, applying a Firewall configuraiton and then call Get-DscConfiguration? Are you applying any other configuration besides the firewall change? Could you share the configuration your using?

**Comment by janegilring** [comment]
Here is an example:
Configuration Firewall {

Import-DscResource -ModuleName xNetworking

Firewall RDP {   

Name = 'Remote Desktop - User Mode (TCP-In)'
DisplayGroup = 'Remote Desktop'
Ensure = 'Present'
State = 'Enabled'
Access = 'Allow'
Profile = 'Domain'
Description = 'Inbound rule for the Remote Desktop service to allow RDP traffic. (Created by DSC)'
LocalPort = '3389'
Protocol = 'TCP'
Direction = 'Inbound'
ApplicationPath = '%SystemRoot%\system32\svchost.exe'

}

}

Apply this to a system and then try to call Get-DscConfiguration. There are other elements in the configuration, but I believe the above should be a sufficient repro.

**Comment by tysonjhayes** [comment]
I can confirm a repro on WMF 4.0 Server 2012 R2.  Though I'm unclear as to the cause. @TravisEz13  do you have any ideas?

**Comment by janegilring** [comment]
Thanks for confirming. I forgot to mention it, but Get-TargetResource works fine here as well.

**Comment by tysonjhayes** [comment]
My vague understanding of this stuff is that Get-DSCConfiguration calls Get-TargetResource for all of the applied resources. So my guess is something about Get-TargetResource needs to be adjusted.  Though I'm just unclear what.

**Comment by janegilring** [comment]
That is correct, Get-DSCConfiguration calls Get-TargetResource.
I also think it`s strange that it works when it`s invoked manually, The only difference I can see is that DSC runs under the SYSTEM account, we might try to run Get-TargetResource in that security context by using for example psexec.

**Comment by tysonjhayes** [comment]
I've never tried doing that, how does one go about leveraging psexec to do that?

**Comment by janegilring** [comment]
Download psexec.exe and launch powershell.exe using this syntax:
C:\SysinternalsSuite\psexec.exe /i /s powershell.exe

Type whoami to verify you`re running as SYSTEM.
You`re now ready to check if Get-TargetResource runs correctly when launched manually.

**Comment by tysonjhayes** [comment]
OK I ran the get-targetresource under the system context and did not observe any difference in behavior.  Get-TargetResource ran without a problem and Get-DSCConfiguration also failed.

**Comment by janegilring** [comment]
Good, then it`s not related to the security context.
Since it works when run manually it may seem like it`s something related to the way DSC invokes it.
It would be useful if we could get some pointers from someone on the PowerShell team.

**Comment by dcrreynolds** [comment]
The RemotePort and LocalPort properties are returning a string instead of a list when there is only one or no local/remote port being configured. This doesn't match the object that DSC is expecting to get returned.

**Comment by tysonjhayes** [comment]
@dcrreynolds that theory makes sense. how do you know it's those two properties in particular?  I'll test this on Monday when I'm back in the office.

**Comment by dcrreynolds** [comment]
Tested them individually in my lab. Wrapped both in @(...) and tested for multiple ports, single port, and no ports with no issue. Was going to send a pull request, but GitHub seems to be having an issue with it atm.

**Comment by tysonjhayes** [comment]
@dcrreynolds are you able to send a pull request now? Would love to have you contribute.

**Comment by dcrreynolds** [comment]
Not yet. I have an open email with GitHub support.

**Comment by tysonjhayes** [comment]
Well drat, to be clear you basically did this:

````
    $getTargetResourceResult.RemotePort = @($properties.PortFilters.RemotePort)
    $getTargetResourceResult.LocalPort = @($properties.PortFilters.LocalPort)
````

If so I'll get some basic tests done on the get-targetresource function and get a pull request open.

**Comment by dcrreynolds** [comment]
That was it.

**Comment by tysonjhayes** [comment]
Ok ran it in my lab and I can confirm that that change does fix the problem. I'll get some tests cobbled together and get a pull request going.

**Comment by janegilring** [comment]
It seems to work fine in my lab as well, excellent!
