### ISSUE TITLE
MSFT_xIPAddress - expected behaviour?

### ISSUE THREAD

**Issue by janegilring** [PowerShell/xNetworking#123]
Scenario: A DSC configuration is defined to configure the same IP address as the target node already have configured via DHCP.
Expected output: The network configuration should be changed from DHCP enabled to DHCP disabled.
Actual output: No changes, DHCP still enabled.

Is this by design or a bug?

**Comment by PlagueHO** [comment]
Actually, this is a bug I think.

xIPAddress only checks to see if the IP Address matches - if it does it doesn't bother to perform a test of the DHCP status. It probably should - nice edge case catch!

I'll add it to my Todo list for this week :+1:

**Comment by janegilring** [comment]
Awesome, thanks for the quick response!

**Comment by PlagueHO** [comment]
This is in progress now.

**Comment by PlagueHO** [comment]
@janegilring - I've been reviewing this and some of the history on this particular resource. I now believe this is actually an intended behavior.

What should actually be done here is that the xDHCPClient resource should be first used to set the DHCP status to disabled and the xIPAddress should be set.

This is really a fault in the examples and documentation (as I had to review the actual resources myself to determine this).

The reason for doing it this way was to try and prevent the possibility of a conflicting configuration: E.g. if the xDHCPClient was enabled and then an address was set by xIPAddress.

Are you able to try adding the xDHCPClient resource to your config and see if that actually resolves the problem? I'll submit a PR to add an example on how to set a static IP Address correctly.

**Comment by janegilring** [comment]
Thanks, that did the trick. I didn`t know about the xDHCPClient resource, but it does makes sense that it exists and must be used in conjunction with xIPAddress after reading your explanation.

**Comment by PlagueHO** [comment]
No worries! It was a relatively new addition to the suite. I do think the documentation actually isn't that clear on the usage pattern, so I've submitted a PR that will update the documentation with better examples for this :smile: Thanks for letting us know the fix worked too!
