### ISSUE TITLE
Unit tests should not wrap entire tests within InModuleScope

### ISSUE THREAD

**Issue by narrieta** [PowerShell/xNetworking#132]
Only sections that need to access to the module's private data/functions should use InModuleScope

**Comment by KarolKaczmarek** [comment]
Ups, just created duplicate. It doesn't only refer to MSFT_xFirewall.Tests.ps1 but other unit tests as well, updating the title.

xNetworking unit tests use old test template (which contained InModuleScope section). It has been removed from new templates so we should update the tests here as well.
 See: PowerShell/DscResources#166

**Comment by kwirkykat** [comment]
@PlagueHO

**Comment by PlagueHO** [comment]
Thank you @narrieta - I'll get a PR through for this over the next few days (by the end of weekend at the latest).

**Comment by PlagueHO** [comment]
I'd like some guidance on this if you all don't mind? Please see this issue I've raised:
https://github.com/PowerShell/DscResources/issues/175

I'm feeling uneasy that this is actually the best way to go.

**Comment by PlagueHO** [comment]
I think we should put this one on hold for now until the changes to Pester are made - as per the community call today.

I've spent a bit of time trying out the suggested alterations (made in https://github.com/PowerShell/DscResources/issues/175) to the test methods to allow ```InModuleScope``` to be removed. But they have either resulted in some really ugly code (which is very hard to understand) or cause a lot more problems.

**Comment by kwirkykat** [comment]
This issue is on hold per discussion in PowerShell/DscResources#175

**Comment by tysonjhayes** [comment]
Call was to leave this in all our templates and not remove this at this time. As such I'm closing this issue.
