### ISSUE TITLE
application bug in powershell DSCResource XNetworking - XRoute

### ISSUE THREAD

**Issue by fanlongmeng** [PowerShell/xNetworking#134]
When I am using the module to remove a specific route, The script delete all routes from the list what ever route assigned.               

It all works fine when delete below scripts from the function Test-TargetResource in  MSFT_xRoute.psm1

            # The Route exists - remove it
            $null = $PSBoundParameters.Remove('InterfaceAlias')
            $null = $PSBoundParameters.Remove('AddressFamily')
            $null = $PSBoundParameters.Remove('DestinationPrefix')
            $null = $PSBoundParameters.Remove('NextHop')

**Comment by PlagueHO** [comment]
Hi @fanlongmeng - you are quite right! Good catch - that looks like a definite bug. I'll get a PR submitted for this ASAP so that it can hopefully go out with the next release.
