### ISSUE TITLE
Get-DscConfiguration failing when multiple IPs are present on interface

### ISSUE THREAD

**Issue by paveldokov** [PowerShell/xNetworking#138]
Hello guys,

I am really happy with the module, but I found a little issue with it - on NLB interface I have 2 IPs - nlb_IP and vip_IP. When it comes to checking the nlb_IP, it fails.

Hope this helps!

Regards,

[get_dscConfig_error.txt](https://github.com/PowerShell/xNetworking/files/410650/get_dscConfig_error.txt)

**Comment by PlagueHO** [comment]
Hi @paveldokov  - thanks for the feedback! :smile:

Are you able to post the output from ```Start-DSCConfiguration``` with the -Verbose parameter added? It should give us more feedback on what is going wrong.

**Comment by paveldokov** [comment]
Hello, 
Actually, the configuration applies and test correctly. Issue occurs only when I run 'Get-DscConfiguration'
Please, find the log from 'Start-DSCConfiguration -Verbose' attached.

Regards,
Pavel

[{E4489580-5FF9-11E6-80CF-02BF0A0F015E}-0.details.json.txt](https://github.com/PowerShell/xNetworking/files/414071/E4489580-5FF9-11E6-80CF-02BF0A0F015E.-0.details.json.txt)

**Comment by PlagueHO** [comment]
Hi @paveldokov - I'm haven't been able to solve this one yet. I've assigned two IP Addresses to the same adapter and Get-TargetResource still returns the exepected values.

So I have a few more questions to help me solve this if you don't mind:
- Which version of xNetworking are you using?
- Could you post the Config you're applying (feel free to remove any sensitive info)?
- Could you post the output of this command run on the box applying the DSC config:
```powershell
Get-NetIpAddress -InterfaceAlias '<Put the alias of your Network adapter with the VIP/NLB IP>' -AddressFamily IPv4
```

Thank you very much for helping me look into this one.

**Comment by paveldokov** [comment]
Hello,

Sorry for the delayed response. Here is my NIC extract from config file:

         foreach ($NIC in $Node.NICs) # Configure NICs
         {
            foreach ($IP in $NIC.IPs) # Configure IP Address (multiple address option available)
            {
                xIPAddress $IP.Name
                {
                    InterfaceAlias = $NIC.Alias
                    IPAddress = $IP.IP
                    AddressFamily = $NIC.IPFamily
                    SubnetMask = $NIC.SM
                    DependsOn = $IP.DependsOn
                }
            }
            if ($NIC.GW -ne $null) # Configure GateWay
            {
                xDefaultGatewayAddress $NIC.Alias
                {
                    Address = $NIC.GW
                    AddressFamily = $NIC.IPFamily
                    InterfaceAlias = $NIC.Alias
                }
            }
            if ($NIC.DNS -ne $null) # Configure DNS Servers
            {
                xDNSServerAddress $NIC.Alias
                {
                    AddressFamily = $NIC.IPFamily
                    InterfaceAlias = $NIC.Alias
                    Address = $NIC.DNS
                }
            }
            if ($NIC.NICBinding -ne $null) # Configure bindings if any
            {
                foreach ($binding in $NIC.NICBinding)
                {    
                    xNetAdapterBinding $binding
                    {
                        InterfaceAlias = $NIC.Alias
                        ComponentId = $binding
                    }
                }
            }
            if ($NIC.Routes -ne $null) # Configure static routes on NICs if any
            {
                foreach ($Route in $NIC.Routes)
                {
                    xRoute $Route.Name
                    {
                        AddressFamily = $NIC.IPFamily
                        DestinationPrefix = $Route.Prefix
                        InterfaceAlias = $NIC.alias
                        NextHop = $Route.GW
                        Ensure = "Present"
                        RouteMetric = 2
                    }
                }
            }
         }
		 
Here is Data part:

			NICs = @(
                        @{
                            Alias = "NLB"
                            IPs = @(
                                @{
                                    Name="NLB_IP"
                                    IP = "IP_NLB_NIC"
                                 }
                                @{
                                    Name="VIP_IP"
                                    IP = "IP_VIP_NLB_NIC"
                                    DependsOn = "[xIPAddress]NLB_IP"
                                 }
                                   )
                            SM = mask
                            GW = "GW_IP"
                            DNS = @("DNS1", "DNS2")
                            IPFamily = "IPv4"
                            NICBinding = @("ms_wlbs")
                          }
                        @{
                            Alias = "Management"
                            IPs = @(
                                @{
                                    Name="Mgmt_IP"
                                    IP = "IP_Mgmt_NIC"
                                 }
                                    )
                            SM = mask
                            DNS = @("DNS1", "DNS2")
                            IPFamily = "IPv4"
                            Routes = @(
                                        @{
                                            Name= "Route1"
                                            Prefix = "network/mask"
                                            GW = "GW_Address_R1"
                                         }
                                        @{
                                            Name= "Route2"
                                            Prefix = "network/mask"
                                            GW = "GW_Address_R2"
                                         }
                                      )
                        }
                    )


Here is output of the command:

PS C:\Windows\system32> Get-NetIpAddress -InterfaceAlias 'NLB' -AddressFamily IPv4


IPAddress         : IP_NLB_NIC
InterfaceIndex    : 14
InterfaceAlias    : NLB
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : mask
PrefixOrigin      : Manual
SuffixOrigin      : Manual
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : IP_VIP_NLB_NIC
InterfaceIndex    : 14
InterfaceAlias    : NLB
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : mask
PrefixOrigin      : Manual
SuffixOrigin      : Manual
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : True
PolicyStore       : ActiveStore

Hope this helps. Thanks a lot for the effort!

Regards

**Comment by paveldokov** [comment]
Hello,

Sorry for the delayed response. Here is my NIC extract from config file:

         foreach ($NIC in $Node.NICs) # Configure NICs
         {
            foreach ($IP in $NIC.IPs) # Configure IP Address (multiple address option available)
            {
                xIPAddress $IP.Name
                {
                    InterfaceAlias = $NIC.Alias
                    IPAddress = $IP.IP
                    AddressFamily = $NIC.IPFamily
                    SubnetMask = $NIC.SM
                    DependsOn = $IP.DependsOn
                }
            }
            if ($NIC.GW -ne $null) # Configure GateWay
            {
                xDefaultGatewayAddress $NIC.Alias
                {
                    Address = $NIC.GW
                    AddressFamily = $NIC.IPFamily
                    InterfaceAlias = $NIC.Alias
                }
            }
            if ($NIC.DNS -ne $null) # Configure DNS Servers
            {
                xDNSServerAddress $NIC.Alias
                {
                    AddressFamily = $NIC.IPFamily
                    InterfaceAlias = $NIC.Alias
                    Address = $NIC.DNS
                }
            }
            if ($NIC.NICBinding -ne $null) # Configure bindings if any
            {
                foreach ($binding in $NIC.NICBinding)
                {    
                    xNetAdapterBinding $binding
                    {
                        InterfaceAlias = $NIC.Alias
                        ComponentId = $binding
                    }
                }
            }
            if ($NIC.Routes -ne $null) # Configure static routes on NICs if any
            {
                foreach ($Route in $NIC.Routes)
                {
                    xRoute $Route.Name
                    {
                        AddressFamily = $NIC.IPFamily
                        DestinationPrefix = $Route.Prefix
                        InterfaceAlias = $NIC.alias
                        NextHop = $Route.GW
                        Ensure = "Present"
                        RouteMetric = 2
                    }
                }
            }
         }
		 
Here is Data part:

			NICs = @(
                        @{
                            Alias = "NLB"
                            IPs = @(
                                @{
                                    Name="NLB_IP"
                                    IP = "IP_NLB_NIC"
                                 }
                                @{
                                    Name="VIP_IP"
                                    IP = "IP_VIP_NLB_NIC"
                                    DependsOn = "[xIPAddress]NLB_IP"
                                 }
                                   )
                            SM = mask
                            GW = "GW_IP"
                            DNS = @("DNS1", "DNS2")
                            IPFamily = "IPv4"
                            NICBinding = @("ms_wlbs")
                          }
                        @{
                            Alias = "Management"
                            IPs = @(
                                @{
                                    Name="Mgmt_IP"
                                    IP = "IP_Mgmt_NIC"
                                 }
                                    )
                            SM = mask
                            DNS = @("DNS1", "DNS2")
                            IPFamily = "IPv4"
                            Routes = @(
                                        @{
                                            Name= "Route1"
                                            Prefix = "network/mask"
                                            GW = "GW_Address_R1"
                                         }
                                        @{
                                            Name= "Route2"
                                            Prefix = "network/mask"
                                            GW = "GW_Address_R2"
                                         }
                                      )
                        }
                    )


Here is output of the command:

PS C:\Windows\system32> Get-NetIpAddress -InterfaceAlias 'NLB' -AddressFamily IPv4


IPAddress         : IP_NLB_NIC
InterfaceIndex    : 14
InterfaceAlias    : NLB
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : mask
PrefixOrigin      : Manual
SuffixOrigin      : Manual
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : IP_VIP_NLB_NIC
InterfaceIndex    : 14
InterfaceAlias    : NLB
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : mask
PrefixOrigin      : Manual
SuffixOrigin      : Manual
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : True
PolicyStore       : ActiveStore

Hope this helps. Thanks a lot for the effort!

Regards

**Comment by paveldokov** [comment]
Hello,

Sorry for the delayed response. Here is my NIC extract from config file:

         foreach ($NIC in $Node.NICs) # Configure NICs
         {
            foreach ($IP in $NIC.IPs) # Configure IP Address (multiple address option available)
            {
                xIPAddress $IP.Name
                {
                    InterfaceAlias = $NIC.Alias
                    IPAddress = $IP.IP
                    AddressFamily = $NIC.IPFamily
                    SubnetMask = $NIC.SM
                    DependsOn = $IP.DependsOn
                }
            }
            if ($NIC.GW -ne $null) # Configure GateWay
            {
                xDefaultGatewayAddress $NIC.Alias
                {
                    Address = $NIC.GW
                    AddressFamily = $NIC.IPFamily
                    InterfaceAlias = $NIC.Alias
                }
            }
            if ($NIC.DNS -ne $null) # Configure DNS Servers
            {
                xDNSServerAddress $NIC.Alias
                {
                    AddressFamily = $NIC.IPFamily
                    InterfaceAlias = $NIC.Alias
                    Address = $NIC.DNS
                }
            }
            if ($NIC.NICBinding -ne $null) # Configure bindings if any
            {
                foreach ($binding in $NIC.NICBinding)
                {    
                    xNetAdapterBinding $binding
                    {
                        InterfaceAlias = $NIC.Alias
                        ComponentId = $binding
                    }
                }
            }
            if ($NIC.Routes -ne $null) # Configure static routes on NICs if any
            {
                foreach ($Route in $NIC.Routes)
                {
                    xRoute $Route.Name
                    {
                        AddressFamily = $NIC.IPFamily
                        DestinationPrefix = $Route.Prefix
                        InterfaceAlias = $NIC.alias
                        NextHop = $Route.GW
                        Ensure = "Present"
                        RouteMetric = 2
                    }
                }
            }
         }
		 
Here is Data part:

			NICs = @(
                        @{
                            Alias = "NLB"
                            IPs = @(
                                @{
                                    Name="NLB_IP"
                                    IP = "IP_NLB_NIC"
                                 }
                                @{
                                    Name="VIP_IP"
                                    IP = "IP_VIP_NLB_NIC"
                                    DependsOn = "[xIPAddress]NLB_IP"
                                 }
                                   )
                            SM = mask
                            GW = "GW_IP"
                            DNS = @("DNS1", "DNS2")
                            IPFamily = "IPv4"
                            NICBinding = @("ms_wlbs")
                          }
                        @{
                            Alias = "Management"
                            IPs = @(
                                @{
                                    Name="Mgmt_IP"
                                    IP = "IP_Mgmt_NIC"
                                 }
                                    )
                            SM = mask
                            DNS = @("DNS1", "DNS2")
                            IPFamily = "IPv4"
                            Routes = @(
                                        @{
                                            Name= "Route1"
                                            Prefix = "network/mask"
                                            GW = "GW_Address_R1"
                                         }
                                        @{
                                            Name= "Route2"
                                            Prefix = "network/mask"
                                            GW = "GW_Address_R2"
                                         }
                                      )
                        }
                    )


Here is output of the command:

PS C:\Windows\system32> Get-NetIpAddress -InterfaceAlias 'NLB' -AddressFamily IPv4


IPAddress         : IP_NLB_NIC
InterfaceIndex    : 14
InterfaceAlias    : NLB
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : mask
PrefixOrigin      : Manual
SuffixOrigin      : Manual
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : IP_VIP_NLB_NIC
InterfaceIndex    : 14
InterfaceAlias    : NLB
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : mask
PrefixOrigin      : Manual
SuffixOrigin      : Manual
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : True
PolicyStore       : ActiveStore

Hope this helps. Thanks a lot for the effort!

Regards

**Comment by paveldokov** [comment]
Hello,

Sorry for the delayed response. Here is my NIC extract from config file:

         foreach ($NIC in $Node.NICs) # Configure NICs
         {
            foreach ($IP in $NIC.IPs) # Configure IP Address (multiple address option available)
            {
                xIPAddress $IP.Name
                {
                    InterfaceAlias = $NIC.Alias
                    IPAddress = $IP.IP
                    AddressFamily = $NIC.IPFamily
                    SubnetMask = $NIC.SM
                    DependsOn = $IP.DependsOn
                }
            }
            if ($NIC.GW -ne $null) # Configure GateWay
            {
                xDefaultGatewayAddress $NIC.Alias
                {
                    Address = $NIC.GW
                    AddressFamily = $NIC.IPFamily
                    InterfaceAlias = $NIC.Alias
                }
            }
            if ($NIC.DNS -ne $null) # Configure DNS Servers
            {
                xDNSServerAddress $NIC.Alias
                {
                    AddressFamily = $NIC.IPFamily
                    InterfaceAlias = $NIC.Alias
                    Address = $NIC.DNS
                }
            }
            if ($NIC.NICBinding -ne $null) # Configure bindings if any
            {
                foreach ($binding in $NIC.NICBinding)
                {    
                    xNetAdapterBinding $binding
                    {
                        InterfaceAlias = $NIC.Alias
                        ComponentId = $binding
                    }
                }
            }
            if ($NIC.Routes -ne $null) # Configure static routes on NICs if any
            {
                foreach ($Route in $NIC.Routes)
                {
                    xRoute $Route.Name
                    {
                        AddressFamily = $NIC.IPFamily
                        DestinationPrefix = $Route.Prefix
                        InterfaceAlias = $NIC.alias
                        NextHop = $Route.GW
                        Ensure = "Present"
                        RouteMetric = 2
                    }
                }
            }
         }
		 
Here is Data part:

			NICs = @(
                        @{
                            Alias = "NLB"
                            IPs = @(
                                @{
                                    Name="NLB_IP"
                                    IP = "IP_NLB_NIC"
                                 }
                                @{
                                    Name="VIP_IP"
                                    IP = "IP_VIP_NLB_NIC"
                                    DependsOn = "[xIPAddress]NLB_IP"
                                 }
                                   )
                            SM = mask
                            GW = "GW_IP"
                            DNS = @("DNS1", "DNS2")
                            IPFamily = "IPv4"
                            NICBinding = @("ms_wlbs")
                          }
                        @{
                            Alias = "Management"
                            IPs = @(
                                @{
                                    Name="Mgmt_IP"
                                    IP = "IP_Mgmt_NIC"
                                 }
                                    )
                            SM = mask
                            DNS = @("DNS1", "DNS2")
                            IPFamily = "IPv4"
                            Routes = @(
                                        @{
                                            Name= "Route1"
                                            Prefix = "network/mask"
                                            GW = "GW_Address_R1"
                                         }
                                        @{
                                            Name= "Route2"
                                            Prefix = "network/mask"
                                            GW = "GW_Address_R2"
                                         }
                                      )
                        }
                    )


Here is output of the command:

PS C:\Windows\system32> Get-NetIpAddress -InterfaceAlias 'NLB' -AddressFamily IPv4


IPAddress         : IP_NLB_NIC
InterfaceIndex    : 14
InterfaceAlias    : NLB
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : mask
PrefixOrigin      : Manual
SuffixOrigin      : Manual
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : False
PolicyStore       : ActiveStore

IPAddress         : IP_VIP_NLB_NIC
InterfaceIndex    : 14
InterfaceAlias    : NLB
AddressFamily     : IPv4
Type              : Unicast
PrefixLength      : mask
PrefixOrigin      : Manual
SuffixOrigin      : Manual
AddressState      : Preferred
ValidLifetime     : Infinite ([TimeSpan]::MaxValue)
PreferredLifetime : Infinite ([TimeSpan]::MaxValue)
SkipAsSource      : True
PolicyStore       : ActiveStore

Hope this helps. Thanks a lot for the effort!

Regards

**Comment by PlagueHO** [comment]
Sorry for taking so long to resolve this @paveldokov, but it is currently being addressed by this PR https://github.com/PowerShell/xNetworking/pull/206 which should be merged soon.

**Comment by PlagueHO** [comment]
Hi @paveldokov - PR #206 was merged a little while back. Have you had a chance to see if that fixes the issue?

**Comment by paveldokov** [comment]
Hello,

It is tested and working.
Sorry for the delayed response, but I had to go through change management process.

Thank you very much for the good work!

Regards,
Pavel

**Comment by PlagueHO** [comment]
Awesome! Thanks @paveldokov - no worries and great to hear! I'll close this one. Thanks again.

**Comment by paveldokov** [comment]
No, thank you for the module and the dedication!
