### ISSUE TITLE
Improve Test Coverage for all Resources

### ISSUE THREAD

**Issue by tysonjhayes** [PowerShell/xNetworking#14]
Currently DNS isn't covered at all that needs to be corrected. Firewall just has some basic tests hitting it. We should get this trued up.

**Comment by PlagueHO** [comment]
I'll throw some tests in for this if you like? I was getting terminating errors thrown by Get-TargetResource when executing Get-DSCConfiguration when the xfirewall resource was being used, so I was going to take a look at this resource anyway and writing pester tests is a good way to get my head around it. It may also give me some ideas on best way to rearchitect xIPAddress to get rid of the Test-Properties helper function - although I don't think there is too much to that really now that the gateway is split out.

**Comment by tysonjhayes** [comment]
Go ye forth @PlagueHO. I'm hoping to loop back these sometime next week and get my firewall fixes working.

**Comment by PlagueHO** [comment]
Hopefully this one can be closed now too as I think test coverage for the existing resources is at about 100% :)
