### ISSUE TITLE
Improve Information provided about Resource parameters in xNetworking Readme.md

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xNetworking#148]
The Readme.md doesn't contain enough information about each resource parameter. This results in often having to check the resource MOF files when building configurations.

This can be easily improved by adopting a standard format for presenting the resource parameters.

Convert Resource parameters in xNetworking Readme.md to the following format:
- **[Type] ParameterName** _(Read/Write/Required/Key)_: Description. Defaults to "default value" (if applicable). { _DefaultOption (if applicable)_ | Option2 | Option3 }.

I'll raise a PR in about a week if there are no objections?
@TravisEz13 ?

**Comment by kwirkykat** [comment]
@PlagueHO We used this format for PSDscResources after you started it for the Service resource. I like it 👍

**Comment by PlagueHO** [comment]
@kwirkykat - oh right, cool! I'll raise a PR this weekend for it :grin: Thanks

**Comment by PlagueHO** [comment]
Fixed by #159
