### ISSUE TITLE
Setting rules according to issue #150 creates notify event on every pass

### ISSUE THREAD

**Issue by marcinbojko** [PowerShell/xNetworking#151]
**We have first pass:
TEST**

```
$invokeParams = @{
  Name          = 'xFirewall'
  Method        = 'test'
  Property      = @{
    name = 'Allow_eScheduler'
    displayname = 'Firewall Rule for Allow_eScheduler'
    ensure = 'present'
    enabled = 'True'
    profile = @('Domain,Private')
    direction = 'Inbound'
    localport = @('33780', '33781')
    protocol = 'TCP'
    description = 'Firewall Rule for Allow_eScheduler'
    remoteaddress = @('10.112.0.21')
  }
  ModuleName = @{
    ModuleName      = "C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet_x/dsc_resources/xNetworking/xNetworking.psd1"
    RequiredVersion = "2.10.0.0"
  }
}
```

**TEST ends with** 

```
Debug: 2016-10-06 10:29:37 +0200 STDOUT> {"rebootrequired":false,"indesiredstate":false,"errormessage":""}

Debug: Wait object signaled
Debug: Waited 900 total milliseconds.
Debug: Dsc Resource returned: {"rebootrequired":false,"indesiredstate":false,"errormessage":""}

Debug: Dsc Resource Exists?: false
Debug: dsc_ensure: Present
Debug: ensure: present
```

Clearly, insedesiredstate is false.
So we have SET

```
$invokeParams = @{
  Name          = 'xFirewall'
  Method        = 'set'
  Property      = @{
    name = 'Allow_eScheduler'
    displayname = 'Firewall Rule for Allow_eScheduler'
    ensure = 'Present'
    enabled = 'True'
    profile = @('Domain,Private')
    direction = 'Inbound'
    localport = @('33780', '33781')
    protocol = 'TCP'
    description = 'Firewall Rule for Allow_eScheduler'
    remoteaddress = @('10.112.0.21')
  }
  ModuleName = @{
    ModuleName      = "C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet_x/dsc_resources/xNetworking/xNetworking.psd1"
    RequiredVersion = "2.10.0.0"
  }
}
```

**ends with**

```
Debug: 2016-10-06 10:29:38 +0200 STDOUT> {"rebootrequired":false,"indesiredstate":true,"errormessage":""}

Debug: Wait object signaled
Debug: Waited 200 total milliseconds.
Debug: Create Dsc Resource returned: {"rebootrequired":false,"indesiredstate":true,"errormessage":""}
Notice: /Stage[main]/Win_manage/Dsc_xfirewall[allow_Allow_eScheduler]/ensure: created
```

Notify is displayed properly - first run.
But on nex run we have the same situation: Test shows indesiredstate: false, SET ends with proper 'indesiredstate:true'
Value in FirewallSettings in inserted properly.

End again we have:

`Notice: /Stage[main]/Win_manage/Dsc_xfirewall[allow_Allow_eScheduler]/ensure: created`

**Comment by PlagueHO** [comment]
Hi @marcinbojko ,

Can you try changing the profile to be:
```powershell
profile = @('Domain','Private')
```
The important part is that this is an array of two items (Domain and Private), not a string containing 'Domain,Private'.

Does that help?

**Comment by marcinbojko** [comment]
Yes,  I'll check it ASAP.

**Comment by marcinbojko** [comment]
@PlagueHO , so with puppetlabs-dsc in version 1.2.0
so:

TEST:
```
$invokeParams = @{
  Name          = 'xFirewall'
  Method        = 'test'
  Property      = @{
    name = 'NotePadFirewallRule'
    displayname = 'Firewall Rule for Notepad.exe'
    ensure = 'present'
    enabled = 'True'
    profile = **@('Domain', 'Private')**
    direction = 'Inbound'
    localport = @('9091', '9090')
    protocol = 'TCP'
    description = 'Firewall Rule for Notepad.exe'
    localaddress = @('Any')
    remoteaddress = @('192.168.2.0-192.168.2.128,192.168.1.0/255.255.255.0')
  }
  ModuleName = @{
    ModuleName      = "C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet_x/dsc_resources/xNetworking/xNetworking.psd1"
    RequiredVersion = "3.0.0.0"
  }
}
```

TEST End with:
```
Debug: 2016-11-13 16:22:43 +0100 STDOUT> {"rebootrequired":false,"indesiredstate":false,"errormessage":""}

Debug: Dsc Resource returned: {"rebootrequired":false,"indesiredstate":false,"errormessage":""}

Debug: Dsc Resource Exists?: false
Debug: dsc_ensure: Present
Debug: ensure: present
```

SET
```
$invokeParams = @{
  Name          = 'xFirewall'
  Method        = 'set'
  Property      = @{
    name = 'NotePadFirewallRule'
    displayname = 'Firewall Rule for Notepad.exe'
    ensure = 'Present'
    enabled = 'True'
    profile = @('Domain', 'Private')
    direction = 'Inbound'
    localport = @('9091', '9090')
    protocol = 'TCP'
    description = 'Firewall Rule for Notepad.exe'
    localaddress = @('Any')
    remoteaddress = @('192.168.2.0-192.168.2.128,192.168.1.0/255.255.255.0')
  }
  ModuleName = @{
    ModuleName      = "C:/ProgramData/PuppetLabs/puppet/cache/lib/puppet_x/dsc_resources/xNetworking/xNetworking.psd1"
    RequiredVersion = "3.0.0.0"
  }
}
```
ends with
```
Debug: 2016-11-13 16:22:44 +0100 STDOUT> {"rebootrequired":false,"indesiredstate":true,"errormessage":""}

Debug: Wait object signaled
Debug: Waited 100 total milliseconds.
Debug: Create Dsc Resource returned: {"rebootrequired":false,"indesiredstate":true,"errormessage":""}
```
and, with complete notify:
```
Notice: /Stage[main]/Win_manage/Dsc_xfirewall[allow_my_rule2]/ensure: created
Info: /Stage[main]/Win_manage/Dsc_xfirewall[allow_my_rule2]: Scheduling refresh of Reboot[dsc_reboot]
Debug: /Stage[main]/Win_manage/Dsc_xfirewall[allow_my_rule2]: The container Class[Win_manage] will propagate my refresh event
Debug: Skipping reboot
Notice: /Stage[main]/Win_manage/Reboot[dsc_reboot]: Triggered 'refresh' from 1 events
Debug: /Stage[main]/Win_manage/Reboot[dsc_reboot]: The container Class[Win_manage] will propagate my refresh event
```

Ergo: no, nada, negative. niet - that's not it :(

**Comment by PlagueHO** [comment]
@marcinbojko - I'm not an expert on the use of DSC in Puppet.

Is there a way to get Puppet to output the Verbose log of the DSC Resource? If so, are you able to post the output of the Test-TargetResource? It should tell us which particular parameter of the firewall rule is failing the tests and I can then investigate from there.

Thanks for your help resolving this one!

**Comment by marcinbojko** [comment]
Yes, I'll do what I can ;)

**Comment by PlagueHO** [comment]
Hi @marcinbojko - did you have any luck getting the verbose output from Puppet so I could see which parameters were failing test Test-TargetResource call?

**Comment by marcinbojko** [comment]
Hi @PlagueHO - nope, but I'll ask guys from puppet dsc module.

**Comment by marcinbojko** [comment]
Ok. maybe it is a holliday spirit, but narowing it down:

> VERBOSE: Performing the operation "Invoke-CimMethod: Resourcetest" on target "MSFT_DSCLocalConfigurationManager".
> VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = Resourcetest,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/
> DesiredStateConfiguration'.
> VERBOSE: An LCM method call arrived from computer WIN-LO53EUODSPV with user sid S-1-5-21-1417678775-2642810764-439633799-500.
> VERBOSE: [WIN-LO53EUODSPV]: LCM:  [ Start  Test     ]  [[xFirewall]DirectResourceAccess]  
> VERBOSE: [WIN-LO53EUODSPV]:                            [[xFirewall]DirectResourceAccess] Test-TargetResource: Checking settings for firewall rule with Name 'NotePadFirewallRule'.
> VERBOSE: [WIN-LO53EUODSPV]:                            [[xFirewall]DirectResourceAccess] Test-TargetResource: Find firewall rule with Name 'NotePadFirewallRule'.
> VERBOSE: [WIN-LO53EUODSPV]:                            [[xFirewall]DirectResourceAccess] Test-TargetResource: Check each defined parameter against the existing firewall rule with Name 'NotePa
> dFirewallRule'.
> VERBOSE: [WIN-LO53EUODSPV]:                            [[xFirewall]DirectResourceAccess] Get-FirewallRuleProperty: Get all the properties and add filter info to rule map.
> VERBOSE: [WIN-LO53EUODSPV]:                            [[xFirewall]DirectResourceAccess] Test-**RuleProperties: RemoteAddress property value '192.168.2.0-192.168.2.128' does not match desired s
> tate '192.168.2.0-192.168.2.128,192.168.1.0/255.255.255.0'**.
> VERBOSE: [WIN-LO53EUODSPV]:                            [[xFirewall]DirectResourceAccess] Test-RuleProperties: Test Firewall rule with Name 'NotePadFirewallRule' returning False.
> VERBOSE: [WIN-LO53EUODSPV]:                            [[xFirewall]DirectResourceAccess] Test-TargetResource: Check Firewall rule with Name 'NotePadFirewallRule' returning False.
> VERBOSE: [WIN-LO53EUODSPV]: LCM:  [ End    Test     ]  [[xFirewall]DirectResourceAccess] False in 1.3120 seconds.
> VERBOSE: [WIN-LO53EUODSPV]: LCM:  [ End    Set      ]    in  1.5000 seconds.
> VERBOSE: Operation 'Invoke CimMethod' complete.

which seems to be related with: https://github.com/PowerShell/xNetworking/issues/169

**Comment by marcinbojko** [comment]
Looks like another (my) array mistake.
Passing it: 

remoteaddress = @('192.168.2.0-192.168.2.128','192.168.1.0')

instead of

remoteaddress = @('192.168.2.0-192.168.2.128,192.168.1.0/255.255.255.0')

**Comment by PlagueHO** [comment]
Oh right, cool! Thank you for letting us know - I might add a new example showing this usage as it is not obvious what the correct format would be.
