### ISSUE TITLE
Add CommonResourceHelper.psm1 module and update to use it

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xNetworking#152]
The xPSDesiredStateConfiguration includes a [CommonResourceHelper.psm1](https://github.com/PowerShell/xPSDesiredStateConfiguration/blob/dev/DSCResources/CommonResourceHelper.psm1) that includes several common functions.

xNetworking has quite a lot of replicated code that is contained in the CommonResourceHelper.psm1 file. So there would be some benefit to changing xNetworking to use these patterns (including making the move to HQRM easier).

**Comment by tysonjhayes** [comment]
To keep this issue updated the module was added but most resources do not use it at this time.

**Comment by PlagueHO** [comment]
@tysonjhayes - I'm working on this one now.
