### ISSUE TITLE
[New Resource] Proxy Server management

### ISSUE THREAD

**Issue by zjalexander** [PowerShell/xNetworking#158]
This has come up in a few places on the internet, but we don't have a complete solution on the gallery today. (http://stackoverflow.com/questions/29600767/setting-the-machine-proxy-via-dsc , https://p0w3rsh3ll.wordpress.com/2015/01/29/dsc-configuring-a-proxy/, https://p0w3rsh3ll.wordpress.com/2015/02/16/follow-up-configuring-a-proxy-with-dsc/)
This has come up as a request for Nano Server as well. 

I should be able to manage proxy server settings on Nano Server using DSC.

**Comment by PlagueHO** [comment]
@zjalexander - great idea! If no one else gets to it first I'll add it to my backlog.

**Comment by PlagueHO** [comment]
Doing a bit of spade work on this. It looks like the only way to configure the proxy in PS is via the registry. The settings are usually stored at this location:
Get-ItemProperty -Path 'HKCU:\Software\Microsoft\Windows\CurrentVersion\Internet Settings'

As far as settings go, is there anything outside of the standard Proxy settings shown in "Proxy Settings" (see below) that people would want to configure? 
![2016-10-28_20-35-28](https://cloud.githubusercontent.com/assets/7589164/19798542/31a5639c-9d4e-11e6-9ec7-e7a7c4c33e70.png)

To be clear though, this will configure the Windows (IE) Proxy settings only - if an application doesn't use these settings (Git for Windows is an example) then this resource will not affect that app.

I recommend that before proceeding with this resource a MOF is proposed (if someone else is going to work on this). Otherwise I'll propose a MOF :grin:

**Comment by johlju** [comment]
On Windows Server 2012 (and above) sometimes it is needed to use the cmdline tool `netsh winhttp import proxy source=ie` (of course after above comment is already set in IE). This is needed to for example to get Windows Update to work thru the proxy. Does not help to just set the proxy in IE.

Also using PowerShell code that needs to get thru an 'authenticating proxy' it might be necessary to run this.
```PowerShell
$webClient = New-Object System.Net.WebClient
$credential = Get-Credential
$webClient.Proxy.Credentials = $credential
```

Just something to think about. :smile:

**Comment by PlagueHO** [comment]
Good thinking @johlju - I'll keep that in mind.

I wrote a blog post exactly about this a while back:
https://dscottraynsford.wordpress.com/2016/06/24/allow-powershell-to-traverse-a-secure-proxy/
as we have an "enthusiastic" proxy at our office too :grin: .

The problem though is that the WebClient stuff only exists for the session it is created under - which for DSC will cease to exist once it is complete. So the above code doesn't really help much.

What I might suggest is we start with configuring the basic Proxy settings as well as setting the NETSH stuff, but leave the WebClient out. Does that work for you?

**Comment by johlju** [comment]
Yes, thought about that too. Lets start with the methods we can make persistent as you suggest.

This resource could be a requisite to another resource, that resource could get the proxy information we set in registry to use in its own session to traverse the proxy (usin webclient). If you follow me. :)

**Comment by PlagueHO** [comment]
@johlju - yep! Makes perfect sense!

I'm working on some other xNetworking stuff today, but I'll try and propose a MOF later on - if you could review the MOF that would be awesome!

**Comment by johlju** [comment]
Happy to review the MOF when you have put something together! :)

**Comment by zjalexander** [comment]
> The problem though is that the WebClient stuff only exists for the session it is created under - which for DSC will cease to exist once it is complete. So the above code doesn't really help much.

Hm, none of that is present on Nano Server, either. In fact, I don't even think IE is present on Nano Server.... I need to do some internal investigation.

**Comment by gaelcolas** [comment]
@zjalexander Have you got an update on the best approach to this?

I see two different things:
1. DSC Resource to Set IE Proxy (Does not apply to Nano?)
2. DSC Resource to set WinHTTP Proxy

I've been looking around and it sounds that the most flexible approach for 1 would be via [PInvoke](http://www.pinvoke.net/default.aspx/wininet/internetsetoption.html?diff=y) calling [InternetSetOption](http://msdn.microsoft.com/en-us/library/windows/desktop/aa385114(v=vs.85).aspx). As trying to construct the undocumented (afaik) Binary registry smells...

For 2, it *sounds* from the [WinHTTP Considerations](https://blogs.msdn.microsoft.com/ieinternals/2013/10/11/understanding-web-proxy-configuration/) paragraph from the (former) owner of the WinHTTP Proxy code that
> The user may attempt to configure the “default” proxy for WinHTTP [...] using netsh.exe

Looking at the documentation on [Winhttp.dll](https://msdn.microsoft.com/en-gb/library/aa384114(v=vs.85).aspx) (which is [present on Nano](https://msdn.microsoft.com/library/mt588480(v=vs.85).aspx#winhttp.dll)), I *assume* that's possible by passing a NULL handle as explained for querying:
> An application can query for the global proxy data (the default proxy) by passing a NULL handle.

Can you confirm that's right and the preferred approach?
I'd rather not start poking around if it's not the right direction...

**Comment by zjalexander** [comment]
Feedback from the Nano team is to not worry about handling the Nano case right now.

**Comment by PlagueHO** [comment]
Thanks for all the info @zjalexander and @gaelcolas - it does sound like calling InternetSetOption with PInvoke would be the only way to go. It is a pity there is no PowerShell (or CIM/WMI) native way of doing this.

**Comment by kewalaka** [comment]
@PlagueHO just ran into the same issue.  What about setting the system proxy, like suggested [here](https://p0w3rsh3ll.wordpress.com/2012/10/07/getsetclear-proxy/)?  Haven't had chance to test this idea yet, so might be nonsense, gets around the per-user issue however.

**Comment by kewalaka** [comment]
@PlagueHO - just curious why you don't think the registry approach is a reasonable option?  The link at the top [here](https://p0w3rsh3ll.wordpress.com/2015/02/16/follow-up-configuring-a-proxy-with-dsc/) covers the points you raise by being able to modify the system proxy and it mentions workaround required to make it go with WU/MU?

**Comment by PlagueHO** [comment]
@kewalaka - to be honest I don't recall why I said registry wasn't an option. It is an option (and I recently implemented a registry setting in one of the resources) - I'd prefer to use CIM or native cmdlet if possible, but if not then registry is OK. The method I thought should be avoided was using NETSH because that can get pretty problematic calling out to external executables and handling "text" output from them (especially when taking into account localization).

If you're up for submitting either a PR with the registry method then that is all good with me and I'm positive the community would definitely be keen for it. If you aren't able to do this (or someone else) then I'll try and get to it - but I've got a bunch of other resources and fixes I've got in my backlog.

**Comment by lavahot** [comment]
Any progress made with this? I've been trying to write a Chef cookbook that uses the methodologies you've laid out, but it's just not working correctly and wrangling the registry is extremely difficult. It would be a lot easier if the DSC were available to do this.

**Comment by PlagueHO** [comment]
Hi @lavahot - it is high up on my back log and I am hoping to get to it as soon as I can! I'd hoped someone else would get to it before me, but it seems not to be the case. I'll try and put some time into this next week.

**Comment by lavahot** [comment]
Thanks, @PlagueHO! I really appreciate it. :)

**Comment by lavahot** [comment]
So after doing a lot of work on debugging this, I've made a Chef cookbook that fulfills this functionality perfectly (proprietary, unfortunately). After running the [Process Monitor](https://docs.microsoft.com/en-us/sysinternals/downloads/procmon) to see how ticking each checkbox affected the registry, I determined that the binary strings are mandatory as no simple flag or string could reliably control the proxy settings consistently. This [SO question](https://stackoverflow.com/questions/4283027/whats-the-format-of-the-defaultconnectionsettings-value-in-the-windows-registry) was very useful as a dissection of each byte in the string. In fact, it made it very simple to build a string that could be converted into binary for insertion into the registry.

**Comment by PlagueHO** [comment]
Thanks for the info @lavahot - I've meant to get onto this for sometime now, but I've been snowed under (and more keeps coming in). I will try and get onto this as soon as I have time.

**Comment by PlagueHO** [comment]
Finally managed to clear a space this weekend so I'm really intending on getting on to this one tomorrow! Apologies for taking so long getting to this one.

**Comment by PlagueHO** [comment]
This is taking a little longer than I'd hoped. Unfortunately the DSC Configs on this page are not completely correct: https://p0w3rsh3ll.wordpress.com/2015/01/29/dsc-configuring-a-proxy/

This has been a slightly more accurate source of information:
https://blogs.msdn.microsoft.com/askie/2017/06/20/what-is-defaultconnectionsettings-key/

**Comment by lavahot** [comment]
Yeah, for this string construction, go look at the SO answer I linked you.
It's even better than that MSDN article.

**Comment by PlagueHO** [comment]
Thanks @lavahot - I had read that and it had helped, but it was only partial information. There is actually other parts of the binary that I needed to reverse engineer. I have completed that part now and it looks like it is working:
```powershell
        $proxySettings = @(0x46, 0x0, 0x0, 0x0, 0x8, 0x0, 0x0, 0x0, 0x1, 0x0, 0x0, 0x0)

        if ($EnableAutoDetection)
        {
            $proxySettings[8] = $proxySettings[8] + 8
        }

        if ($EnableManualProxy)
        {
            $proxySettings[8] = $proxySettings[8] + 2
        }

        if ($EnableAutoConfiguration)
        {
            $proxySettings[8] = $proxySettings[8] + 4
        }

        if ($PSBoundParameters.ContainsKey('ProxyServer'))
        {
            $proxySettings += @($ProxyServer.Length, 0x0, 0x0, 0x0)
            $proxySettings += [Byte[]][Char[]] $ProxyServer
        }
        else
        {
            $proxySettings += @(0x0, 0x0, 0x0, 0x0)
        }

        if ($ProxyServerBypassLocal -eq $true)
        {
            $proxySettings += @('<local>'.Length, 0x0, 0x0, 0x0)
            $proxySettings += [Byte[]][Char[]] '<local>'
        }
        else
        {
            $proxySettings += @(0x0, 0x0, 0x0, 0x0)
        }

        if ($PSBoundParameters.ContainsKey('AutoConfigURL'))
        {
            $proxySettings += @($AutoConfigURL.Length, 0x0, 0x0, 0x0)
            $proxySettings += [Byte[]][Char[]] $AutoConfigURL
        }

        $proxySettings += @(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
        $proxySettings += @(0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
```

**Comment by lavahot** [comment]
Looks right to me. Good work!

**Comment by PlagueHO** [comment]
I'm still working on this, but I have got the MOF file defined and much of the code complete:
```powershell
[ClassVersion("1.0.0"), FriendlyName("xProxy")]
class MSFT_xProxy : OMI_BaseResource
{
    [Key, Description("Specifies the resource is a single instance, the value must be 'Yes'."), ValueMap{"Yes"}, Values{"Yes"}] String IsSingleInstance;
    [Write, Description("Specifies if computer proxy settings should be set. Defaults to 'Present'."), ValueMap{"Present","Absent"}, Values{"Present","Absent"}] String Ensure;
    [Write, Description("Defines if the proxy settings should be configured for default connections, legacy connections or all connections. Defaults to 'All'."), ValueMap{"All","Default","Legacy"}, Values{"All","Default","Legacy"}] String ConnectionType;
    [Write, Description("Enable automatic detection of the proxy settings. Defaults to 'False'.")] Boolean EnableAutoDetection;
    [Write, Description("Use automatic configuration script for specifying proxy settings. Defaults to 'False'.")] Boolean EnableAutoConfiguration;
    [Write, Description("Use manual proxy server settings. Defaults to 'False'.")] Boolean EnableManualProxy;
    [Write, Description("The URL of the automatic configuration script to specify the proxy settings. Should be specified if 'EnableAutoConfiguration' is 'True'.")] String AutoConfigURL;
    [Write, Description("The address and port of the manual proxy server to use. Should be specified if 'EnableManualProxy' is 'True'.")] String ProxyServer;
    [Write, Description("Bypass proxy server for addresses starting with addresses in this list.")] String ProxyServerExceptions[];
    [Write, Description("Bypass proxy server for local addresses. Defaults to 'False'.")] Boolean ProxyServerBypassLocal;
};
```

**Comment by PlagueHO** [comment]
I've pretty much completed work on this one. I just need to get a bit more coverage on the unit tests and it should be good to go.

But if any of you (@lavahot, @kewalaka, @zjalexander) have some spare time, it would be great if you could try it out to ensure that it addresses your requirements. You can find it in this branch: https://github.com/PlagueHO/xNetworking/tree/Issue-158

You can find the examples etc. here: https://github.com/PlagueHO/xNetworking/tree/Issue-158/Modules/xNetworking/Examples/Resources/xProxySettings

I'd like to try and get the merged before the next resource kit release (coming up next week). So any feed back before then is gratefully accepted.
