### ISSUE TITLE
Resolve all PSSA Warnings

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xNetworking#166]
There are many warnings now showing up from the PSSA tests. These need to be resolved.

**Comment by PlagueHO** [comment]
Once #135 is completed it actually resolves all PSSA violations except for the Invoke-Expression ones.

**Comment by tysonjhayes** [comment]
I started working on this too, odd are you'll get done before I do but in case it's useful you can find my branch [here](https://github.com/tysonjhayes/xNetworking/tree/pssa_warning).

**Comment by PlagueHO** [comment]
@tysonjhayes - haha cool - I'm not actually trying to resolve the PSSA issues per se - it is just a by-product of implementing the HQRM guidelines (which will change a lot of lines, but not really change code itself). Hopefully we won't conflict too much :grin:

But if you can figure out a way of getting round the Invoke-Expression, that would be awesome - that is going to be the one that provides the most grief I reckon.
