### ISSUE TITLE
Breakup IP Address Resource to DHCP and Static

### ISSUE THREAD

**Issue by tysonjhayes** [PowerShell/xNetworking#17]
I think xIPAddress is trying to cover the gambit on what is really two distinct things.  One use case would be trying to assign a NIC a static IP address.  The other would be to assign the NIC to a DHCP server.

As the NIC can not have a static IP and be assigned to a DHCP server I prepose we break up the resources to handle those two different tasks.  This way we could have StaticIPAddress and DHCPAddress resources that just handle those use cases.

Thoughts?

**Comment by Dan1el42** [comment]
What about using Ensure = Absent to enable DHCP on a network interface instead breaking up the resource? If you specify Ensure = Present the IPAddress property must be required to configure an IP address.

Wouldn't that provide the same consistency and follow more closely the DSC concepts?

"Just my 2 cents"

**Comment by BladeFireLight** [comment]
That only makes sense if the Absent IP is the only IP on the NIC. Why not have the IP address take a string and allow DHCP as the value. then all IP's can be removed and DHCP turned on.

**Comment by tysonjhayes** [comment]
I guess the way I'm thinking of it is the division is really around how we implement the logc.

To borrow from [a blog post](http://www.adminarsenal.com/admin-arsenal-blog/using-powershell-to-set-static-and-dhcp-ip-addresses-part-1) I found setting up a static IP is done this way.

```powershell
$IP = "10.10.10.10"
$MaskBits = 24 # This means subnet mask = 255.255.255.0
$Gateway = "10.10.10.1"
$Dns = "10.10.10.100"
$IPType = "IPv4"

# Retrieve the network adapter that you want to configure
$adapter = Get-NetAdapter | ? {$_.Status -eq "up"}

# Remove any existing IP, gateway from our ipv4 adapter
If (($adapter | Get-NetIPConfiguration).IPv4Address.IPAddress) {
    $adapter | Remove-NetIPAddress -AddressFamily $IPType -Confirm:$false
}

If (($adapter | Get-NetIPConfiguration).Ipv4DefaultGateway) {
    $adapter | Remove-NetRoute -AddressFamily $IPType -Confirm:$false
}

 # Configure the IP address and default gateway
$adapter | New-NetIPAddress `
    -AddressFamily $IPType `
    -IPAddress $IP `
    -PrefixLength $MaskBits `
    -DefaultGateway $Gateway

# Configure the DNS client server IP addresses
$adapter | Set-DnsClientServerAddress -ServerAddresses $DNS
````

Where a DHCP is setup like this:
````powershell
$IPType = "IPv4"
$adapter = Get-NetAdapter | ? {$_.Status -eq "up"}
$interface = $adapter | Get-NetIPInterface -AddressFamily $IPType

If ($interface.Dhcp -eq "Disabled") {
    # Remove existing gateway
    If (($interface | Get-NetIPConfiguration).Ipv4DefaultGateway) {
        $interface | Remove-NetRoute -Confirm:$false
    }

    # Enable DHCP
    $interface | Set-NetIPInterface -DHCP Enabled

    # Configure the  DNS Servers automatically
    $interface | Set-DnsClientServerAddress -ResetServerAddresses
}
````

For DHCP this becomes of Ensure = 'Present' means set DHCP, Ensure = 'Absent' means remove the DHCP.

Static means much the same, set these IP Address, or remove the IP addresses.

I'm also considering we should change the static IP address to be "assign these IPs and only these IPs"

This would mean if your assigning the IP addresses it would be like this:
@(IP1, IP2, IP3, IP4)

If we want to remove one IP address it would need to be assigned like this:
@(IP1, IP2, IP4)

The test-targetresource would validate that all given IP addresses, and only those IP addresses are present, if its wrong it would remove all of the IPs and reassign them accordingly.

**Comment by PlagueHO** [comment]
Hopefully this issue is now resolved so can be closed?

**Comment by tysonjhayes** [comment]
Yup, thanks!
