### ISSUE TITLE
Wiki: Referencing SharePointDsc

### ISSUE THREAD

**Issue by johlju** [PowerShell/xNetworking#175]
The wiki is referencing SharePointDsc instead of xNetworking.

>![image](https://cloud.githubusercontent.com/assets/7189721/21963271/1a3ddb80-db38-11e6-8e98-19123ec67521.png)

**Comment by PlagueHO** [comment]
@tysonjhayes - I couldn't find this in any code, so I'm presuming it was added manually and this was just copy/paste error. So I fixed this by editing the side bar in the Wiki and changing it to xNetworking. Is that the correct way to do it?

**Comment by tysonjhayes** [comment]
Yup, it was a copy paste error, fix looks good.
