### ISSUE TITLE
Error in AppVeyor CI because NUPKG is not produced

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xNetworking#177]
An error is occurring at the end of the AppVeyor CI build process. It appears that the build is not producing the Nuget package:

![image](https://cloud.githubusercontent.com/assets/7589164/22010363/9d3fb70e-dced-11e6-90d3-ea9839aad0e8.png)

**Comment by tysonjhayes** [comment]
Took a few minutes to poke at this.

When I run this on my local machine I can't actually reproduce it.  If you look at the image you can see all of the produced files are appended with 3.1.43.0.

![image](https://cloud.githubusercontent.com/assets/651851/22127057/27b2653c-de4f-11e6-8241-978e0ca869d7.png)

However the nupkg file does not have the final .0 - why is beyond me. I set $env:AppVeyor_Build_Version on my local machine to match it produces the file correctly. 

![image](https://cloud.githubusercontent.com/assets/651851/22127170/af911822-de4f-11e6-9472-023a6249c5e1.png)

The way I see it we have to quick/dirty ways to fix.

1) Modify [this line](https://github.com/PowerShell/xNetworking/blob/dev/.appveyor/appveyor.psm1#L121) to not include the build number. I have no idea what that breaks but doesn't seem great to me.
2) Modify the next line to not specify the exact file name but filter on all nukpg files. ie:
````powershell
    Get-ChildItem -Path "$env:APPVEYOR_BUILD_FOLDER" -Filter '*.nupkg' | ForEach-Object -Process {
        Push-AppveyorArtifact $_.FullName -FileName $_.Name
    }
````
Downside with this one is we now upload all nupkg files which means if we generate more then the one we might end up with more then we intend. Not sure really.

**Comment by PlagueHO** [comment]
@tysonjhayes - I think I've found the problem:
- **Nuget.exe v3.5.0.1938**: This is the version downloaded by AppVeyor by [this line](https://github.com/PowerShell/xNetworking/blob/dev/appveyor.yml#L6). It produces a NUPKG with the trailing 0 **stripped off**.

- **Nuget.exe v3.4.0.1938**: This is the version I have on my machine - came with VS2015. It produces a NUPKG with the trailing 0 **retained**.

![image](https://cloud.githubusercontent.com/assets/7589164/22138723/ea0e761e-df46-11e6-8f77-d3d3d7c711b5.png)

So it looks like this is a behaviour that is implemented in Nuget 3.5 - although I haven't been able to find any specific mention of it.

I did a quick test and downloaded the 3.4.4 Nuget.exe from https://dist.nuget.org/win-x86-commandline/v3.4.4/NuGet.exe and gave that a try. It **retains** the trailing 0.

So I think the solution might be to specify the 3.4.4 version of Nuget.exe in the AppVeyor.yml:
```
 - appveyor DownloadFile https://dist.nuget.org/win-x86-commandline/v3.4.4/NuGet.exe
```

Whatcha reckon?

**Comment by johlju** [comment]
I got the same error over at xSQLServer. So I wait to see what your solution is a do the same :)

In the appveyor.yml in xSQLServer it is specified a minimum version, so I could also change that to a specific version.  

@PlagueHO great work finding that!

**Comment by johlju** [comment]
Hmm.. in xSQLServer its using `Install-PackageProvider` so I guess I have to change the entire row to solve this one.
But strangely this started happen on the December 31, on December 28 the build was passing, but from December 31 that the error appears. And the same version of package provider is being used. I guess some internals was changed.
I will try @PlagueHO solution this evening.

**Comment by johlju** [comment]
I have tested a bit...

When using "my own" AppVeyor connected to my fork of xSQLServer it fails when I push to my fork. In these two tests I printed out the version of the Nuget.exe. In the last I also printed the nuspec to see if it contained the right version. It did.

Failed with Nuget v3.4.4.1321:
https://ci.appveyor.com/project/johlju/xsqlserver/build/4.0.315.0#L4551

Failed with Nuget v3.4.3.0855
https://ci.appveyor.com/project/johlju/xsqlserver/build/4.0.316.0#L4015

But if I actually send in a PR to xSQLServer then it is working without any change to the .yml. Becuse it does not do the build step I guess:
https://ci.appveyor.com/project/PowerShell/xsqlserver/build/4.0.734.0#L3631

But when I merge code into 'dev' it is failing again (without any change to the .yml)
https://ci.appveyor.com/project/PowerShell/xsqlserver/build/4.0.730.0

I would liek to see this working on my fork before merging any changes into dev. I can't get the 3.4.x version to work either.
So only way I see now is actually removing the last `'.0'`, or filter on `"$($env:APPVEYOR_PROJECT_NAME)*.nupkg"` as @tysonjhayes suggest.

One thought though. Is there a nuget.exe somewhere in the build worker that is used, and not the one downloaded to the project folder 🤔

**Comment by PlagueHO** [comment]
@johlju - that is very odd! I'm looking into this further. Great investigation!

FYI: I think the last two links are transposed (the last one shows a successful run because the build is skipped, but the second to last is failing because of the missing .0).

**Comment by johlju** [comment]
If I change the .yml to the following it works; https://ci.appveyor.com/project/johlju/xsqlserver/build/4.0.318.0#L4046

```
      $nuGetPackageName = "$($env:APPVEYOR_PROJECT_NAME)*.nupkg"
      $nuGetPackagePath = (Get-ChildItem $nuGetPackageName).FullName
```

But then I tried to force it to use the nuget.exe in the project folder. And it WORKED! 
https://ci.appveyor.com/project/johlju/xsqlserver/build/4.0.319.0#L4003

```
& "$($env:APPVEYOR_BUILD_FOLDER)\nuget" pack ".\$($env:APPVEYOR_PROJECT_NAME).nuspec" -outputdirectory .
```

@PlagueHO @tysonjhayes Can you see if this works for you as well? If so then there is a nuget.exe in the build worker that messes things up... maybe? 

Do I get a local nuget.exe from Install-PackageProvider? 🤔 I will try to revert the code and see.

**Comment by PlagueHO** [comment]
I notice SharePointDsc uses the "latest" URL for Nuget.exe as well. But it doesn't look like it has been changed/rebuilt since mid Dec last year. @BrianFarnhill - have you by any chance run across this issue (Nuget stripping off .0 from end of the version number in the NUPKG filename).

**Comment by PlagueHO** [comment]
@johlju - good detective work! There is a Nuget.exe installed by default in the AppVeyor build worker. I'm not sure which version though.

However, in xNetworking (and SharePointDsc) one of the [first steps](https://github.com/PowerShell/xNetworking/blob/dev/appveyor.yml#L6) we perform is to download a the latest copy of Nuget.exe from Nuget.org into the build folder. However, we use [this code](https://github.com/PowerShell/xNetworking/blob/dev/.appveyor/appveyor.psm1#L116) to perform the Nuget Pack. So I'm not certain which copy is being used here - I'd actually like to refine this code so we are enforcing the copy being used.

You are right: It does sound like this is just a situation where multiple copies of Nuget.exe end up being available and more care and control needs to be put in to ensure the correct (3.4.4) version is being used.

**Comment by johlju** [comment]
Yes, I need to change so that nuget.exe is download like you do, and using the correct version. Using the current `Install-PackageProvider` install the package in [other folders](https://msdn.microsoft.com/en-us/powershell/reference/5.1/packagemanagement/install-packageprovider#description).

I did see that you are using `Install-PackageProvider` too [here](https://github.com/PowerShell/xNetworking/blob/dev/.appveyor/appveyor.psm1#L3). 

I tested with the latest nuget.exe and using the code that "force" using the one downloaded. It did not work (as you said it wouldn't). 
So changing back to 3.4.4 now and using the same way of starting nuget.exe as you (Start-Process). But I do it from the .yml file still.

I feel comfortable that this is the solution. But I will monitor here if you find a better solution. 😄

**Comment by PlagueHO** [comment]
I think the ```Install-PackageProvider``` cmdlet only downloads and installs the Nuget Provider assemblies to ```C:\Program Files\PackageManagement\ProviderAssemblies\nuget``` - not Nuget.exe itself - but I could be wrong here.

Good to hear it is working! I'm going to submit a PR through here but perform the entire change within the AppVeyor.psm1 file because I think having it out in the AppVeyor.yml leaves it open to problems. Also, as the AppVeyor.psm1 file is also being moved over to DSCResource.Tests (and generalized) to be used by all DSC Resources it makes sense to ensure the dependencies are correctly downloaded.

**Comment by johlju** [comment]
Yes, I agree. I do it in .yml because I'm not there yet with AppVeyor.psm1. :) I think I wait and see what you guys put together first in DSCResources.Tests. 

Side note: I did some work during the holidays to implement AppVeyor.psm1 (based on @tysonjhayes work here), but at the end I did not send in the PR to xSQLServer, still have it though. But I did take some bits an pieces which ended up in a common test here; https://github.com/PowerShell/xSQLServer/blob/dev/Tests/xSQLServerCommon.Tests.ps1.
It has helped tremendously to find bugs!

**Comment by BrianFarnhill** [comment]
@PlagueHO I haven't noticed it, but I did just have 4 weeks of leave after a fairly hectic run up to Christmas so I haven't been paying as much attention as I should be, so I'll get back in and have a look when I get a minute.

**Comment by PlagueHO** [comment]
@BrianFarnhill - thank pal! 

@tysonjhayes, @johlju - I'm going to fix this issue when I implement support for https://github.com/PowerShell/DscResources/issues/205 in this resource module. I've added code in DSCResource.Tests to ensure a known Nuget.exe is downloaded and used in every case (rather than whatever is found in the build worker).

**Comment by johlju** [comment]
@PlagueHO Sounds great!

**Comment by PlagueHO** [comment]
@johlju - I've just finished the changes to DSCResource.Tests and have so far tested it with xNetworking, xDFS and I'm in process of testing it with SharePointDsc and xSQLServer.

Forcing the use of a specific Nuget.exe (which the new AppVeyor.psm1 downloads the $ENV:Temp) resolves the version number NUPKG issue.

Once I've completed the tests on xSQLServer and SharePointDsc with this new AppVeyor.yml I'll submit the PR to DSCResource.Tests. Once that is through I can submit the PR's to each repo (xNetworking, xSQLServer, SharePointDsc and xDFS) to bring them over to using the AppVeyor.psm1.

The changes are pretty minimal (you can see the xDFS ones here: https://github.com/PlagueHO/xDFS/blob/Use-AppVeyor-Module/appveyor.yml). It is cloning DSCResource.Tests from my repo at the moment (so I can test).

**Comment by johlju** [comment]
@PlagueHO Awesome work! 👍  Looking forward getting this to xSQLServer as well, so your PR a welcomed! 😄

**Comment by PlagueHO** [comment]
@tysonjhayes - I've fixed this issue in the PR to move AppVeyor.psm1 over to DSCResource.Tests. Once that is through we can update xNetworking to use it (I've got the PR ready to go). This will fix the Nuget.exe problem.

**Comment by PlagueHO** [comment]
@kwirkykat - xNetworking is scheduled for release next week, but this issue is currently blocking release. The fix is contained in the PR I submitted to DSCResource.Tests (https://github.com/PowerShell/DscResource.Tests/pull/84). Let me know if you think the change to DSCResource.Tests won't be merged in time and I'll see about cross-porting the fix for this - although I'd rather avoid it if possible.

Once the PR for DSCResource.Tests has gone through, there will still need to be a PR merged into this repo as well. So the timing might be tight.

**Comment by kwirkykat** [comment]
@PlagueHO I can release xNetworking whenever it's ready in-between main DSC Resource Kit releases if this doesn't get done by Wednesday.

But also, we don't actually release the package that AppVeyor creates right now. We probably should (so it's really good this is getting fixed 👍 ), but right now we don't. We clone the repo locally and then just call Publish-Module on the cloned module's path. So I could still release it on Wednesday even with this bug if you'd like.

**Comment by tysonjhayes** [comment]
If this isn't blocking release then ship it! Well get it patched up but no sense in blocking release.

**Comment by PlagueHO** [comment]
@tysonjhayes - doh! I though I responded to this last night (must have not clicked comment). But yep I reckon we can definitely release this.
