### ISSUE TITLE
Create Gateway Resource

### ISSUE THREAD

**Issue by tysonjhayes** [PowerShell/xNetworking#18]
Given that a gateway is set at the resource level, and DNS is already its own resource, I'm thinking it would make sense to set the default gateway as its own resource as well. This would break up the logic for the resources into more descrete components and allow more targeted changes in our code fixes and for setting the configuraiton.

Thoughts?

**Comment by iainbrighton** [comment]
I agree that the gateway resource should be in a separate resource. There may be times you don't want to set a gateway (on a second NIC for example) but the IPAddress resource currently requires this!

**Comment by PlagueHO** [comment]
:+1: 
This change does make sense to me and would simplify a lot of my configs.

Presumably the schema would be something like this?
```powershell
[ClassVersion("1.0.0"), FriendlyName("xGatewayAddress")] 
class MSFT_xGatewayAddress : OMI_BaseResource
{
  [Write] string Address;
  [Write, Description("Ensure the presence/absence of the resource"), ValueMap{"Present", "Absent"},Values{"Present", "Absent"}] String Ensure;
  [Key] string InterfaceAlias;
  [Key,Write,ValueMap{"IPv4", "IPv6"},Values{"IPv4", "IPv6"}] string AddressFamily;
};
```
I set both IPv4 and IPv6 gateways on the same interface usually so ideally it would support both :)

**Comment by tysonjhayes** [comment]
Yeah that seems pretty good to me. I won't have time for a bit to get started on it but if if anyone wants to take a pass I'd gladly do a code review.

**Comment by PlagueHO** [comment]
I'm happy to take it on if it's good with you. After all, it'll simplify my configs :)

**Comment by tysonjhayes** [comment]
Consider it yours @PlagueHO

**Comment by tysonjhayes** [comment]
This is fixed, closing this out. Thanks everyone!
