### ISSUE TITLE
xHostsFile: Refactor Logic for speed and consistency across resources

### ISSUE THREAD

**Issue by tysonjhayes** [PowerShell/xNetworking#180]
I'm refactoring xHostsFile to increase performance for the Get-TargetResource and refactoring the logic across the module. This will include fixes for #176. I'm also rewriting some of the integration tests to cover more broader test coverage (run a single line remove, run a multi-line add, run a multi-line remove).

**Comment by PlagueHO** [comment]
I think you completed this one. Closing.
