### ISSUE TITLE
xNetworkAdapterRegisterDNS

### ISSUE THREAD

**Issue by gmatusko** [PowerShell/xNetworking#184]
It would be good if there was a way we could disable a NIC from registering with a DNS server.  This is helpful when using DSC to setup clusters as you don't want to register the nic attached to the cluster network.

**Comment by PlagueHO** [comment]
Hi @gmatusko - Can't this be done using the [xDNSConnectionSuffix](https://github.com/PowerShell/xNetworking/wiki/xDnsConnectionSuffix) resource? The name of this resource is actually a bit misleading - it should have really been called xDNSClient - but I think it does what you need.

**Comment by gmatusko** [comment]
Thanks PlaqueHO, totally missed that probably because the name is misleading and never found the wiki page you linked to.  I agree, that resource should be rename to xDnsClient for sure.
