### ISSUE TITLE
Need a wildcard or query for InterfaceAlias property in resources like xIPAddress, xDNSServerAddress, etc.

### ISSUE THREAD

**Issue by GoateePFE** [PowerShell/xNetworking#187]
If I am applying a config to an existing server I have no idea what the interface alias has been named. There is no practical way to know that at the time the MOF is generated from a remote server at scale. (You could remotely query 1000 servers for this, but it is not practical.) For example, need a way built into the resources to apply to all interfaces that are connected except isatap and loopback. Perhaps a WQL string or some other technique.

**Comment by PlagueHO** [comment]
Hi @GoateePFE - thanks for raising this. I definitely understand the issue here.

One other possible solution to this problem might to actually rename the Network Adapter as a first step of the DSC. E.g.
```powershell
xNetAdapterName {
   Name = 'Primary Adapter'
   InterfaceDescription = 'Hyper-V Network Adapter Name'
}
xDNSServer {
    InterfaceAlias = 'Primary Adapeter'
    AddressFamily = 'IPv4'
    Address = '10.0.0.10','10.0.0.20'
}
```
Does this look like it might work as a solution to your issue?

If so, we are in the process of creating the xNetAdapterName resource (see [this issue](https://github.com/PowerShell/xNetworking/issues/115)).

**Comment by GoateePFE** [comment]
I reviewed the new resource proposal. That may work. It would help a lot of people. Thanks.

**Comment by PlagueHO** [comment]
@GoateePFE - Ok. cool. I'm just finishing up some work on xCertificate this weekend but will put this one as my next priority to get out. It's been hanging around for a while so definitely needs to get sorted.

**Comment by RobBiddle** [comment]
I ran into this issue as well.  AWS T2 Instances all end up with their primary adapters named "Ethernet", however several other instance types end up with "Ethernet 2" instead.

I ended up writing my own script resource instead, like this:
[https://gist.github.com/RobBiddle/049f1c13bd5f1730fb5412703b7e8153#file-dsc_script_dnsclientservers-ps1](url)

**Comment by brwilkinson** [comment]
xDnsConnectionSuffix already seems to work with wildcards. * would change every adapter *Eth* changes adapters that match that pattern.

**Comment by PlagueHO** [comment]
I'm beginning work on this one now. It requires modification of the xNetworkAdapter module to enable specifying an adapter by specific parameters. This module also needs to be updated to HQRM style guidelines.

**Comment by PlagueHO** [comment]
Sorry about the delay getting this done @GoateePFE .

The new xNetAdapterName resource has been submitted for review (see https://github.com/PowerShell/xNetworking/pull/203). It may take a little while to get reviewed depending on how busy the other repo admins are - but I'm aiming for it to be included in the next release of the DSC Resource Kit.
