### ISSUE TITLE
Example 4 Wiki entry for xFirewall has display issues

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xNetworking#194]
https://github.com/PowerShell/xNetworking/wiki/xFirewall

**Comment by tysonjhayes** [comment]
Likely this is a bug in how the docs get generated, or we missed up the mof file some how. Good catch though!

**Comment by PlagueHO** [comment]
@tysonjhayes - seems the likely causes! I'll take a look over the weekend (too busy playing with VS2017 :grin:) .

**Comment by PlagueHO** [comment]
@tysonjhayes - found the problem. Caused by a bug in the auto documentation generation. I've got a PR open there already (to convert the wiki to valid MD). I'll add the fix to that PR.

There are some inconsistencies in the examples though so I'll fix those.

**Comment by PlagueHO** [comment]
This is now resolved so closing.
