### ISSUE TITLE
NIC Alias Rename

### ISSUE THREAD

**Issue by matthitchcock** [PowerShell/xNetworking#196]
Hi

There was an issue open regarding renaming NIC Aliases but I can't seem to find it now. I don't see this functionality has been introduced into the xNetworking module yet. I just wondered if anyone is working on it? If not, I can pick this one up.

The requirements I have are:
- Rename a specific NIC Alias in a New Server scenario where only the MAC address is known

There is a scenario, however, where Virtual NICs using the Hyper-V Virtual Switch can have duplicate MAC addresses, so I am experimenting with this in a module I am working on to further filter based on if the NIC is physical or virtual, the Interface ID (if known), the Device Name and potentially the Description also.

If someone is working on this functionality already I'd be happy to connect. If not, I'd be happy to contribute to the Resource.

Thanks

**Comment by PlagueHO** [comment]
Hi @matthitchcock - There have actually been a few. But this was the most recent one where it was discussed:
https://github.com/PowerShell/xNetworking/issues/187

There was this issue I raised as well:
https://github.com/PowerShell/xNetworking/issues/122

However, the most likely issue you're talking about is this:
https://github.com/PowerShell/xNetworking/issues/115

It contains the basic design requirements. We had thought it best to use the [xNetworkAdapter](https://github.com/PowerShell/xNetworking/blob/dev/Modules/xNetworking/xNetworkAdapter.psm1) module that @TravisEz13 created early on to identify a Network Adapter based on a set of parameter and then rename the adapter found with that name.

I actually did something very similar in [xCertificateExport](https://github.com/PowerShell/xCertificate/tree/dev/DSCResources/MSFT_xCertificateExport) a couple of weeks ago (I based the design of this to some degree on what Travis did.

But I haven't made any progress on this (lack of time right now). So if you're interested in having a go then let me know and I'll put the issue as in progress! All help is greatly appreciated.

**Comment by matthitchcock** [comment]
Hi

Please have a look at https://github.com/matthitchcock/xNetworkAdapterAlias/blob/master/xNetworkAdapterAlias.psm1

These are the initial functions that I have working in my environment. The intention is that they are used on brand new servers where only Physical NIC's are configured so that the initial Alias Names can be set.

This can obviously be enhanced down the road.

**Comment by PlagueHO** [comment]
Hi @matthitchcock - as 4.1.0.0 has been released with the new xNetAdapterName resource, can we close this one?

**Comment by PlagueHO** [comment]
Hi @matthitchcock - I'll close this one now. If you run across any issues, please open an issue. Thank you!
