### ISSUE TITLE
xDnsServerAddress needs to set secondary

### ISSUE THREAD

**Issue by DarenDaigle** [PowerShell/xNetworking#198]
I cannot find a way that xDnsServerAddress can set the secondary Address

Daren Daigle

**Comment by PlagueHO** [comment]
Hi @DarenDaigle - it isn't actually clear from the documentation, but you can specify multiple DNS Server Addresses in xDnsServerAddress:
```powershell
configuration Example
{
    param
    (
        [string[]] $NodeName = 'localhost'
    )

    Import-DscResource -Module xNetworking

    Node $NodeName
    {
        xDnsServerAddress DnsServerAddress
        {
            Address        = '10.0.0.8','10.0.0.10'
            InterfaceAlias = 'Ethernet'
            AddressFamily  = 'IPv4'
            Validate       = $true
        }
    }
}
```
I'll get some changes to made to the documentation generation and add an additional example to show this. I'll keep this issue open until this has been resolved.

https://github.com/PowerShell/DscResource.Tests/issues/135

Does this solve your issue?
