### ISSUE TITLE
Enabling/Disabling of LSO/TSO 

### ISSUE THREAD

**Issue by gammalost** [PowerShell/xNetworking#202]
VMware states that for [performance reasons](https://pubs.vmware.com/vsphere-60/index.jsp?topic=%2Fcom.vmware.vsphere.networking.doc%2FGUID-D80AEC2F-E0DA-4172-BFFD-B721BF36C2E8.html) when virtualizing Windows machines one might want to disable TSO/LSO .

Is this something that would be beneficial to add to **xNetworking** as a new resouce **xNetAdapterLso** ?

**Comment by PlagueHO** [comment]
Hi @gammalost - absolutely - that sounds like something that belongs in here. We should already have a similar resource pattern floating around here somewhere that would be easy to clone and modify to suit this purpose.

**Comment by gammalost** [comment]
@PlagueHO Great! I'll get on it right away.
