### ISSUE TITLE
xIPAddress doesn't support setting multiple IP Addresses on a single interface

### ISSUE THREAD

**Issue by ChrisLGardner** [PowerShell/xNetworking#205]
Currently xIPAddress removes any existing IP addresses on an interface and then sets them to the specified one but there are use cases for setting multiple IP addresses on a single interface. As IPAddress is a string this would mean having multiple xIPAddress in the configuration but the one to run last will take precedence (and may change each time if ApplyAndAutoCorrect is used).

The fix would be to have IPAddress accept a string array and then compare that to the existing IP Addresses on that interface. 

I can put together a PR and do some testing to ensure this doesn't break any existing configurations.

**Comment by ChrisLGardner** [comment]
As mentioned in the the pull request, arrays can't be Key values in the schema. 

I'm not sure how important it is that IPAddress be a Key, before this change I can see it would be useful to have unique IPAddress values if using multiple xIPAddress configurations but with this change it would only be necessary to have 1 per Interface.

**Comment by PlagueHO** [comment]
Hi @ChrisLGardner - I've started a review of this and I think that this might be breaking change.

It won't affect most usage scenarios, but it depends on how the resource was being used. So according to the guidelines (https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md#breaking-changes) we need to open this for the community to discus for a bit.

Your proposal looks pretty good, but I'm not completely sure how the support for specifying a different prefix length for each IP works. Could you show an example?

**Comment by ChrisLGardner** [comment]
I'll add some examples when I get a chance this weekend. 

Further thought on my earlier commit to make prefixLength. I can see cases where you'd want to set multiple addresses on a single adapter across multiple prefixes, specifying each in their own xIpAddress block. It's probably not a common situation though, more likely you'd specify a few addresses on a single prefixlength on the same adapter and then use a different adapter for a different prefixlength. 

Can you give an example of when this might be a breaking change? I'd guess that if a configuration doesn't have a prefixlength specified then making it a key would be a breaking change but as that wasn't defaulting to a preset value (like get and test are) previously I'm not sure how that behaved if you didn't give it a value.

**Comment by ChrisLGardner** [comment]
Example of specifying multiple prefix lengths:

```
xIPAddress EthernetSlash16Range {
    IPAddress = '172.100.1.4','172.100.1.5'
    InterfaceAlias = 'Ethernet'
    PrefixLength = 16
    AddressFamily = 'IPv4'
}

xIPAddress EthernetSlash24Range {
    IPAddress = '192.168.10.5','192.168.10.6','192.168.10.7'
    InterfaceAlias = 'Ethernet'
    PrefixLength = 24
    AddressFamily = 'IPv4'

}
````

**Comment by PlagueHO** [comment]
Hi @ChrisLGardner - ah! I see now! That makes sense.

A breaking change is no problem (it'll just cause the major build number to be incremented).

But the reason why this would be considered a breaking change is that it'll change the output of IPAddress in Get-TargetResource from a single string to an array of strings. In 99% of usage scenarios this won't break any configs or automation, but this will have an effect on people using this resource from Chef. But what is really a breakage is a bit of a gray area.

@tysonjhayes - If you're about would you mind throwing in your thoughts?

Thanks again for putting up with all my queries etc and all your work - you've been doing heaps of great stuff!!!

**Comment by johlju** [comment]
I usually set a breaking change on all PR's that change the behavior of existing parameters and when existing output is changed. 
I also have set a breaking change when a resource went thru heavy changes internally. Like changing how a setup process is started in xSQLServer. Because that could potentially change how, when and if error messages are thrown.
