### ISSUE TITLE
xNetAdapterName: Using Name as detection parameter does not work

### ISSUE THREAD

**Issue by johlju** [PowerShell/xNetworking#207]
When using this configuration.
```
xNetAdapterName (New-ResourceName -Name 'RenameNIC')
{
    NewName = 'Private1'
    Name = 'Ethernet0'
}
```
It gives the error

```
VERBOSE: [SQLTEST6]: LCM:  [ End    Test     ]  [[xNetAdapterName]RenameNIC]  in 0.1560 seconds.
PowerShell DSC resource MSFT_xNetAdapterName  failed to execute Test-TargetResource functionality with error message: System.InvalidOperationException: A Network Adapter matching the parameters was not found. Please correct the properties and try again. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : SQLTEST6
```

Shouldn't this work? If it is already a NIC with the correct (new) name the Test-TargetResource should be return $true?

**Comment by johlju** [comment]
@PlagueHO I know there is not an example for this configuration. But It did work. It did rename the NIC. Just the second run did not work. 😄

**Comment by ChrisLGardner** [comment]
Looks like the parameters being passed to Find-NetworkAdapter aren't accounting for the change in name. Just putting together a fix for it now and will submit it soon.

**Comment by PlagueHO** [comment]
Good catch @johlju and @ChrisLGardner ! That is a really obvious flaw I should have thought of (or at least covered with automated tests). @ChrisLGardner has put through a PR so I'll review it now. Thanks guys.

**Comment by johlju** [comment]
@PlagueHO @ChrisLGardner Great work guys! Thanks! Though I think I see a flaw in the fix... Please correct me if I'm wrong. But if 'Name' would be assigned to an adapter name that does not exist, then it will always error out with that adapter "NewName" does not exist? That might be confusing.
I this should be fixed, i can add a new issue for it.

**Comment by PlagueHO** [comment]
Great catch @johlju - you're very right. I've raised the issue and will get the fix done this weekend:
https://github.com/PowerShell/xNetworking/issues/209

Thanks for being so onto it! :grin:

**Comment by johlju** [comment]
Awesome! Was just curious how it was resolved (always learn something new when looking at others code), but I looked and went "hmm... wait..." :smile:
