### ISSUE TITLE
Breaking change: Get-LocalizedData command

### ISSUE THREAD

**Issue by glennmate** [PowerShell/xNetworking#213]
```
PS C:\Users\GlennMate> Install-Module xNetworking -Force
PackageManagement\Install-Package : A command with name 'Get-LocalizedData' is already available on this system. This
module 'xNetworking' may override the existing commands. If you still want to install this module 'xNetworking', use
-AllowClobber parameter.
At C:\Program Files\WindowsPowerShell\Modules\PowerShellGet\1.0.0.1\PSModule.psm1:1772 char:21
+ ...          $null = PackageManagement\Install-Package @PSBoundParameters
+                      ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (Microsoft.Power....InstallPackage:InstallPackage) [Install-Package],
   Exception
    + FullyQualifiedErrorId : CommandAlreadyAvailable,Validate-ModuleCommandAlreadyAvailable,Microsoft.PowerShell.Pack
   ageManagement.Cmdlets.InstallPackage
```

As of the 4.0.0.0 release today, this module now conflicts with the newly released 3.0.0.0 version of xStorage. The only way to install this module is to use `Install-Module xNetworking -Force -AllowClobber`. This should break aliases between DSC resources. 

Please address ASAP, this is a big breaking change.

**Comment by PlagueHO** [comment]
Thanks for raising this @glennmate 

I'll get this fixed ASAP (xStorage will also need the same fix).

**Comment by PlagueHO** [comment]
Hi @glennmate - I've submitted the changes to the 4 resources that will potentially conflict (xStorage, xNetworking, xCertificate, xDFS). I'll need to wait for someone to review them so I can merge them.

Once that is done I'll see if I can get the DSC team to do a special release for these ones (at least xStorage) to prevent the conflicts.

I've also added some new integration tests that should prevent this sort of conflict from happening (at least from these 4 modules).

@kwirkykat - is it possible to rerelease xStorage after the PR in xStorage is merged to resolve this conflict?

**Comment by PlagueHO** [comment]
@glennmate - I've made the changes now and they've all been merged. I just need to see if the DSC Resource team can re-release them (only needs one of them to be re-released for now).

**Comment by PlagueHO** [comment]
@glennmate - a new version of xStorage, xCertificate and xNetworking have all been released to the PowerShellGallery now.

I have confirmed that xNetworking and xStorage can both be installed without using -AllowClobber now.

Sorry again about the conflict!

Also, do note that the latest xStorage has a breaking change in it that will require most configs to have minor updates made (change DiskNumber to DiskId).

Could you please close this if the fix solves the issue for you?

**Comment by PlagueHO** [comment]
Hi @glennmate - I'm going to close this issue now, but if it is still occurring, please reopen this and let us know. Thank you!
