### ISSUE TITLE
configuration of the firewall

### ISSUE THREAD

**Issue by kewalaka** [PowerShell/xNetworking#218]
I use [xDSCFirewall](https://github.com/theonlyway/xDSCFirewall) in order to configure the firewall zones, I've suggested to the author that this would be a good candidate for merging into xNetworking.

The author is supportive: https://github.com/theonlyway/xDSCFirewall/issues/26

I'd suggest this should be another resource separate from xFirewall, but not sure what it should be called, perhaps xFirewallProfile?

**Comment by PlagueHO** [comment]
Hi @kewalaka - this looks like it would be a great addition to xNetworking. And the name xFirewallProfile looks right to me. @tysonjhayes - any thoughts?

**Comment by PlagueHO** [comment]
Hi @kewalaka,

I've completed this one now. It will still need to be reviewed and merged.

If you want to try it out, you can find it here:
https://github.com/PlagueHO/xNetworking/tree/Issue-249

**Comment by kewalaka** [comment]
@PlagueHO Great, thanks for this.  I see it has been merged into the dev branch.  I'm on holiday at the moment, and restructures where I work have disestablished my existing role, so it might be a while before I put this to practical use :)

**Comment by PlagueHO** [comment]
@kewalaka - Disestablished while on holiday is pretty rotten! No worries about using it -it was a feature we needed either way :grin: Hope you find a new role!
