### ISSUE TITLE
DNS Connection Suffix Resource

### ISSUE THREAD

**Issue by iainbrighton** [PowerShell/xNetworking#23]
It would be good to be able to configure a connection suffix on a NIC. There are times when this is required (like in a multi-homed networking environment). I think this should probably be a new, descrete resource. Thoughts?

**Comment by tysonjhayes** [comment]
I'm not sure I'm following this, could you give an example of what you are trying to do?

**Comment by iainbrighton** [comment]
Just like configuring the DNS server address, be able to manage these:

![image](https://cloud.githubusercontent.com/assets/7023258/9783760/ade76b68-579e-11e5-88ed-ad5d9249306d.png)

The code to set the connection suffix is
```powershell
Set-DnsClient -InterfaceAlias "Ethernet" -ConnectionSpecificSuffix myzone.example.com
```

**Comment by tysonjhayes** [comment]
Ah now I get it, yeah, let's do it. :+1:
