### ISSUE TITLE
xNetworkTeamInterface Test method fails when using a 0 value for VLANID

### ISSUE THREAD

**Issue by matthitchcock** [PowerShell/xNetworking#248]
I am using the latest version of the resource and this can be seen in the Master branch. When using a VLANID of 0, the Set method will convert the parameters to use -Default. When running the Test method however, it fails, because the VLANID is specified in the configuration as 0, but the cmdlets return $null.

There is no transform done on the 0 value in the Test method.

**Comment by PlagueHO** [comment]
Hi @matthitchcock , Thanks for submitting this. I'll take a look at this tonight or tomorrow night and see if I can get a fix through (unless someone gets to it before me).

**Comment by matthitchcock** [comment]
I can add the line of code needed, do I need to update the release notes and so forth as well or is that taken care of after the Pull Request is accepted and before the Release? Is there a guide to any tasks that need to be done?

**Comment by PlagueHO** [comment]
Hi @matthitchcock - I'm sorry I didn't get to this sooner (I'm a bit behind I'm afraid). But your help would be greatly appreciated - and I'd be delighted to help you get this added.

There is a detailed guide on contributing over [here](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md). It covers pretty much everything you need to know. You'll want to make sure you submit your PR to the Dev branch. I also wrote a blog series on contributing a couple of years back that might help (https://dscottraynsford.wordpress.com/2015/12/14/creating-professional-dsc-resources-part-1/). The trickiest part is usually updating the automated tests.

I'm happy to help guide you through the process, but I'll just be a bit snowed under with my day job till after the 7th of Sept so might not be able to provide quick feedback till after that :cry:

**Comment by PlagueHO** [comment]
Closed by #262
