### ISSUE TITLE
xFirewall: Need a way of enabling built-in Firewall Rule without setting all properties

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xNetworking#25]
An example:
I was trying to use xFirewall to enable the built-in Firewall rules for FSRM:
![before](https://cloud.githubusercontent.com/assets/7589164/9892704/70499db4-5c65-11e5-9554-4cdceb6cdf83.png)
Using:
```powershell
xFirewall FSRMFirewall8
{
	Name = "FSRM-SrmSvc-In (RPC)"
	State = "Enabled"
	Access = "Allow"
}
```

It was enabling the rule just fine, but was replacing the properties:
![after](https://cloud.githubusercontent.com/assets/7589164/9892740/e4f23130-5c65-11e5-867d-90f30556dab2.png)

This can be worked around by manually setting all the properties of the Firewall rule but it is a bit of a pain, especially as the built in rules contain a lot of settings and there are often a lot of them - e.g. 8 rules for FSRM.

It would be nice if this would enable a built-in rule:
xFirewall FSRMFirewall8
{
	Name = "FSRM-SrmSvc-In (RPC)"
	State = "Enabled"
}

It would be possible to implement a special code path for when only the Name and State are passed and the rule exists that just fires:
Enable-NetFirewallRule or Disable-NetFirewallRule

Or is there a better way of doing this? I'm not completely sure that this would be a 100% obvious way of using the xFirewall resource because if any other parameter was set with State it would revert to the Delete and Recreate method which would still remove all properties of the built-in rule. Perhaps an new resource could be created for just disabling/enabling existing firewall rules?

**Comment by PlagueHO** [comment]
I've been thinking about this issue and I think I can see a way the resource could be changed to support this user story fairly easily.

The issue at the moment is in lines 131-134 of MSFT_xFirewall.psm1:
```powershell
Remove-NetFirewallRule -Name $Name

# Set the Firewall rule based on specified parameters
New-NetFirewallRule @PSBoundParameters
```
This code fires whenever a rule needs to be updated. This effectively destroys the structure of a built in rule.

What could be done instead is to build a @splat object out of the PSBoundParameters and then modify the splat object adding, removing or tweaking any parameters required and then splatting it on Set-NetFirewallRule (removing the Remove/New).

Pretty much just this would do (perhaps some tweaking would be required):
```powershell
$Splat = $PSBoundParameters
Set-NetFirewallRule @Splat
```

This would mean that the default values on the following parameters would need to be removed from Set-TargetResource and Test-TargetResource:
* DisplayName
* DisplayGroup
* Action
* Profile

Defaults could still be used, but instead of on the properties, they would be set down between lines 141-142 - e.g. change:
```powershell
Write-Verbose "$($MyInvocation.MyCommand): We want the firewall rule [$Name] to exist, but it does not"
New-NetFirewallRule @PSBoundParameters
```
To:
```powershell
Write-Verbose "$($MyInvocation.MyCommand): We want the firewall rule [$Name] to exist, but it does not"
if (-not $PSBoundParameters.DisplayName ) { $PSBoundParameters += @{ DisplayName= $Name } }
if (-not $PSBoundParameters.DisplayGroup) { $PSBoundParameters += @{ DisplayGroup= 'DSC_FirewallRule' } }
if (-not $PSBoundParameters.Action) { $PSBoundParameters += @{ Action= 'allow' } }
if (-not $PSBoundParameters.Profile) { $PSBoundParameters += @{ Profile= 'any' } }
New-NetFirewallRule @PSBoundParameters
```
The defaults could then be set on the parameters in Test-RuleProperties instead:
```powershell
function Test-RuleProperties
{
    param (
        [Parameter(Mandatory)]
        $FirewallRule,
        [String] $Name,
        [String] $DisplayName = $Name,
        [String] $DisplayGroup,
        [String] $Group,
        [String] $Enabled,
        [string] $Action,
        [String[]] $Profile,
        [String] $Direction,
        [String[]] $RemotePort,
        [String[]] $LocalPort,
        [String] $Protocol,
        [String] $Description,
        [String] $ApplicationPath,
        [String] $Service
    )
```

Changed to:
```powershell
function Test-RuleProperties
{
    param (
        [Parameter(Mandatory)]
        $FirewallRule,
        [String] $Name,
        [String] $DisplayName = $Name,
        [String] $DisplayGroup = 'DSC_FirewallRule',
        [String] $Group,
        [String] $Enabled,
        [string] $Action  = 'Allow',
        [String[]] $Profile = 'Any',
        [String] $Direction,
        [String[]] $RemotePort,
        [String[]] $LocalPort,
        [String] $Protocol,
        [String] $Description,
        [String] $ApplicationPath,
        [String] $Service
    )
```

That way these default values are still set, but only on New rules - not when modifying existing ones. This would resolve the issue with enabling built in rules I think without breaking any existing functionality.

I could also add localization code (like in xIPaddress, xDNSServerAddress, xDefaultGatewayAddress) at the same time.

**Comment by tysonjhayes** [comment]
Seems like a good idea to me, the user story seems like a good use case. I think this makes sense to work on.

**Comment by PlagueHO** [comment]
I've been working on this issue and after reviewing the code some more I've realized that all the foreach() loops that update or check multiple rules are actually redundant. The reason is that the  Get-FirewallRule function always fires the Get-NetFirewallRule cmdlet passing a Name parameter, which can only ever return 0 or 1 rules - it can't return more than one because this field must be unique. The DisplayName field doesn't have to be unique, but this isn't the field we're indexing on.

So, is there any reason I can't get rid of these loops?

**Comment by tysonjhayes** [comment]
I believe I remembered thinking that when I was last doing a refactor pass on it. So I can't think of a reason not to get rid of it, try writing some unit tests to prove your logic so we can prove it still works after the change.

**Comment by PlagueHO** [comment]
Very good point - I'll add a check in to Get-FirewallRule to throw an exception if any more than one rule is returned - I'll make it a terminating exception because well, it indicates something is very wrong somewhere. Can then test for it in the unit tests.

Also, if the assumption that Name is unique and should never return more than one result, there isn't actually any point in looking for a record with a matching DisplayGroup in Get-FirewallRule.

In fact it would actually cause an error to be thrown if a resource was configured that just tried to change the DisplayGroup property for a rule to a new value - it would result in the a Rule with the same name property being added when it already exists, which throws an exception (I tested this). So I think I should remove that code too as I don't think it could work. I could be wrong here of course so please feel free to point out my "bad thinking". :)
