### ISSUE TITLE
xNetConnectionProfile always returns falls when not passing all parameters. 

### ISSUE THREAD

**Issue by dcrreynolds** [PowerShell/xNetworking#254]
Test-TargetResource returns false when parameters IPv4Connectivity, IPv6Connectivity, or NetworkCategory are not provided. These option parameters are treated and evaluated as if they could not be null.

I think we should check for NullOrWhitespace before returning false. A validation check that at least one of the 3 parameters was used may be a nice add as well.

**Comment by PlagueHO** [comment]
Cool - thanks @dcrreynolds - I'll see if I can get to this one today. Cheers for submitting!
