### ISSUE TITLE
[New Resource]: xWeakHostReceive and xWeakHostSend 

### ISSUE THREAD

**Issue by Warryz** [PowerShell/xNetworking#266]
Hello everyone,

I'm currently working on implementing DSC in our infrastructure for the deployment of new servers. A lot of features is already available but the xNetworking module is lacking of the ability to enable or disable the WeakHostSend and WeakHostReceive model. 

I'm planning to develop these resources, because there are powershell cmdlets but no dsc resources available yet.

Further information can be found at
https://technet.microsoft.com/en-us/library/2007.09.cableguy.aspx
https://technet.microsoft.com/en-us/itpro/powershell/windows/nettcpip/set-netipinterface#-weakhostreceive

**Comment by PlagueHO** [comment]
Hi @Warryz - we'd be delighted to accept any new modules! So if you're keen on adding them then go for it!

It is definitely worth looking over the [Contributing guidelines](https://github.com/PowerShell/DscResources/blob/master/CONTRIBUTING.md) and the [Style guidelines](https://github.com/PowerShell/DscResources/blob/master/StyleGuidelines.md). We're also moving this module over to HQRM, which means that we are also implementing the [HQRM guidelines](https://github.com/PowerShell/DscResources/blob/master/HighQualityModuleGuidelines.md).
