### ISSUE TITLE
xHostsFile: The PowerShell DSC resource MSFT_xHostsFile from module <xNetworking,5.0.0.0> does not exist at the PowerShell module path nor is it registered as a WMI DSC resource

### ISSUE THREAD

**Issue by shurick81** [PowerShell/xNetworking#267]
**Details of the scenario you tried and the problem that is occurring:**
I'm trying to apply this resource:

```
            xHostsFile WAHostEntry
            {
                HostName  =  $webAppHostName
                IPAddress = "127.0.0.1"
                Ensure    = "Present"
            }
```

It is successfully compiled on my dev machine into this:

```
instance of MSFT_xHostsFile as $MSFT_xHostsFile1ref
{
ResourceID = "[xHostsFile]WAHostEntry";
 Ensure = "Present";
 HostName = "SPWA_01.sp.local";
 SourceInfo = "D:\\Alex\\GitHub\\SPConfiStructurer\\SharePointOnPrem\\DSC\\SPFarm.ps1::75::13::xHostsFile";
 ModuleName = "xNetworking";
 IPAddress = "127.0.0.1";
 ModuleVersion = "5.0.0.0";

 ConfigurationName = "SPFarm";

};
```

However, when I start the configuration on the target machine in Azure, I get the error:

```
PS C:\Users\dauser1> Start-DscConfiguration "C:\DSC\SPFarm - Copy" -Wait -Force -Verbose
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' =
SendConfigurationApply,'className' = MSFT_DSCLocalConfigurationManager,'namespaceName' =
root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer SP2016Ent01sp01 with user sid
S-1-5-21-1446973221-797931035-2561853747-500.
VERBOSE: [SP2016Ent01sp01]: LCM:  [ Start  Set      ]
VERBOSE: [SP2016Ent01sp01]: LCM:  [ End    Set      ]
The PowerShell DSC resource MSFT_xHostsFile from module <xNetworking,5.0.0.0> does not exist at the PowerShell module
path nor is it registered as a WMI DSC resource.
    + CategoryInfo          : InvalidOperation: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : DscResourceNotFound
    + PSComputerName        : SP2016Ent01sp01

VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 0.441 seconds
```

The resource looks available:
```
PS C:\Users\dauser1> Get-DscResource -Module xNetworking -Name xHostsFile | Format-List


ResourceType  : MSFT_xHostsFile
Name          : xHostsFile
FriendlyName  : xHostsFile
Module        : xNetworking
ModuleName    : xNetworking
Version       : 5.1.0.0
Path          : C:\Program
                Files\WindowsPowerShell\Modules\xNetworking\DSCResources\MSFT_xHostsFile\MSFT_xHostsFile.psm1
ParentPath    : C:\Program Files\WindowsPowerShell\Modules\xNetworking\DSCResources\MSFT_xHostsFile
ImplementedAs : PowerShell
CompanyName   : Microsoft Corporation
Properties    : {HostName, DependsOn, Ensure, IPAddress...}
```

**The DSC configuration that is using the resource (as detailed as possible):**
How I create the configuration:
1. Create Azure Standard_D11_v2 machine.
2. Install some other extensions via Set-AzureRmVmDscExtension
3. Take an image of the machine
4. Create another machine via image
5. Running mof file

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2016
```
PS C:\Users\dauser1> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  1613

```
**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
When I check with Get-DscResource, it shows version 5.1.0.0 if that was the question

**Comment by shurick81** [comment]
I also checked more straight forward scenario:
1. Creating new Standard_D11_v2 machine
2. Runing `Install-Module -Name xNetworking -Force`
3. Starting mof

getting the same error.

**Comment by atdhe18** [comment]
Hi shurick81, 
maybe on the Configuration File when you import xNetworking you have set the "ModuleVersion" switch to use  5.0.0.0 .
Best Regards 
Atdhe

**Comment by atdhe18** [comment]
instance of MSFT_xHostsFile as $MSFT_xHostsFile1ref
{
ResourceID = "[xHostsFile]WAHostEntry";
 Ensure = "Present";
 HostName = "SPWA_01.sp.local";
 SourceInfo = "D:\\Alex\\GitHub\\SPConfiStructurer\\SharePointOnPrem\\DSC\\SPFarm.ps1::75::13::xHostsFile";
 ModuleName = "xNetworking";
 IPAddress = "127.0.0.1";
 **ModuleVersion = "5.0.0.0";**

 ConfigurationName = "SPFarm";

};

**Comment by shurick81** [comment]
Hello and thank you for your reply.

I can see now that on my dev machine that I use for compilation, the version of the module is 5.0.0.0.

```
PS C:\WINDOWS\system32> Get-DscResource -Module xNetworking -Name xHostsFile | Format-List


ResourceType  : MSFT_xHostsFile
Name          : xHostsFile
FriendlyName  : xHostsFile
Module        : xNetworking
ModuleName    : xNetworking
Version       : 5.0.0.0
Path          : C:\Program Files\WindowsPowerShell\Modules\xNetworking\5.0.0.0\DSCResources\MSFT_xHostsFile\MSFT_xHostsFile.psm1
ParentPath    : C:\Program Files\WindowsPowerShell\Modules\xNetworking\5.0.0.0\DSCResources\MSFT_xHostsFile
ImplementedAs : PowerShell
CompanyName   : Microsoft Corporation
Properties    : {HostName, DependsOn, Ensure, IPAddress...}
```

Probably I should keep my compiling machine always up to date then?

**Comment by atdhe18** [comment]
Yes i would try to update the xNetworking Module and then look if it works.

I think that's the reason why it's not working because, it's searching for the Module xNetworking Version 5.0.0.0 .


Am 13.09.2017 um 15:49 schrieb Alex SaPozhkov <notifications@github.com<mailto:notifications@github.com>>:


Hello and thank you for your reply.

I can see now that on my dev machine that I use for compilation, the version of the module is 5.0.0.0.

PS C:\WINDOWS\system32> Get-DscResource -Module xNetworking -Name xHostsFile | Format-List


ResourceType  : MSFT_xHostsFile
Name          : xHostsFile
FriendlyName  : xHostsFile
Module        : xNetworking
ModuleName    : xNetworking
Version       : 5.0.0.0
Path          : C:\Program Files\WindowsPowerShell\Modules\xNetworking\5.0.0.0\DSCResources\MSFT_xHostsFile\MSFT_xHostsFile.psm1
ParentPath    : C:\Program Files\WindowsPowerShell\Modules\xNetworking\5.0.0.0\DSCResources\MSFT_xHostsFile
ImplementedAs : PowerShell
CompanyName   : Microsoft Corporation
Properties    : {HostName, DependsOn, Ensure, IPAddress...}


Probably I should keep my compiling machine always up to date then?

**Comment by shurick81** [comment]
Yes that worked, thank you
