### ISSUE TITLE
I would like to assign Static Gateway and Static DNS Server addresses using DSC. I tried to use xNetworking module with xIPAddress but it can't find these properties.

### ISSUE THREAD

**Issue by rsganta** [PowerShell/xNetworking#274]
**Details of the scenario you tried and the problem that is occurring:**

**The DSC configuration that is using the resource (as detailed as possible):**

**Version of the Operating System and PowerShell the DSC Target Node is running:**

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**

**Comment by rsganta** [comment]
Code Snippet:
xIPAddress MgmtAddress  
        { 
            IPAddress        = $Node.IPAddress #
            AddressFamily    = $Node.AddressFamily #"IPV4" 
            InterfaceAlias   = $Node.InterfaceAlias #"EtherNet"
            #DefaultGateway = $Node.DefaultGateway 
            #DNSServerAddress =
 

        }

**Comment by PlagueHO** [comment]
Hi @rsganta ,

The parameters you need are actually contained in different resources.

To set the Default Gateway you'll need to add in instance of the `xDefaultGatewayAddress` resource ([see here for examples](https://github.com/PowerShell/xNetworking/wiki/xDefaultGatewayAddress) - note, I just noted a bug with Example 2 - The AddressFamily should be IPv4).

To set the DNS Server address you'll want to use the `xDNSServerAddress` resource ([see here for examples](https://github.com/PowerShell/xNetworking/wiki/xDNSServerAddress) ).

You'll therefore end up with a config like this:
```powershell
xIPAddress MgmtAddress
{
  IPAddress = $Node.IPAddress
  AddressFamily = $Node.AddressFamily
  InterfaceAlias = $Node.InterfaceAlias
}
xDefaultGatewayAddress
{
  Address = $Node.DefaultGateway
  InterfaceAlias = $Node.InterfaceAlias
  AddressFamily = $Node.IPv4
}
xDnsServerAddress DnsServerAddress
{
  Address = $Node.DNSServerAddress
  InterfaceAlias = $Node.InterfaceAlias
  AddressFamily = $Node.IPv4
  Validate = $true
}
```

Does that make sense?

**Comment by rsganta** [comment]
Thank you. I have already used the above example and I hit an error
VERBOSE: [ComputernameABC]:                            [[xDNSServerAddress]DnsServerAd
dress] Get-DnsClientServerStaticAddress: Statically assigned DNS server IPv4 address f
or interface alias 'EtherNet' is not set.
VERBOSE: [ComputernameABC]:                            [[xDNSServerAddress]DnsServerAd
dress] Test-TargetResource: DNS server addresses are not correct. Expected "10.222.120
.24", actual "".

**Comment by rsganta** [comment]
Any help would be greatly appreciated .

**Comment by PlagueHO** [comment]
Hi @rsganta - is there any other logs appearing apart from those? Because none of those messages are actually an error - they are exactly what I'd expect to see. Although I'd expect one more message afterwards saying something like:
`VERBOSE: [ComputernameABC]: [[xDNSServerAddress]DnsServerAd
dress] Set-TargetResource: Applying the Default Gateway Address.`

Can you confirm if there were any other messages or specify which part you're referring to as the error?
Thank you!

**Comment by rsganta** [comment]
Here is the error message
Job {2DC5999A-BA79-11E7-B371-00155D207E27} : 
This event indicates that failure happens when LCM is processing the configuration. Error Id is 0x1. Error Detail is The SendConfigurationApply function did not succeed.. Resource Id is [xDNSServerAddress]DnsServerAddress and Source Info is ::49::9::xDnsServerAddress. Error Message is PowerShell DSC resource MSFT_xDNSServerAddress  failed to execute Set-TargetResource functionality with error message: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: A general error occurred that is not covered by a more specific error code. .

Job {2DC5999A-BA79-11E7-B371-00155D207E27} : 
MIResult: 1
Error Message: PowerShell DSC resource MSFT_xDNSServerAddress  failed to execute Set-TargetResource functionality with error message: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: A general error occurred that is not covered by a more specific error code. 
Message ID: ProviderOperationExecutionFailure
Error Category: 7
Error Code: 1
Error Type: MI


ERBOSE: [WIN-MT5H3UUNLSC]:                            [[xDNSServerAddress]DnsServerAddress] Get-DnsClientServerStatic
Address: Getting staticly assigned DNS server IPv4 address for interface alias 'EtherNet'.
VERBOSE: [WIN-MT5H3UUNLSC]:                            [[xDNSServerAddress]DnsServerAddress] Get-DnsClientServerStatic
Address: Statically assigned DNS server IPv4 address for interface alias 'EtherNet' is not set.
VERBOSE: [WIN-MT5H3UUNLSC]: LCM:  [ End    Set      ]  [[xDNSServerAddress]DnsServerAddress]  in 18.8320 seconds.
PowerShell DSC resource MSFT_xDNSServerAddress  failed to execute Set-TargetResource functionality with error 
message: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is 
set to Stop: A general error occurred that is not covered by a more specific error code. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
 
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost

**Comment by rsganta** [comment]
Full log stack from the node 
PS C:\Users\Administrator> update-dscconfiguration -verbose -wait -force
Update-DscConfiguration : A parameter cannot be found that matches parameter name 
'force'.
At line:1 char:40
+ update-dscconfiguration -verbose -wait -force
+                                        ~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Update-DscConfiguration], Parame 
   terBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.DesiredSta 
   teConfiguration.Commands.UpdateDscConfigurationCommand
 

PS C:\Users\Administrator> update-dscconfiguration -verbose -wait -force
Update-DscConfiguration : A parameter cannot be found that matches parameter name 
'force'.
At line:1 char:40
+ update-dscconfiguration -verbose -wait -force
+                                        ~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Update-DscConfiguration], Parame 
   terBindingException
    + FullyQualifiedErrorId : NamedParameterNotFound,Microsoft.PowerShell.DesiredSta 
   teConfiguration.Commands.UpdateDscConfigurationCommand
 

PS C:\Users\Administrator> update-dscconfiguration -verbose -wait
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName'
 = PerformRequiredConfigurationChecks,'className' = MSFT_DSCLocalConfigurationManager,
'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer WIN-M9C3L3CR730 with user sid S-1-5-
21-3045334842-3259267579-683374414-500.
Cannot invoke the Consistency Check or Pull cmdlet. The Consistency Check or Pull 
cmdlet is in progress and must return before Consistency Check or Pull can be 
invoked. Use -Force option if that is available to cancel the current operation.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:Strin 
   g) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 0.47 seconds

PS C:\Users\Administrator> update-dscconfiguration -verbose -wait
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName'
 = PerformRequiredConfigurationChecks,'className' = MSFT_DSCLocalConfigurationManager,
'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer WIN-M9C3L3CR730 with user sid S-1-5-
21-3045334842-3259267579-683374414-500.
VERBOSE: [WIN-M9C3L3CR730]:                            [] Executing Get-Action with co
nfiguration (null)'s checksum: 57994622C88813278AB3936010B5AC13EBBB39A7E2CF2BF3F184F07
5243FCC89.
VERBOSE: [WIN-M9C3L3CR730]:                            [] Executing Get-Action with co
nfiguration (null)'s checksum failed. Please check the availability of pull server.
Failed to get the action from server https://wcus-agentservice-prod-1.azure-automatio
n.net/accounts/f35e85fc-7e07-45d6-9612-909d75d688bd/Nodes(AgentId='021E6B3D-BAD1-11E7
-B36E-00155D207E29')/GetDscAction.
    + CategoryInfo          : InvalidResult: (root/Microsoft/...gurationManager:Stri 
   ng) [], CimException
    + FullyQualifiedErrorId : WebDownloadManagerGetActionFailed,Microsoft.PowerShell 
   .DesiredStateConfiguration.Commands.GetDscActionCommand
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 26.891 seconds

PS C:\Users\Administrator> update-dscconfiguration -verbose -wait
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName'
 = PerformRequiredConfigurationChecks,'className' = MSFT_DSCLocalConfigurationManager,
'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer WIN-M9C3L3CR730 with user sid S-1-5-
21-3045334842-3259267579-683374414-500.
Cannot invoke the Consistency Check or Pull cmdlet. The Consistency Check or Pull 
cmdlet is in progress and must return before Consistency Check or Pull can be 
invoked. Use -Force option if that is available to cancel the current operation.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:Strin 
   g) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 0.091 seconds

PS C:\Users\Administrator> update-dscconfiguration -verbose -wait
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName'
 = PerformRequiredConfigurationChecks,'className' = MSFT_DSCLocalConfigurationManager,
'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer WIN-M9C3L3CR730 with user sid S-1-5-
21-3045334842-3259267579-683374414-500.
VERBOSE: [WIN-M9C3L3CR730]:                            [] Executing Get-Action with co
nfiguration (null)'s checksum: 57994622C88813278AB3936010B5AC13EBBB39A7E2CF2BF3F184F07
5243FCC89.
VERBOSE: [WIN-M9C3L3CR730]:                            [] Executing Get-Action with co
nfiguration 's checksum returned result status: GetConfiguration.
VERBOSE: [WIN-M9C3L3CR730]:                            [] Checksum is different. LCM w
ill execute GetConfiguration to pull configuration .
VERBOSE: [WIN-M9C3L3CR730]:                            [] Executing GetConfiguration s
ucceeded. Configuration  was pulled from server.
VERBOSE: [WIN-M9C3L3CR730]:                            [] Applying the new configurati
on(s) pulled.
VERBOSE: [WIN-M9C3L3CR730]: LCM:  [ Start  Resource ]  [[xDSCDomainjoin]JoinDomain]
VERBOSE: [WIN-M9C3L3CR730]: LCM:  [ Start  Test     ]  [[xDSCDomainjoin]JoinDomain]
VERBOSE: [WIN-M9C3L3CR730]: LCM:  [ End    Test     ]  [[xDSCDomainjoin]JoinDomain]  i
n 0.5580 seconds.
VERBOSE: [WIN-M9C3L3CR730]: LCM:  [ Skip   Set      ]  [[xDSCDomainjoin]JoinDomain]
VERBOSE: [WIN-M9C3L3CR730]: LCM:  [ End    Resource ]  [[xDSCDomainjoin]JoinDomain]
VERBOSE: [WIN-M9C3L3CR730]: LCM:  [ Start  Resource ]  [[xIPAddress]MgmtAddress]
VERBOSE: [WIN-M9C3L3CR730]: LCM:  [ Start  Test     ]  [[xIPAddress]MgmtAddress]
VERBOSE: [WIN-M9C3L3CR730]:                            [[xIPAddress]MgmtAddress] Test-
TargetResource: Checking the IP Address.
VERBOSE: [WIN-M9C3L3CR730]:                            [[xIPAddress]MgmtAddress] Test-
TargetResource: IP Address does NOT match desired state. Expected @{IPAddress=10.245.1
51.73; prefixLength=24}, actual 10.121.33.103.
VERBOSE: [WIN-M9C3L3CR730]: LCM:  [ End    Test     ]  [[xIPAddress]MgmtAddress]  in 7
.1900 seconds.
VERBOSE: [WIN-M9C3L3CR730]: LCM:  [ Start  Set      ]  [[xIPAddress]MgmtAddress]
VERBOSE: [WIN-M9C3L3CR730]:                            [[xIPAddress]MgmtAddress] Set-T
argetResource: Applying the IP Address.
VERBOSE: [WIN-M9C3L3CR730]:                            [[xIPAddress]MgmtAddress] Set-T
argetResource: IP Interface was set to the desired state.
VERBOSE: [WIN-M9C3L3CR730]: LCM:  [ End    Set      ]  [[xIPAddress]MgmtAddress]  in 1
.4210 seconds.
VERBOSE: [WIN-M9C3L3CR730]: LCM:  [ End    Resource ]  [[xIPAddress]MgmtAddress]
VERBOSE: [WIN-M9C3L3CR730]: LCM:  [ Start  Resource ]  [[xDefaultGatewayAddress]SetDef
aultGateway]
VERBOSE: [WIN-M9C3L3CR730]: LCM:  [ Start  Test     ]  [[xDefaultGatewayAddress]SetDef
aultGateway]
VERBOSE: [WIN-M9C3L3CR730]:                            [[xDefaultGatewayAddress]SetDef
aultGateway] Test-TargetResource: Checking the Default Gateway Address.
VERBOSE: [WIN-M9C3L3CR730]:                            [[xDefaultGatewayAddress]SetDef
aultGateway] Test-TargetResource: Default gateway does not exist. Expected "10.245.151
.1".
VERBOSE: [WIN-M9C3L3CR730]: LCM:  [ End    Test     ]  [[xDefaultGatewayAddress]SetDef
aultGateway]  in 0.5780 seconds.
VERBOSE: [WIN-M9C3L3CR730]: LCM:  [ Start  Set      ]  [[xDefaultGatewayAddress]SetDef
aultGateway]
VERBOSE: [WIN-M9C3L3CR730]:                            [[xDefaultGatewayAddress]SetDef
aultGateway] Set-TargetResource: Applying the Default Gateway Address.
VERBOSE: [WIN-M9C3L3CR730]:                            [[xDefaultGatewayAddress]SetDef
aultGateway] Set-TargetResource: Default Gateway address was set to the desired state.
VERBOSE: [WIN-M9C3L3CR730]: LCM:  [ End    Set      ]  [[xDefaultGatewayAddress]SetDef
aultGateway]  in 0.1880 seconds.
VERBOSE: [WIN-M9C3L3CR730]: LCM:  [ End    Resource ]  [[xDefaultGatewayAddress]SetDef
aultGateway]
VERBOSE: [WIN-M9C3L3CR730]: LCM:  [ Start  Resource ]  [[xDNSServerAddress]DnsServerAd
dress]
VERBOSE: [WIN-M9C3L3CR730]: LCM:  [ Start  Test     ]  [[xDNSServerAddress]DnsServerAd
dress]
VERBOSE: [WIN-M9C3L3CR730]:                            [[xDNSServerAddress]DnsServerAd
dress] Test-TargetResource: Checking the DNS server addresses.
VERBOSE: [WIN-M9C3L3CR730]:                            [[xDNSServerAddress]DnsServerAd
dress] Get-DnsClientServerStaticAddress: Getting staticly assigned DNS server IPv4 add
ress for interface alias 'EtherNet'.
VERBOSE: [WIN-M9C3L3CR730]:                            [[xDNSServerAddress]DnsServerAd
dress] Get-DnsClientServerStaticAddress: Statically assigned DNS server IPv4 address f
or interface alias 'EtherNet' is not set.
VERBOSE: [WIN-M9C3L3CR730]:                            [[xDNSServerAddress]DnsServerAd
dress] Test-TargetResource: DNS server addresses are not correct. Expected "10.222.120
.24,10.221.226.12", actual "".
VERBOSE: [WIN-M9C3L3CR730]: LCM:  [ End    Test     ]  [[xDNSServerAddress]DnsServerAd
dress]  in 0.3130 seconds.
VERBOSE: [WIN-M9C3L3CR730]: LCM:  [ Start  Set      ]  [[xDNSServerAddress]DnsServerAd
dress]
VERBOSE: [WIN-M9C3L3CR730]:                            [[xDNSServerAddress]DnsServerAd
dress] Set-TargetResource: Applying the DNS server addresses.
VERBOSE: [WIN-M9C3L3CR730]:                            [[xDNSServerAddress]DnsServerAd
dress] Get-DnsClientServerStaticAddress: Getting staticly assigned DNS server IPv4 add
ress for interface alias 'EtherNet'.
VERBOSE: [WIN-M9C3L3CR730]:                            [[xDNSServerAddress]DnsServerAd
dress] Get-DnsClientServerStaticAddress: Statically assigned DNS server IPv4 address f
or interface alias 'EtherNet' is not set.
VERBOSE: [WIN-M9C3L3CR730]: LCM:  [ End    Set      ]  [[xDNSServerAddress]DnsServerAd
dress]  in 2.6540 seconds.
PowerShell DSC resource MSFT_xDNSServerAddress  failed to execute Set-TargetResource 
functionality with error message: The running command stopped because the preference 
variable "ErrorActionPreference" or common parameter is set to Stop: A general error 
occurred that is not covered by a more specific error code. 
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : ProviderOperationExecutionFailure
    + PSComputerName        : localhost
 
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:Strin 
   g) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 21.112 seconds

PS C:\Users\Administrator>

**Comment by PlagueHO** [comment]
Hi @rsganta - can you paste a copy of the config you're using?

Also, can you check that the DNS Server Addresses you are passing in are an array of addresses rather than a string? E.g. it should be:
```powershell
xDnsServerAddress DnsServerAddress
{
  Address = '10.222.120.24'   ,   '10.221.226.12'
  InterfaceAlias = 'Ethernet'
  AddressFamily = 'IPv4'
  Validate = $true
}
```
Not:
xDnsServerAddress DnsServerAddress
{
  Address = '10.222.120.24,10.221.226.12'
  InterfaceAlias = 'Ethernet'
  AddressFamily = 'IPv4'
  Validate = $true
}
```

Can you confirm that the `Address` parameter is an array, rather than a single string?

**Comment by rsganta** [comment]
Here is my config data
$ConfigData = @{ 
                 AllNodes = @(  
                              @{     
                                 NodeName = "*"                           
                                 PSDscAllowPlainTextPassword = $False
                                 Domain = "OfficeDog.SelfHost.corp.microsoft.com"                                 
                                 #OU = "OU=Host,OU=Sharepoint 2019,OU=SharePoint_PG_Hosted,OU=Labs,DC=Officedog,DC=selfhost,DC=corp,DC=microsoft,DC=com"

                                 #Domain = "Redmond.corp.microsoft.com"
                                 #Domain = (Get-AutomationVariable -Name "TargetDomain")

                                 AddressFamily    = 'IPv4'
                                 InterfaceAlias   = 'EtherNet'
                                 DefaultGateway = '10.245.151.1'
                                 DNSIPAddress =  @('10.222.120.24','10.221.226.12')
                                 AdministratorsGroup = 'Redmond\997-DSG-SP2019FarmAdmins'
                                                                   
                              }    
                              


                               @{     
                                 NodeName = "WIN-OG8THID5P4B"#"OPOffice6"
                                 #Role = "App"
                                 IPAddress = "10.245.151.71/24"                                 
                                                                 
                               } 

                               @{     
                                 NodeName = "WIN-MT5H3UUNLSC"#"OPOffice6"
                                 #Role = "App"
                                 IPAddress = '10.245.151.72/24'                                  
                                                                 
                               }
                               @{     
                                 NodeName = "WIN-M9C3L3CR730"#"OPOffice6"
                                 #Role = "App"
                                 IPAddress = '10.245.151.73/24'                                  
                                                                 
                               }  
                             
                            )  
              }

**Comment by rsganta** [comment]
here is my configuration
#Step 1
#region Accounts Configuration

configuration DomainJoin
{ 
    param 
    ( 
        
    ) 
 
    #Import the required DSC Resources 
    Import-DscResource -Module xComputerManagement
    Import-DscResource -ModuleName xDSCDomainJoin
    Import-DscResource -ModuleName xNetWorking
    Import-DscResource -ModuleName xActiveDirectory
    Import-DscResource –ModuleName PSDesiredStateConfiguration   
     
    #$domjoincreds = [PSCredential](Get-AutomationPSCredential -Name 'SankargRedmond')
    $domjoincreds = [PSCredential](Get-AutomationPSCredential -Name 'SankargOfficeDog')

    #Node LocalHost
    Node $AllNodes.NodeName
    {         

        <#xComputer NewName 
        { 
            Name = $Node.NodeName
        } #>
    
        #xDNSServerAddress DNS
        xIPAddress MgmtAddress  
        { 
            IPAddress        = $Node.IPAddress #"10.245.151.71"  
            AddressFamily    = $Node.AddressFamily #"IPV4" 
            InterfaceAlias   = $Node.InterfaceAlias #"EtherNet"
            DependsOn     = "[xDSCDomainJoin]JoinDomain" # Only Corp Machines are able to ping officedog domain.

        }

        xDefaultGatewayAddress SetDefaultGateway
        {
            Address        = $Node.DefaultGateway
            InterfaceAlias = $Node.InterfaceAlias
            AddressFamily  = $Node.AddressFamily
            DependsOn     = "[xIPAddress]MgmtAddress"
        }      


        xDnsServerAddress DnsServerAddress
        {
            Address        = $Node.DNSIPAddress #"10.221.226.12"#@('127.0.0.1') #,'10.221.226.12' #$Node.DNSServerAddress
            InterfaceAlias = $Node.InterfaceAlias
            AddressFamily  = $Node.AddressFamily
            Validate       = $true
            DependsOn     = "[xDefaultGatewayAddress]SetDefaultGateway"
        }

        xDSCDomainJoin JoinDomain 
        { 
            Domain    = $Node.Domain 
            Credential    = $domjoincreds
            #DependsOn     = "[xIPAddress]MgmtAddress"
        }      

        #add the account to the Administrators group
        <#Group Administrators {
            GroupName="Administrators" 
            MembersToInclude="Redmond\Sankarg" #$Node.AdministratorsGroup #Redmond\Sankarg
            DependsOn="[xDSCDomainJoin]JoinDomain" 
        }#>

        
        
    } 
}

**Comment by PlagueHO** [comment]
Hi There, @rsganta - your configs look fine to me. However, do the DNS Servers on '10.222.120.24' and '10.221.226.12' exist? And are they contactable?

If not you'll want to change the `Validate` parameter to $false.
E.g.
```powershell
 xDnsServerAddress DnsServerAddress
    {
        Address        = $Node.DNSIPAddress #"10.221.226.12"#@('127.0.0.1') #,'10.221.226.12' #$Node.DNSServerAddress
        InterfaceAlias = $Node.InterfaceAlias
        AddressFamily  = $Node.AddressFamily
        Validate       = $false
        DependsOn     = "[xDefaultGatewayAddress]SetDefaultGateway"
    }
```

If the `validate` parameter is set to $true and either of the DNS Servers can't be contacted then an error usually occurs (unfortunately the cmdlet doesn't provide a clear error message when this occurs).

**Comment by rsganta** [comment]
Let me try with $false option.

**Comment by PlagueHO** [comment]
Sure! Let me know the outcome and I'll take a look tomorrow (it's late here now so I'm off to sleep). Will check tomorrow. Thank you!

**Comment by rsganta** [comment]
Oh great . it worked with $false option. I am able to see DNSServers were assigned. However I am unable to ping other machines in this domain. I will give sometime  for this machine and try it again.  Thank you so much for your time.

**Comment by PlagueHO** [comment]
This could be a firewall issue, or a problem with your default gateway config if you are pinging outside the subnet. I am assuming you are pinging the IP address, not a hostname (as your DNS Servers might not up yet based on previous messages). Happy to assist further if I can.

I'll close this for now, but feel free to reopen if there is any other assistance needed.

**Comment by rsganta** [comment]
Yes, I am pinging IP Addresses . I am still trying to understand why I am unable to ping IPAddresses. As you said, could be firewall issue. I have another question but open in a different thread. Thanks much for your time.
