### ISSUE TITLE
Jumbo Frames

### ISSUE THREAD

**Issue by BarnumD** [PowerShell/xNetworking#286]
Can we configure jumbo frames with one of these modules?  If not, can it be added?

**Comment by PlagueHO** [comment]
Hi @BarnumD - this is not currently supported by any of the DSC Resources in xNetworking, but I don't see why this could not be added.

It could be done by creating a resource for setting Advanced Net Adapter properties - as this would allow other properties to also be set.

If no one gets to this one I'll put it on the backlog - but I've got a lot on there already! But hopefully someone else already has a resource available that they could contribute to the resource kit covering this.

**Comment by atdhe18** [comment]
Is it okay if i do it? 
Because i need it too!

**Comment by johlju** [comment]
@ardhe18 you are more than welcome to send in a PR for this! Much appreciated!

**Comment by johlju** [comment]
@atdhe18 I misspelled the name, please see previous comment :smile:
