### ISSUE TITLE
Should xIPAddress force the network connection profile to Private?

### ISSUE THREAD

**Issue by Dan1el42** [PowerShell/xNetworking#3]
The xIPAddress resource is currently forcing the network connection profile of the interface being configured to Private in the internal ValidateProperties function.

```
# Make the connection profile private
Get-NetConnectionProfile -InterfaceAlias $InterfaceAlias | Set-NetConnectionProfile -NetworkCategory Private -ErrorAction SilentlyContinue
```

Invoking Set-NetConnectionProfile for domain joined machines throws an exception which is being suppressed by the ErrorAction parameter. The resource does not test for the network connection profile. Changes to the network connection profile are not being detected by the resource. I think a clear violation of DSC design best practices.

I would like to remove above two lines to allow for the scenario of an external facing server (public IP) without workarounds.

What are your thoughts?

P.S.: I have started to code a simple DSC resource to set the network connection profile if required as part of a larger configuration script.

Thanks
Daniel

**Comment by tysonjhayes** [comment]
Sorry to just be getting to this but I think the answer is no, that being said I'm not sure xIPAddress should be setting this at all, I'm going to be opening a discussion on this next week with my thoughts of where this resource should go.

**Comment by tysonjhayes** [comment]
So this has been removed (though I forget when we merged it) so this no longer occurs.
