### ISSUE TITLE
Need more properties in xNetAdapterAdvancedProperty

### ISSUE THREAD

**Issue by BarnumD** [PowerShell/xNetworking#314]
I'm trying to set a number of NIC advanced properties that don't seem to be accepted by the code in MSFT_xNetAdapterAdvancedProperty.psm1.   I would imagine that this list is completely dependent on the network card manufacturer and which features it supports.  Is there a way to set arbitrary advanced properties that are not listed in this file or should I submit a merge request to add mine?

Here are the list i'm trying to add:
```
*DcbxMode: '2'
*EncapsulatedPacketTaskOffload: '1'
*NetworkDirect: '1'
*NumRSSQueues: '30'
*PacketDirect: '1'
*QOS: '1'
*RecvCompletionMethod: 1'
*RoceMaxFrameSize: '0'
*RscIPv4: '1'
*RssOnHostVPorts: '1'
*RssProfile: '1'
*RxIntModeration: '2'
*RxIntModerationProfile: '1'
*Sriov: '0'
*TCPUDPChecksumOffloadIPv4: '3'
*TCPUDPChecksumOffloadIPv6: '3'
*TxIntModerationProfile: '1'
*VMQ: '1'
*VMQVlanFiltering: '1'
*VlanID: '0'
```

**Comment by PlagueHO** [comment]
Hi @BarnumD - thank you for submitting this.

It seems like this list of acceptable values is likely to change quite a lot depending on adapter manufacturer. So I wonder if it is worth removing the ValidateSet from the `RegistryKeyword` parameter entirely. Otherwise we're likely to be constantly trying to keep ahead of this list.

The downside is that we lose the config validation at design time.

@tysonjhayes - do you have any thoughts on this?

**Comment by BarnumD** [comment]
Sure.  I've prepared a commit and can submit a merge request if necessary, but I also think someone else is likely to show up here looking for their adapter's property to be supported.

**Comment by tysonjhayes** [comment]
Given this is the first time we've really had to change those values I think it would make sense to make a PR and keep the validation at design time. If we find in the long term that we are going back and tweaking this near constantly it would make sense to remove it, but for now I think I think there is value in keeping it.

**Comment by PlagueHO** [comment]
Cool! Thanks @tysonjhayes and @BarnumD

**Comment by BarnumD** [comment]
FYI, RssProfile, and NumRSSQueues were already in the module.  They weren't working for me based on case sensitivity.  So you won't see them in this merge request.

**Comment by AussieDavo** [comment]
Would it be possible to also include "MaxRxRing1Length" and "NumRxBuffersSmall" in the validate set?

**Comment by PlagueHO** [comment]
Hi @AussieDavo - Yep, I reckon that would be easy enough. Do you want to raise a new issue so that I can track this and get it done?

**Comment by AussieDavo** [comment]
Thanks @PlagueHO , I have opened a new issue for this: #387
