### ISSUE TITLE
xNetBIOS: InterfaceAlias not working properly

### ISSUE THREAD

**Issue by aalmeida89** [PowerShell/xNetworking#315]
I'm having a problem enabling netBIOS. My file is like it:
xNetBIOS EnableNetBIOS 
        {
            InterfaceAlias = 'ethernet0'
            Setting        = 'Enable'
        }
When I use InterfaceAlias as "Ethernet0" it returns the error: System.InvalidOperationException: Interface 'ethernet0' was not found.
To find InterfaceAlias, I am doing the PS query: 
Get-NetIPAddress | where IPAddress -eq "***.***.***.***" | fl interfaceAlias
and it returns:
interfaceAlias : Ethernet0 
I am using the correct name.
When I query "Get-NetAdapter | fl Name,InterfaceDescription" it returns:
Name                        : Ethernet0
InterfaceDescription : Intel(R) 82574L Gigabit Network Connection

Then Im trying 
xNetBIOS EnableNetBIOS 
        {
            InterfaceAlias = 'Intel(R) 82574L Gigabit Network Connection'
            Setting        = 'Enable'
        }
and it changes well. I think InterfaceAlias is not suppose to be it. Going further in my investigation I opened the file "MSFT_xNetBIOS.psm1" and go to "function Test-TargetResource" (line 190) to find what it is doing. At line 208 have it:
$netAdapter = Get-CimInstance `
        -ClassName Win32_NetworkAdapter `
        -Filter ('Name="{0}"' -f $InterfaceAlias)
then I query "Get-CimInstance -ClassName Win32_NetworkAdapter | select name" and none of them is "Ethernet0", so looking for "ethernet0" I found it at NetConnectionID:
NetConnectionID             : Ethernet0
query: Get-CimInstance -ClassName Win32_NetworkAdapter | select NetConnectionID

All my nodes are running Powershell 5.1 and i'm using xNetworking 5.5.0 (master branch I guess)
PS
Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14393  693
xNetworking
Version    Name         
-------    ----               
5.5.0.0    xNetworking

**Comment by PlagueHO** [comment]
Hi @aalmeida89 - it looks like a change was made in the last release that broke this. I'll get this fixed ASAP. It should still work fine in 5.4.0.0. Thanks for raising this.

**Comment by aalmeida89** [comment]
Thanks a lot =).

**Comment by matt6697** [comment]
Fix available in 5.7.0.0 (not 5.6.0.0 as stated in the changelog !)

**Comment by johlju** [comment]
You could fix the change log in this repo, but don't think we can (read have time) to resolve the release notes in PowerShell Gallery. I have no permission there.
You could add a note in next release's change log (under the Unreleased section) mentioning the mistake too?

**Comment by PlagueHO** [comment]
Thanks @johlju - I think you're right and going back and changing past packages is a no-no in general. So I'll just submit a PR to correct the CHANGELOG.MD.
