### ISSUE TITLE
xIPAddress: Incorrectly reports that DHCP is enabled for IPv6 addresses

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xNetworking#32]
The xIPAddress resource when used to set a static IPv6 address will misreport that the interface on the adapter is configured with DHCP when it is not. This causes Test-TargetResource to return $False, triggering the IP Address to be updated every time the config is applied.

The problem appears to be in the Get-NetIPInterface cmdlet at line 234 of MSFT_xIPAddress.psm1. I am referring to the current Dev version of this resource. This cmdlet always returns that DHCP is enabled even when it is not:

![pic](https://cloud.githubusercontent.com/assets/7589164/10557287/30bbbb90-7502-11e5-9e6d-b678c8d12f4b.png)

Note, the IPv4 address in the above screenshot is also statically assigned. Yet, the Get-NetIPInterface cmdlet returns that DHCP is enabled on the IPv6 interface but disabled on the IPv4.

Is this a problem in the cmdlet itself or does the cmdlet behave differently with IPv6? I know that IPv6 is a little more complex than IPv4 with things like Link-Local addresses and Site-Local/Unique-Local being assigned to the same interface, so perhaps this is a normal behavior?

The problem code is this:
```powershell
if (-not (Get-NetIPInterface `
        -InterfaceAlias $InterfaceAlias `
        -AddressFamily $AddressFamily).Dhcp.ToString().Equals('Disabled'))
```

To fix this, it needs to be changed to something that reliably detects the DHCP state of an IPv6 interface. Possibly the using the suffixOrigin or PrefixOrigin properties returned on objects from the Get-NetIPAddress cmdlet - if they equal 'manual' then DHCP is disabled. But this feels a bit risky to me. 

Any ideas?

**Comment by PlagueHO** [comment]
And another example (except in a Windows Server 2012 R2 Full install):
![pic2](https://cloud.githubusercontent.com/assets/7589164/10561792/a463317e-7596-11e5-9809-a996f3055262.png)

**Comment by PlagueHO** [comment]
After further review I think the problem can be resolved by manually setting the DHCP status on the IPv6 Interface in Set-TargetResource when the IP address is set. Alternately the check to ensure DHCP is set could be removed completely. This seems to make more sense when taking Issue #17 into account (moving DHCP into a separate resource).

My feeling is that the check for the DHCP setting should be removed completely.

**Comment by PlagueHO** [comment]
Would anyone have an objection to me submitting a PR that removes the offending DHCP check code from the xIPAddress resource? I'm not sure I see the purpose for it anyway. I could optionally put a check around it and only fire it for IPv4. Either way it is causing pain with IPv6.

It is causing a few problems with IPv6 because it causes the IPv6 address to be reconfigured every time DSC is applied because the resource currently incorrectly reports the DHCPv6 state. It is causing me a problem though because I often have Domain Join resources following it which often fail because the networking is still being reconfigured when this fires.

This isn't a problem with IPv4 so most people won't run into it.

**Comment by iainbrighton** [comment]
Excuse my ignorance but, is there no DHCP (or equivalent) in IPv6?

**Comment by PlagueHO** [comment]
There is, but it doesn't behave in the same fashion as DHCPv4. If DHCP is enabled on an IPv6 interface it can be in two modes - stateless autoconfig and stateful autoconfig. Stateful requires a DHCPv6 server to assign the IPv6 address, but stateless doesn't (it uses information from a detected router to configure it). You are usually assigned an automatic Link-Local IPv6 (stateless autoconfig) address to every adapter regardless if you've assigned a static IPv6 address. So on a single adapter DHCPv6 can be both enabled and disabled at the same time (which is why the DHCP status is meaningless when talking about IPv6).

Anyway, the problem is that on an IPv6 interface the DHCP status is not useful. If we check it in the resource it will report that DHCP is enabled when it isn't (or vice versa). Which causes the Set-TargetResource to fire every time the DSC is evaluated. So I've got a situation where I'm assigning static IPv6 addresses to my servers and the DHCP status is being returned as Enabled - so the resource continuously applies.

Hopefully my explanation of all this is clear-ish :smile:

**Comment by PlagueHO** [comment]
This has been resolved. Thanks @tysonjhayes
