### ISSUE TITLE
xNetAdapterAdvancedProperty: Conflict when configuring more than 1 NetAdapter

### ISSUE THREAD

**Issue by janegilring** [PowerShell/xNetworking#324]
**Details of the scenario you tried and the problem that is occurring:**

When a configuration contains the following:
                xNetAdapterAdvancedProperty JumboPacket9014SMB1
                {
                    NetworkAdapterName  = 'vEthernet (SMB_1)'
                    RegistryKeyword     = "*JumboPacket"
                    RegistryValue       = 9014
                    DependsOn = '[xVMNetworkAdapter]SMB1'
                }

                xNetAdapterAdvancedProperty JumboPacket9014SMB2
                {
                    NetworkAdapterName  = 'vEthernet (SMB_2)'
                    RegistryKeyword     = "*JumboPacket"
                    RegistryValue       = 9014
                    DependsOn = '[xVMNetworkAdapter]SMB2'
                }

Compile fails with the following error:
Test-ConflictingResources : A conflict was detected between resources '[xNetAdapterAdvancedProperty]JumboPacket9014SMB1(C:\NR\S2D_Configuration.ps1::166::17::xNetAdapterAdvancedProperty)' and 
'[xNetAdapterAdvancedProperty]JumboPacket9014SMB2 (C:\NR\S2D_Configuration.ps1::174::17::xNetAdapterAdvancedProperty)' in node 'Node1'. Resources have identical key properties but there are differences in the following non-key properties: 
'NetworkAdapterName'. Values 'vEthernet (SMB_1)' don't match values 'vEthernet (SMB_2)'. Please update these property values so that they are identical in both cases.
At line:289 char:9
+         Test-ConflictingResources $keywordName $canonicalizedValue $k ...

Shouldn't it be possible to configure a property such as JumboPackets on several NetAdapters?

**The DSC configuration that is using the resource (as detailed as possible):**

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows Server 2016 with PowerShell 5.1

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
xNetworking 5.6.0.0

**Comment by PlagueHO** [comment]
Hi @janegilring - I think you're quite right. This should be supported. I'll get this fixed right now.

**Comment by janegilring** [comment]
Excellent - I`ll go ahead and test as soon as the fix is available.

**Comment by janegilring** [comment]
FYI: I tested the update today, it worked without any issues. Thanks again.

**Comment by PlagueHO** [comment]
Thanks @janegilring !
