### ISSUE TITLE
xFirewall: public profile is not being disabled as expected

### ISSUE THREAD

**Issue by artisticcheese** [PowerShell/xNetworking#327]
**Details of the scenario you tried and the problem that is occurring:**
If I manually enable firewall for some reason xFirewall resource will not put it back to disabled state and DSC still reports it as compliant
```
ConfigurationName    : SwarmManager
DependsOn            :
ModuleName           : xNetworking
ModuleVersion        : 5.6.0.0
PsDscRunAsCredential :
ResourceId           : [xFirewallProfile]DisablePublic
SourceInfo           : ::33::9::xFirewallProfile
DurationInSeconds    : 0.049
Error                :
FinalState           :
InDesiredState       : True
InitialState         :
InstanceName         : DisablePublic
RebootRequested      : False
ResourceName         : xFirewallProfile
StartDate            : 4/20/2018 2:39:50 PM
PSComputerName       :
```
Firewall public profile is on
```
PS C:\Users\cloudadmin> netsh advfirewall show public

Public Profile Settings:
----------------------------------------------------------------------
State                                 ON
Firewall Policy                       BlockInbound,AllowOutbound
LocalFirewallRules                    N/A (GPO-store only)
LocalConSecRules                      N/A (GPO-store only)
InboundUserNotification               Disable
RemoteManagement                      Disable
UnicastResponseToMulticast            Enable

Logging:
LogAllowedConnections                 Disable
LogDroppedConnections                 Disable
FileName                              %systemroot%\system32\LogFiles\Firewall\pfirewall.log
MaxFileSize                           4096


```

**The DSC configuration that is using the resource (as detailed as possible):**

```
        xFirewallProfile DisablePrivate {
            Enabled = "False"
            Name   = "Private"
        }
```

**Version of the Operating System and PowerShell the DSC Target Node is running:**
Windows 2016

Name                           Value                                                                                   
----                           -----                                                                                   
PSVersion                      5.1.14393.2155                                                                          
PSEdition                      Desktop                                                                                 
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                 
BuildVersion                   10.0.14393.2155                                                                         
CLRVersion                     4.0.30319.42000                                                                         
WSManStackVersion              3.0                                                                                     
PSRemotingProtocolVersion      2.3                                                                                     
SerializationVersion           1.1.0.1                                                                                 

**Version of the DSC module you're using, or 'dev' if you're using current dev branch:**
5.6.0.0

**Comment by PlagueHO** [comment]
Hi @artisticcheese - thank you for logging this. Your DSC example seems to be disabling the Firewall for _Private_ Profiles where as the diagnostic information seems to indicate you're showing the _Public_ profile state. Is this a mistake?

If not then I'd say your config needs to be:
```powershell
        xFirewallProfile DisablePublic {
            Enabled = "False"
            Name   = "Public"
        }
```

Could you confirm?
