### ISSUE TITLE
Get-DscConfiguration Fails on Firewall Rule

### ISSUE THREAD

**Issue by PrahlM93** [PowerShell/xNetworking#41]
Hello,
Using xNetworking 2.4, I am having issues running Get-DscConfiguration.

My configuration block looks as follows:
```
xFirewall RdpFirewallRules {
    Name = 'RemoteDesktop-UserMode-In-TCP'
    Ensure = 'Present'
    Action = 'Allow'
    Enabled = 'True'
    Profile = ('Domain', 'Private', 'Public')
}
```

I get the following error in Event Viewer when running Get-DscConfiguration:
```
This event indicates that failure happens when LCM is processing the configuration. Error Id is 0xD. Error Detail is The SendConfigurationApply function did not succeed.. Resource Id is [xFirewall]RdpFirewallRules and Source Info is C:\Configuration\Firewall.ps1::118::17::xFirewall. Error Message is The PowerShell DSC resource  returned results that are not valid from Get-TargetResource. The Group key is not a valid property in the corresponding DSC resource schema file. The results from Get-TargetResource must be in a Hashtable format. The keys in the Hashtable must be the same as the properties in the corresponding DSC resource schema file..
```

It seems that the Group property isn't defined in the schema. I ended up adding it as a read-only property and it seems to work but the information isn't particularly useful as shown below:
```
Group                : @FirewallAPI.dll,-28752
```

It seems that the appropriate solution is to have "Group" not be returned in the Get-TargetResource function. This is implemented in #42 

Thank you for your help.

**Comment by tysonjhayes** [comment]
Howdy - I have a fix for this as well I was planning on adding some integration testing back into the code and managed to get it working with it and your suggested changes.
