### ISSUE TITLE
xFirewall - error 

### ISSUE THREAD

**Issue by cflesher** [PowerShell/xNetworking#48]
Each time I run this

````powershell
Configuration test {

    Import-DSCResource -ModuleName xNetworking

node localhost
{
   xFirewall firsttry {
   Name = "NotepadFirewallRule"
   Program = "c:\windows\system32\notepad.exe"
   Action = "Block"
   Description = "Rule to allow notepad to be accessed remotely"
   Enabled = "True"
   Direction = "Inbound"
   DisplayName = "Windows Team Notepad FW Rule"
   Profile = ("Domain","Private")
   Service = "WinRM"
}
}

start-dscconfiguration -path path
````

I get the following error

````powershell
The PowerShell provider MSFT_xFirewall threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called 
Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
````

It's basically a copy of what is in the example....but it doesn't apply. Is there something I'm missing? I have other settings that work fine on this machine.

**Comment by tysonjhayes** [comment]
Which version of the code are you running?

**Comment by cflesher** [comment]
# Version number of this module.
ModuleVersion = '2.4.0.0'

**Comment by tysonjhayes** [comment]
Sorry are you using the dev fork or are you using the code from the Gallery?  If you are using the gallery could you try the github code?

**Comment by cflesher** [comment]
I downloaded from github about an hour ago...not using the gallery code

**Comment by tysonjhayes** [comment]
I ran your code (it was missing an curly brace } but overall was fine) and wasn't able to reproduce this error on either WMF 4.0 or WMF 5.0 on Server 2012 R2 updated to the latest patches.

What version of WMF are you uisng? What operating system are you running this on?

**Comment by cflesher** [comment]
I'll try updating WMF and let you know if I still get the error

**Comment by cflesher** [comment]
PS C:\Windows\system32> $PSVersionTable

Name                           Value                                                                                                                                                              
----                           -----                                                                                                                                                              
PSVersion                      4.0                                                                                                                                                                
WSManStackVersion              3.0                                                                                                                                                                
SerializationVersion           1.1.0.1                                                                                                                                                            
CLRVersion                     4.0.30319.34014                                                                                                                                                    
BuildVersion                   6.3.9600.17090                                                                                                                                                     
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0}                                                                                                                                               
PSRemotingProtocolVersion      2.2

**Comment by PlagueHO** [comment]
I haven't had any luck replicating it either using WMF5.0 and W2K12 R2.

Are you able to start the DSC config with:
```powershell
Start-DSCConfiguration -path path -Force -Debug -Wait -Verbose
```

And post the log?

Thanks!

**Comment by PlagueHO** [comment]
This is what I get when I do the same thing:
![2015-11-10_11-12-12](https://cloud.githubusercontent.com/assets/7589164/11048299/f65a485c-879b-11e5-92a2-0c91e8dd8111.png)
and:
![2015-11-10_11-14-40](https://cloud.githubusercontent.com/assets/7589164/11048348/45415a00-879c-11e5-8d99-0da6c7c0b3d0.png)

**Comment by cflesher** [comment]
DEBUG: [SCORCHBETA]:                            [[WindowsFeature]Backup::[cfleshertest]localhost::[cfleshertest]localhost] Calling GetEnumerationRequestState provider method...
DEBUG: [SCORCHBETA]:                            [[WindowsFeature]Backup::[cfleshertest]localhost::[cfleshertest]localhost] Progress returned from GetEnumerationRequestState provider method: 47%
DEBUG: [SCORCHBETA]:                            [[WindowsFeature]Backup::[cfleshertest]localhost::[cfleshertest]localhost] Calling GetEnumerationRequestState provider method...
DEBUG: [SCORCHBETA]:                            [[WindowsFeature]Backup::[cfleshertest]localhost::[cfleshertest]localhost] Progress returned from GetEnumerationRequestState provider method: 47%
DEBUG: [SCORCHBETA]:                            [[WindowsFeature]Backup::[cfleshertest]localhost::[cfleshertest]localhost] Calling GetEnumerationRequestState provider method...
DEBUG: [SCORCHBETA]:                            [[WindowsFeature]Backup::[cfleshertest]localhost::[cfleshertest]localhost] Progress returned from GetEnumerationRequestState provider method: 47%
DEBUG: [SCORCHBETA]:                            [[WindowsFeature]Backup::[cfleshertest]localhost::[cfleshertest]localhost] Calling GetEnumerationRequestState provider method...
DEBUG: [SCORCHBETA]:                            [[WindowsFeature]Backup::[cfleshertest]localhost::[cfleshertest]localhost] Progress returned from GetEnumerationRequestState provider method: 90%
DEBUG: [SCORCHBETA]:                            [[WindowsFeature]Backup::[cfleshertest]localhost::[cfleshertest]localhost] Calling GetEnumerationRequestState provider method...
DEBUG: [SCORCHBETA]:                            [[WindowsFeature]Backup::[cfleshertest]localhost::[cfleshertest]localhost] Call to GetEnumerationRequestState provider method succeeded.
VERBOSE: [SCORCHBETA]:                            [[WindowsFeature]Backup::[cfleshertest]localhost::[cfleshertest]localhost] The operation 'Get-WindowsFeature' succeeded: Windows-Server-Backup
DEBUG: [SCORCHBETA]:                            [[WindowsFeature]Backup::[cfleshertest]localhost::[cfleshertest]localhost] End executing Test functionality on the Windows-Server-Backup feature.
VERBOSE: [SCORCHBETA]: LCM:  [ End    Test     ]  [[WindowsFeature]Backup::[cfleshertest]localhost::[cfleshertest]localhost]  in 48.7120 seconds.
VERBOSE: [SCORCHBETA]: LCM:  [ Skip   Set      ]  [[WindowsFeature]Backup::[cfleshertest]localhost::[cfleshertest]localhost]
VERBOSE: [SCORCHBETA]: LCM:  [ End    Resource ]  [[WindowsFeature]Backup::[cfleshertest]localhost::[cfleshertest]localhost]
VERBOSE: [SCORCHBETA]: LCM:  [ Start  Resource ]  [[Service]w32time::[cfleshertest]localhost::[cfleshertest]localhost]
VERBOSE: [SCORCHBETA]: LCM:  [ Start  Test     ]  [[Service]w32time::[cfleshertest]localhost::[cfleshertest]localhost]
VERBOSE: [SCORCHBETA]: LCM:  [ End    Test     ]  [[Service]w32time::[cfleshertest]localhost::[cfleshertest]localhost]  in 0.0370 seconds.
VERBOSE: [SCORCHBETA]: LCM:  [ Skip   Set      ]  [[Service]w32time::[cfleshertest]localhost::[cfleshertest]localhost]
VERBOSE: [SCORCHBETA]: LCM:  [ End    Resource ]  [[Service]w32time::[cfleshertest]localhost::[cfleshertest]localhost]
VERBOSE: [SCORCHBETA]: LCM:  [ Start  Resource ]  [[Service]MpsSvc::[cfleshertest]localhost::[cfleshertest]localhost]
VERBOSE: [SCORCHBETA]: LCM:  [ Start  Test     ]  [[Service]MpsSvc::[cfleshertest]localhost::[cfleshertest]localhost]
VERBOSE: [SCORCHBETA]: LCM:  [ End    Test     ]  [[Service]MpsSvc::[cfleshertest]localhost::[cfleshertest]localhost]  in 0.0610 seconds.
VERBOSE: [SCORCHBETA]: LCM:  [ Skip   Set      ]  [[Service]MpsSvc::[cfleshertest]localhost::[cfleshertest]localhost]
VERBOSE: [SCORCHBETA]: LCM:  [ End    Resource ]  [[Service]MpsSvc::[cfleshertest]localhost::[cfleshertest]localhost]
VERBOSE: [SCORCHBETA]: LCM:  [ Start  Resource ]  [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost]
VERBOSE: [SCORCHBETA]: LCM:  [ Start  Test     ]  [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost]
VERBOSE: [SCORCHBETA]:                            [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost] Test-TargetResource: Checking settings for firewall rule with Name 'Notep
adFirewallRule'.
VERBOSE: [SCORCHBETA]:                            [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost] Test-TargetResource: Find firewall rule with Name 'NotepadFirewallRule'.
VERBOSE: [SCORCHBETA]:                            [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost] Get-FirewallRule: No Firewall Rule found with Name 'NotepadFirewallRule'.
VERBOSE: [SCORCHBETA]:                            [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost] Test-TargetResource: Firewall rule with Name 'NotepadFirewallRule' does n
ot exist.
VERBOSE: [SCORCHBETA]:                            [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost] Test-TargetResource: Check Firewall rule with Name 'NotepadFirewallRule' 
returning False.
VERBOSE: [SCORCHBETA]: LCM:  [ End    Test     ]  [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost]  in 0.3450 seconds.
VERBOSE: [SCORCHBETA]: LCM:  [ Start  Set      ]  [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost]
VERBOSE: [SCORCHBETA]:                            [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost] Set-TargetResource: Applying settings for firewall rule with Name 'Notepa
dFirewallRule'.
VERBOSE: [SCORCHBETA]:                            [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost] Set-TargetResource: Find firewall rule with Name 'NotepadFirewallRule'.
VERBOSE: [SCORCHBETA]:                            [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost] Get-FirewallRule: No Firewall Rule found with Name 'NotepadFirewallRule'.
VERBOSE: [SCORCHBETA]:                            [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost] Set-TargetResource: We want the firewall rule with Name 'NotepadFirewallR
ule' to exist since Ensure is set to Present.
VERBOSE: [SCORCHBETA]:                            [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost] Set-TargetResource: We want the firewall rule with Name 'NotepadFirewallR
ule' to exist, but it does not.
The cmdlet does not fully support the Inquire action for debug messages.  Cmdlet operation will continue during the prompt.  Select a different action preference via -Debug switch or 
$DebugPreference variable, and try again.
    + CategoryInfo          : NotImplemented: (:) [], CimException
    + FullyQualifiedErrorId : ActionPreferenceNotSupportedByCimCmdletAdapter,New-NetFirewallRule
    + PSComputerName        : localhost
 
VERBOSE: [SCORCHBETA]: LCM:  [ End    Set      ]  [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost]  in 0.1500 seconds.
The PowerShell provider MSFT_xFirewall threw one or more non-terminating errors while running the Set-TargetResource functionality. These errors are logged to the ETW channel called 
Microsoft-Windows-DSC/Operational. Refer to this channel for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
 
VERBOSE: [SCORCHBETA]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 49.612 seconds

**Comment by PlagueHO** [comment]
It seems the ```-debug``` parameter on ```Start-DSCConfiguration``` is causing some issues here and obfuscating the actual issue we're trying to investigate (which actually 

Are you able to run this command instead please?
```powershell
Start-DSCConfiguration -path path -Force -Wait -Verbose
```
and post the output?

What is the Windows Server version that this is this DSC config being run on? The BuildVersion in the $PSVersionTable is not necessarily representative of the actual Server Version being used so I can't tell here. The PowerShell Firewall cmdlets have slightly different features and parameters available depending on the OS version rather than the PS version.

Thanks heaps!

**Comment by cflesher** [comment]
This is running on a 2012 R2 virtual machine

PS C:\Windows\system32> Start-DscConfiguration -Path F:\dscscripts\localhost -Wait -Force -Verbose
VERBOSE: Perform operation 'Invoke CimMethod' with following parameters, ''methodName' = SendConfigurationApply,'className'
 = MSFT_DSCLocalConfigurationManager,'namespaceName' = root/Microsoft/Windows/DesiredStateConfiguration'.
VERBOSE: An LCM method call arrived from computer SCORCHBETA with user sid S-1-5-21-3401375572-3424278077-2022591620-2101.
VERBOSE: [SCORCHBETA]: LCM:  [ Start  Set      ]
VERBOSE: [SCORCHBETA]: LCM:  [ Start  Resource ]  [[WindowsFeature]Backup::[cfleshertest]localhost::[cfleshertest]localhost
]
VERBOSE: [SCORCHBETA]: LCM:  [ Start  Test     ]  [[WindowsFeature]Backup::[cfleshertest]localhost::[cfleshertest]localhost
]
VERBOSE: [SCORCHBETA]:                            [[WindowsFeature]Backup::[cfleshertest]localhost::[cfleshertest]localhost
] The operation 'Get-WindowsFeature' started: Windows-Server-Backup
VERBOSE: [SCORCHBETA]:                            [[WindowsFeature]Backup::[cfleshertest]localhost::[cfleshertest]localhost
] The operation 'Get-WindowsFeature' succeeded: Windows-Server-Backup
VERBOSE: [SCORCHBETA]: LCM:  [ End    Test     ]  [[WindowsFeature]Backup::[cfleshertest]localhost::[cfleshertest]localhost
]  in 0.6680 seconds.
VERBOSE: [SCORCHBETA]: LCM:  [ Skip   Set      ]  [[WindowsFeature]Backup::[cfleshertest]localhost::[cfleshertest]localhost
]
VERBOSE: [SCORCHBETA]: LCM:  [ End    Resource ]  [[WindowsFeature]Backup::[cfleshertest]localhost::[cfleshertest]localhost
]
VERBOSE: [SCORCHBETA]: LCM:  [ Start  Resource ]  [[Service]w32time::[cfleshertest]localhost::[cfleshertest]localhost]
VERBOSE: [SCORCHBETA]: LCM:  [ Start  Test     ]  [[Service]w32time::[cfleshertest]localhost::[cfleshertest]localhost]
VERBOSE: [SCORCHBETA]: LCM:  [ End    Test     ]  [[Service]w32time::[cfleshertest]localhost::[cfleshertest]localhost]  in 
0.0160 seconds.
VERBOSE: [SCORCHBETA]: LCM:  [ Skip   Set      ]  [[Service]w32time::[cfleshertest]localhost::[cfleshertest]localhost]
VERBOSE: [SCORCHBETA]: LCM:  [ End    Resource ]  [[Service]w32time::[cfleshertest]localhost::[cfleshertest]localhost]
VERBOSE: [SCORCHBETA]: LCM:  [ Start  Resource ]  [[Service]MpsSvc::[cfleshertest]localhost::[cfleshertest]localhost]
VERBOSE: [SCORCHBETA]: LCM:  [ Start  Test     ]  [[Service]MpsSvc::[cfleshertest]localhost::[cfleshertest]localhost]
VERBOSE: [SCORCHBETA]: LCM:  [ End    Test     ]  [[Service]MpsSvc::[cfleshertest]localhost::[cfleshertest]localhost]  in 0
.0150 seconds.
VERBOSE: [SCORCHBETA]: LCM:  [ Skip   Set      ]  [[Service]MpsSvc::[cfleshertest]localhost::[cfleshertest]localhost]
VERBOSE: [SCORCHBETA]: LCM:  [ End    Resource ]  [[Service]MpsSvc::[cfleshertest]localhost::[cfleshertest]localhost]
VERBOSE: [SCORCHBETA]: LCM:  [ Start  Resource ]  [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost]
VERBOSE: [SCORCHBETA]: LCM:  [ Start  Test     ]  [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost]
VERBOSE: [SCORCHBETA]:                            [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost] T
est-TargetResource: Checking settings for firewall rule with Name 'NotepadFirewallRule'.
VERBOSE: [SCORCHBETA]:                            [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost] T
est-TargetResource: Find firewall rule with Name 'NotepadFirewallRule'.
VERBOSE: [SCORCHBETA]:                            [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost] G
et-FirewallRule: No Firewall Rule found with Name 'NotepadFirewallRule'.
VERBOSE: [SCORCHBETA]:                            [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost] T
est-TargetResource: Firewall rule with Name 'NotepadFirewallRule' does not exist.
VERBOSE: [SCORCHBETA]:                            [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost] T
est-TargetResource: Check Firewall rule with Name 'NotepadFirewallRule' returning False.
VERBOSE: [SCORCHBETA]: LCM:  [ End    Test     ]  [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost]  
in 0.8060 seconds.
VERBOSE: [SCORCHBETA]: LCM:  [ Start  Set      ]  [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost]
VERBOSE: [SCORCHBETA]:                            [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost] S
et-TargetResource: Applying settings for firewall rule with Name 'NotepadFirewallRule'.
VERBOSE: [SCORCHBETA]:                            [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost] S
et-TargetResource: Find firewall rule with Name 'NotepadFirewallRule'.
VERBOSE: [SCORCHBETA]:                            [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost] G
et-FirewallRule: No Firewall Rule found with Name 'NotepadFirewallRule'.
VERBOSE: [SCORCHBETA]:                            [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost] S
et-TargetResource: We want the firewall rule with Name 'NotepadFirewallRule' to exist since Ensure is set to Present.
VERBOSE: [SCORCHBETA]:                            [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost] S
et-TargetResource: We want the firewall rule with Name 'NotepadFirewallRule' to exist, but it does not.
The cmdlet does not fully support the Inquire action for debug messages.  Cmdlet operation will continue during the 
prompt.  Select a different action preference via -Debug switch or $DebugPreference variable, and try again.
    + CategoryInfo          : NotImplemented: (:) [], CimException
    + FullyQualifiedErrorId : ActionPreferenceNotSupportedByCimCmdletAdapter,New-NetFirewallRule
    + PSComputerName        : localhost
 
VERBOSE: [SCORCHBETA]: LCM:  [ End    Set      ]  [[xFirewall]firsttry::[cfleshertest]localhost::[cfleshertest]localhost]  
in 0.2610 seconds.
The PowerShell provider MSFT_xFirewall threw one or more non-terminating errors while running the Set-TargetResource 
functionality. These errors are logged to the ETW channel called Microsoft-Windows-DSC/Operational. Refer to this channel 
for more details.
    + CategoryInfo          : InvalidOperation: (:) [], CimException
    + FullyQualifiedErrorId : NonTerminatingErrorFromProvider
    + PSComputerName        : localhost
 
VERBOSE: [SCORCHBETA]: LCM:  [ End    Set      ]
The SendConfigurationApply function did not succeed.
    + CategoryInfo          : NotSpecified: (root/Microsoft/...gurationManager:String) [], CimException
    + FullyQualifiedErrorId : MI RESULT 1
    + PSComputerName        : localhost
 
VERBOSE: Operation 'Invoke CimMethod' complete.
VERBOSE: Time taken for configuration job to complete is 2.873 seconds

**Comment by cflesher** [comment]
This is working. We only apply security updates and not optional updates. An optional update was related to this and now it's working. Sorry for taking up your time.

**Comment by PlagueHO** [comment]
Oh right! No problem :+1:

Do you possibly know the KBs of the Optional Updates that resolved the issue? Or was it "All of them"? :smile:  I only ask because it is always good to have this stuff documented for any future reference and if it is known we can also add it into the documentation as a gotcha.

Thanks!

**Comment by cflesher** [comment]
KB3000850

It's a big one. Not sure what exactly in that update "fixed" the issue but it did.

**Comment by PlagueHO** [comment]
Awesome! I'll put a mention in the documentation just in case anyone else runs into the problem. Thanks for your help tracking the issue down. :hammer:

**Comment by tysonjhayes** [comment]
We've updated the documentation to note this KB as probably needed. Thanks for letting us know @cflesher

**Comment by jackqq** [comment]
I think I've found where the problem is, but not sure if the solution is correct.

When trying to use this resource to add an open port for MongoDB, I encountered the same error. The configuration is 2012 R2 in a VM, only installed Package Management Preview 10.0.10514.0 and the following updates: KB2883200, KB2884846, and KB2894179. They seem to be necessities to get WMF 4.0 going with the PowerShell Gallery.

The installed modules are:

```
Version    Name
-------    ----
2.0.0.0    xMySql
3.4.0      Pester
2.1.0.0    xDscDiagnostics
1.7.0.0    xDSCResourceDesigner
2.7.0.0    xNetworking
3.7.0.0    xPSDesiredStateConfiguration
```

The DSC configuration is written as (excerpt):

```
    xFirewall MongoPort {
        Name = "MongoDB"
        Protocol = "TCP"
        LocalPort = "27017"
    }
```

The error message,

>    + CategoryInfo          : NotImplemented: (:) [], CimException
>    + FullyQualifiedErrorId : ActionPreferenceNotSupportedByCimCmdletAdapter,New-NetFirewallRule

same as above, doesn't give a clue.

I followed the verbose message
> We want the firewall rule with Name '{0}' to exist, but it does not.

to a part of code of Set-TargetResource in MSFT_xFirewall.psm1, circa **line 366**.

Then I tried to change the line of 
```
New-NetFirewallRule @PSBoundParameters
```
to plainly
```
New-NetFirewallRule -Name MongoDB -DisplayName MongoDB -Protocol TCP -LocalPort 27017
```
and the configuration completed successfully.

Then, I added a few lines of code in front of that line to understand what PSBoundParameters did,
```
$s = ""
foreach ($k in $PSBoundParameters.Keys) {
  $s += " -$k " + $PSBoundParameters[$k]
}
Write-Verbose $s
```
and changed the line creating the rule as:
```
Invoke-Expression "New-NetFirewallRule $s"
```

Then the error message finally made some sense:
> 详细信息: [TEST-SERVER]:                            [[xFirewall]MongoPort]  -Name MongoDB -Action Allow -LocalPort 27017 -Verbose True -Debug True -DisplayName MongoDB
> 找不到接受实际参数“True”的位置形式参数。
>    + CategoryInfo          : InvalidArgument: (:) []，CimException
>    + FullyQualifiedErrorId : PositionalParameterNotFound,New-NetFirewallRule

The above error message translates to: unable to find a positional parameter for the actual argument "True".

So, it's the "True" arguments to the "Verbose" and "Debug" parameters to blame!

Finally, I removed these two parameters from PSBoundParameters with
```
$PSBoundParameters.Remove('Verbose')
$PSBoundParameters.Remove('Debug')
```
and the original code also worked like a charm!

**Comment by PlagueHO** [comment]
Ah I see - so what you're saying is that Set-TargetResource is being called with parameters Verbose and Debug set to true, which then gets splatted to the New-NetFirewallRule cmdlet.

Question: Do you know what causing the Verbose and Debug parameters to be passed? I've never run into this before. How is your LCM configured?

We could of course just add the:
```powershell
$PSBoundParameters.Remove('Verbose')
$PSBoundParameters.Remove('Debug')
```

to the beginning of the Set-TargetResource of course, but I'd like to get a handle on what triggers the LCM to pass them.

**Comment by jackqq** [comment]
I've been using the push model. This is the output of Get-DscLocalConfigurationManager on the target machine:

```
[test-server]: PS C:\Users\Administrator\Documents> Get-DscLocalConfigurationManager

AllowModuleOverwrite           : False
CertificateID                  : 0D3496D5BB2B5795CDD804376CF671EBBBDA4380
ConfigurationID                :
ConfigurationMode              : ApplyAndMonitor
ConfigurationModeFrequencyMins : 30
Credential                     :
DownloadManagerCustomData      :
DownloadManagerName            :
RebootNodeIfNeeded             : False
RefreshFrequencyMins           : 15
RefreshMode                    : PUSH
PSComputerName                 :
```

The configuration script and DSC cmdlets are executed this way:

```
Set-Location F:\

Copy-Item F:\dscmodules\* 'C:\Program Files\WindowsPowerShell\Modules' -Recurse -Force
.\Config-Targets.ps1 developing
Start-DscConfiguration .\output -Verbose -Wait

Invoke-Command -ComputerName $target_server { Stop-Process -Name WmiPrvSE -Force }

.\Config-Product.ps1 developing -Verbose
Set-DscLocalConfigurationManager .\output -Verbose
Start-DscConfiguration .\output -Verbose -Wait
```

where 'developing' is a psd1 filename got passed to the -ConfigurationData parameter in the Config-*.ps1 scripts.

Config-Targets.ps1 copies all the Modules in %ProgramFiles%\WindowsPowerShell from the master machine to the target. Config-Product.ps1 calls other config scripts in this way:

```
. .\configs\MongoDB.ps1

Configuration Product {

    Node $AllNodes.NodeName {
        LocalConfigurationManager {
            CertificateId = $Node.Thumbprint
        }
    }

    Node $AllNodes.Where{ $_.Roles -contains 'MongoDB' }.NodeName {
        Product_MongoDB
    }

}

Product -OutputPath .\output -ConfigurationData ".\configdata\$ConfigName.psd1"
```

I'm using the Composite Resource in an undocumented, workaround way, which is blogged as "Issue 2" at http://dille.name/blog/2015/01/11/reusing-psdsc-node-configuration-with-nested-configurations-the-horror/. The canonical way just adds too much complexity and I just want to make it simple to help my team get the whole picture more easily.
