### ISSUE TITLE
Add Missing Parameters to MSFT_xFirewall Resource

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xNetworking#53]
The following parameters are missing from the MSFT_xFirewall resource and need to be added (after PR #52 has been merged):
DynamicTarget
EdgeTraversalPolicy
IcmpType
LocalOnlyMapping
LooseSourceMapping
OverrideBlockRules
Owner

At this point I don't think they are critical (unless someone needs them right now of course).

**Comment by tysonjhayes** [comment]
you wrote MSFT_xNetworking, did you mean xFirewall?

**Comment by PlagueHO** [comment]
Yes. Yes I did. Corrected now. Sorry about that.

**Comment by PlagueHO** [comment]
Closing. Thanks @tysonjhayes
