### ISSUE TITLE
DNS Servers not set if original settings is empty...

### ISSUE THREAD

**Issue by bk147** [PowerShell/xNetworking#54]
If the DNS on the target computer is empty (not set) the xDNSServerAddress 'Set' states that the configuration is already correct and therefore the DNS does not get set...
Problem seems to be in the check in the "Set-TargetResource" where the Compare-Object returns nothing if $currentAddress is empty - a fix could be to use the same logic as in the "Test-TargetResource"...

**Comment by PlagueHO** [comment]
Hi @bk147 ,

Which version of the xDNSServerAddress resource are you using? Is this in the current Dev branch here or in one of the released versions? There have been some changes to this code over the last few weeks. And from a brief code review of the Master branch vs. the Dev branch it does look like this issue has been fixed.

Are you able to give the code in the Dev branch a try and see if it resolves the issue for you?

Thank you!

**Comment by bk147** [comment]
It's working like a charm in the dev version :-)
[I was using the released 2.4.0.0 version]

Thanks,
-Brian

**Comment by tysonjhayes** [comment]
Thanks for letting us know @bk147 we're hoping to get the new version released soon with these fixes!
