### ISSUE TITLE
Add Ability to Configure Routes

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xNetworking#60]
This would require a change to the xDefaultGatewayAddress resource.

I think it would require two new parameters to be added:
1. Ensure = {Absent | Present} - Default to Present
2. Metric = 0-65536 - Default to 0.

This should enable existing configs to continue to work just fine, but allow multiple Default Gateways to be specified.

**Comment by iainbrighton** [comment]
You can only have one default gateway on an interface (realistically one per machine too)!

It sounds like someone wants/needs a resource for adding and removing routes to the routing table?

We can get into a technical discussion, but we might want to remove any ambiguity around definitions first!

**Comment by PlagueHO** [comment]
When I say Default Gateway I am of course referring to the default route. :smiling_imp: So yes, you're right, you can't practically have two active default gateways - even though you can set them and only one will be active. What I have is two routers connecting to a given network (an edge network) - if the one with the lowest metric fails then the next one becomes the active route.

Example:
![2015-11-25_21-47-07](https://cloud.githubusercontent.com/assets/7589164/11392638/ee186e00-93bf-11e5-8e8c-29095df8cd2b.png)

So, you're right - what I really have a need for is to be able to manually control the default routes. But if we're going that way, we might as well extend it to be able to configure any route - and now that I've said that, it might actually make more sense to have a xRouting resource of some kind where any route can be added/edited/removed.

**Comment by iainbrighton** [comment]
That's where I was going - a more generic "route" resource would also solve specifying multiple gateways. The only real difference will be being able to specify subnet masks (at least for IPv4).

I didn't realise that my Jedi mind-tricks were that good. Might just be great minds, eh?!

**Comment by tysonjhayes** [comment]
Forgive my ignorance here, what other routes are we looking to deal with in this resource?

**Comment by iainbrighton** [comment]
Just static routes in general!

Adding an additional default gateway just adds another route to 0.0.0.0/0. Why just restrict ourselves to ‘default routes’, why not add support for any custom static routes.

For example, the following adds a static route to the 192.168.10/24 network via interface '2' you would use:
```
route add 192.168.10.0 mask 255.255.255.0 10.1.2.254 if 2
```
It's the same thing - I just didn't want someone to create an "AdditionalDefaultGateway" resource, when a more generic "StaticRoute" resource could cater to the wider masses!

**Comment by tysonjhayes** [comment]
So would this be the *-NetRoute commands? If I'm understanding what is being discussed then yes I think it should be its own resource given the constrains that are being discussed.

Though I would say let's use the *-NetRoute commands for a few reasons.

1) It'll make it easier to test as they are actually powershell commands and Pester will have an easier time with it.
2) In general we try to use those over *.exe files. :grin:

**Comment by PlagueHO** [comment]
Some fine Jedi mind tricks - I almost started looking for some other droids. :+1: 

I'd say a generic Route resource for creating/editing/removing any static route using the *-netroute cmdlets is exactly what is needed (solves all problems). Agree with @tysonjhayes, ideally would want to use the *-netroute cmdlets because it does expose some functionality like expiring routes and route protocols that the route command (or NetSh) does not.

Using *-netroute also enables the Dest IP and Subnet to be combined (as that is what *-netroute expects). Giving us a MOF something like this (can't remember MOF syntax off the top of my head):
[key] string $DestinationPrefix
[key,values...] string $AddressFamily
[key] string $InterfaceAlias
[write] string $Ensure
[write] int16 $Metric
[mandatory] string $NextHop
[write] string $Protocol
[write] float $ValidLifetime
[write] float $PreferredLifetime

My 2c :)

**Comment by iainbrighton** [comment]
The ROUTE ADD command was just an example and I've probably just given away I'm an old geezer :). Obviously, the *-NetRoute cmdlets are the best way to go!

**Comment by PlagueHO** [comment]
Haha - you have indeed! At least no one has asked for IPX/SPX support in a resource yet :smiley:

**Comment by PlagueHO** [comment]
Closing because change merged.
