### ISSUE TITLE
MSFT_xNetConnectionProfile fails when DomainAuthenticated

### ISSUE THREAD

**Issue by tysonjhayes** [PowerShell/xNetworking#66]
Running the integration tests while on a domain authenticated machine I get the following error. We'll want to look at modifying the tests to cover this scenario.

``` powershell
Describing MSFT_xNetConnectionProfile_Integration
xNetworking\xNetConnectionProfile : At least one of the values 'DomainAuthenticated' is not supported or valid for property 'NetworkCategory' on class 'xNetConnectionProfile'. Please specify only supported values: Public, Private.
At C:\GitHub\tysonjhayes\xNetworking\Tests\Integration\MSFT_xNetConnectionProfile.config.ps1:6 char:9
+         xNetConnectionProfile Integration_Test {
+         ~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], ParentContainsErrorRecordException
    + FullyQualifiedErrorId : UnsupportedValueForProperty,xNetworking\xNetConnectionProfile

Write-NodeMOFFile : Invalid MOF definition for node 'localhost': Exception calling "ValidateInstanceText" with "1" argument(s): "Syntax error:
 At line:17, char:38
 Buffer:
ry = DomainAuthenticated^;
};
"
At C:\windows\system32\windowspowershell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:1465 char:17
+                 Write-NodeMOFFile $name $mofNode $Script:NodeInstanceAliases[$mo ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [Write-Error], InvalidOperationException
    + FullyQualifiedErrorId : InvalidMOFDefinition,Write-NodeMOFFile
 [-] Should compile without throwing 9.35s
   Expected: the expression not to throw an exception. Message was {Errors occurred while processing configuration 'MSFT_xNetConnectionProfile_Config'.}
       from C:\windows\system32\windowspowershell\v1.0\Modules\PSDesiredStateConfiguration\PSDesiredStateConfiguration.psm1:2223 char:5
       +     throw $errorRecord
       +     ~~~~~~~~~~~~~~~~~~
   at line: 34 in C:\GitHub\tysonjhayes\xNetworking\Tests\Integration\MSFT_xNetConnectionProfile.Integration.Tests.ps1
   34:             } | Should not throw

```

**Comment by PlagueHO** [comment]
Good catch. That's a head scratcher as how to implement integration tests in a domain joined scenario up on AppVeyor. Any thoughts?

**Comment by tysonjhayes** [comment]
Not off the top of my head, my first thought might just be it's not a supported scenario as  AppVeyor obviously can't support it. Unless we get super crazy on some configuration stuff.  I'll have to think on it a bit.

**Comment by PlagueHO** [comment]
I'm thinking Domain Joining an AppVeyor machine to an Azure AD domain is probably not going to work? I can see other DSC Resources requiring Domain Joined machines for integration tests as well - I don't think this problem will be isolated to just this resource.

**Comment by PlagueHO** [comment]
One possible way of doing this would be to execute an offline domain join on the AppVeyor machine using a predefined blob (that could be stored in the repo). In this situation you wouldn't actually need a read DC to be available. The ODJ blob would need to match the name of the AppVeyor machine though and would therefore not work for local tests. But you probably don't want local tests to force a domain join anyway.

The problem with doing this though is that after the ODJ blob is applied to the AppVeyor machine it would want to force a reboot before the machine would be considered part of a domain. I can't think of a way around this part.

I wonder if it might be possible to ask the AppVeyor guys if they could provide a build environment image that was domain joined? I doubt the DC would need to be accessible for these tests to work.

**Comment by PlagueHO** [comment]
@tysonjhayes - It is now possible to have an AppVeyor machine reboot in the init phase, so it might be possible to have it perform an ODJ. However, this really does open up a whole set of other problems (like whose Azure AD account would be used - how can we guarantee this Azure AD is available).

IMHO we should close this and reopen it if/when some solutions to these problems present.

**Comment by PlagueHO** [comment]
@tysonjhayes - I'm going to close this one, because I don't really see a way to add tests for this. We can reopen this if we figure out some way to execute tests on a domain joined machine in AppVeyor.

**Comment by tysonjhayes** [comment]
We should add it to the known issues

list.

**Comment by PlagueHO** [comment]
Great suggestion. I've reopend this to ensure it happens!

**Comment by tysonjhayes** [comment]
Actually this really isn't a known issue per se basically we grab the current settings and put them into DSC. Means we're kind of blocked on actually modifying stuff but as we noted that's kind of hard in this scenario. I'm going to close this.
