### ISSUE TITLE
Add Integration Tests for Resources

### ISSUE THREAD

**Issue by tysonjhayes** [PowerShell/xNetworking#72]
The following resources are missing integration tests. This leads to PRs like #71. We should add integration tests for these resources.

* MSFT_xDNSServerAddress
* MSFT_xDefaultGatewayAddress
* MSFT_xDnsConnectionSuffix
* MSFT_xIPAddress

**Comment by PlagueHO** [comment]
Thinking out loud here:

I've been thinking about this one for a while now. The problem I keep running into with this is figuring out a "non-destructive" method of implementing these. E.g. we'd want to avoid stopping network connectivity when these tests execute.

What would happen if network connectivity stopped while AppVeyor tests run - I guess we could find out? Assuming AppVeyor was OK with a disruption of network connectivity, we could allow the integration tests to modify the network settings and then restore them afterwards - this might work, but it feels a bit risky to me.

I thought about trying to add a loopback adapter we can use to run integration tests on, but this will require quite a bit of code and I couldn't get it working (didn't try for that long though). We just need some form of adapter we can add that we can mess with the IP config on.

But I'm with you 100% - we need these!

**Comment by tysonjhayes** [comment]
Oh for sure, I'm not sure how to "fix" it either without accidently doing some terrible things to an operators machine that may knock it off the network etc.  Just putting it out there that we need to test these resources.

**Comment by PlagueHO** [comment]
Adding a loopback adapter seems the most promising approach. Is it worth me spending a bit more time trying to get a loopback adapter added via powershell?

I've seen some code floating around to do this, but it is quite "nasty" (downloads scripts/apps off the internet etc). So, I'd rather not use that code if I can avoid it - too many dependencies that we couldn't ensure will always be there. Pity there isn't a single cmdlet to add a loopback adapter device.

**Comment by tysonjhayes** [comment]
Mulling it over with some of my coworkers we think it makes the most amount of sense to add a loopback device to try to work over. If you wanted to work on it let's try solving just that for now, and then move on to the rest. This is a pretty tough problem that I want to make sure we handle well.

**Comment by PlagueHO** [comment]
Ok, will do.
