### ISSUE TITLE
HostsFile management

### ISSUE THREAD

**Issue by leshkinski** [PowerShell/xNetworking#8]
Hi! I'm dealing with a requirement to manage hostsfile and found an existing [community effort](https://github.com/rchaganti/DSCResources/tree/master/cWindowsOS/DSCResources/cHostsFile) to address this, but thought that it would logical to add this functionality to the Networking resource module going forward. Are there any objections if I add a HostsFile resource to this module?

**Comment by tysonjhayes** [comment]
I'm not aware of anything besides the community effort. I think it makes more sense in the Networking module then its own. So please feel free to add it!

**Comment by rchaganti** [comment]
I am submitting a pull request for adding HostsFile DSC resource from my repo. I have included only DSC resource and schema tests for now. I will eventually add more tests related to functionality of the HostsFile resource.

**Comment by rchaganti** [comment]
https://github.com/PowerShell/xNetworking/pull/93 closes this.

**Comment by rchaganti** [comment]
This can be closed. HostsFile resource is now a part of xNetwork dev branch. https://github.com/PowerShell/xNetworking/commit/83a60f2ef467ca607295e05c146460be14960114

**Comment by tysonjhayes** [comment]
Closing issue per @rchaganti 's notes.
