### ISSUE TITLE
Bug - MSFT_xDNSConnectionSuffix format return error

### ISSUE THREAD

**Issue by Zuldan** [PowerShell/xNetworking#81]
If I run Get-DscConfiguration I receive the following error...

Get-DscConfiguration : The PowerShell DSC resource  returned results that are not valid from Get-TargetResource. The DnsSuffix key is not a valid property in the corresponding
DSC resource schema file. The results from Get-TargetResource must be in a Hashtable format. The keys in the Hashtable must be the same as the properties in the corresponding DSC
resource schema file.
At line:1 char:1
+ Get-DscConfiguration
+ ~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidResult: (MSFT_DSCLocalConfigurationManager:root/Microsoft/...gurationManager) [Get-DscConfiguration], CimException
    + FullyQualifiedErrorId : GetOperationResultInvalidResultFormat,Get-DscConfiguration

**Comment by PlagueHO** [comment]
Hi @Zuldan,

It looks like this issue has been resolved in the Dev branch of this repo in (this commit)[https://github.com/PowerShell/xNetworking/commit/49d82396c2c685204eaba02c13c93d2fb6c4d77e].

This version hasn't yet been released officially, but you could still use a copy of the Dev resource. Are you able to give the Dev version a try and let us know if your problem still occurs?

Thanks :+1:

**Comment by Zuldan** [comment]
PlagueHO , thank you for pointing this out to me. I tried the Dev version and I have no more errors! Looking forward to it being pushed to master.

**Comment by PlagueHO** [comment]
No worries! Thankyou :+1:
