### ISSUE TITLE
Remove Templates from templates folder

### ISSUE THREAD

**Issue by PlagueHO** [PowerShell/xNetworking#84]
The templates are now available in the (DSCResources repo)[https://github.com/PowerShell/DscResources/tree/master/Tests.Template] along with usage documentation etc.

I think the templates should be removed from this folder and replaced with a readme.md  that directs a user to the templates in the DSCResources repo.

Any thoughts?

**Comment by PlagueHO** [comment]
@tysonjhayes - Any thoughts on whether we can remove the templates from this repo now? At the moment they're out of sync with the master templates and I'm wondering if I should apply the latest changes I made to the master templates to these ones.

**Comment by tysonjhayes** [comment]
Yeah I think it makes sense to remove them, in an ideal world we'd link to them so when someone clones the repro they get the templates, but that's never worked exceptionally well. Let's just delete them.

**Comment by PlagueHO** [comment]
Cool. Thanks @tysonjhayes. Ill get this done.
