### ISSUE TITLE
Small typo in ModuleVersion = '2.6.0.0'

### ISSUE THREAD

**Issue by juriskrumins** [PowerShell/xNetworking#92]
We have tag 2.7.0.0, but when you download code with this tag, you end up with record in xNetworking.psd1 : ModuleVersion = '2.6.0.0'. As a result, when you put code to the directory XNetworkking\2.7.0.0\... you can't load it.

**Comment by PlagueHO** [comment]
Are you downloading the code directly from the master branch or the dev branch? Or are you using Install-Module to get this from the PowerShell Gallery?

I've tried using:
```powershell
Install-module xnetworking
```

and it seems to install the xNetworking module to the correct 2.7.0.0 folder as expected.

Or am I misunderstanding the issue?

**Comment by juriskrumins** [comment]
I've used tag.
Tag -> 2.7.0.0 and then Download zip.

**Comment by PlagueHO** [comment]
Oh, I see. The issue here is that the Tag 2.7.0.0 is linked to the wrong commit/branch (the 2.6.0.0 release commit). @tysonjhayes - are you able to resolve this?

In the mean time, can you download the Master branch instead? The master branch is currently at 2.7.0.0.

**Comment by juriskrumins** [comment]
Excellent. Thanks.

**Comment by tysonjhayes** [comment]
Not something I can fix - @KarolKaczmarek could you lend a hand?

**Comment by KarolKaczmarek** [comment]
Should be fixed now
