### ISSUE TITLE
xDNSServerAddress does not always set the DNS address when its empty

### ISSUE THREAD

**Issue by DdenBraver** [PowerShell/xNetworking#97]
When using the xDNSServerAddress resource on a computer that has no DNS addresses filled in, it does not always set them properly.

Test-Target resource shows it is in an incorrect state, however Set-Target resource thinks it is correct.
This is due to line 96 of MSFT_xDNSServerAddress.psm1:

```
#Check if the Server addresses are the same as the desired addresses.
    [Boolean] $addressDifferent = (@(Compare-Object `
            -ReferenceObject $currentAddress `
            -DifferenceObject $Address `
            -SyncWindow 0).Length -gt 0)
```

Tested on Server 2016 TP4 (RTM) and Server 2012R2 with WMF5 Production Preview.

**Comment by PlagueHO** [comment]
So, in your config you're setting the DNS Servers to a value (which values), but currently the DNS entries on the node are empty?
e.g.
```powershell
(Get-DnsClientServerAddress `
        -InterfaceAlias $InterfaceAlias `
        -AddressFamily $AddressFamily `
        -ErrorAction Stop)
```

returns nothing currently, and your config is trying to set the values?

Just wanting to get my facts straight before I investigate too much :smile:

The odd thing is the test for state difference in Test-TargetResource and Set-TargetResource are identical (or at least appear to be - side by side).

**Comment by DdenBraver** [comment]
@PlagueHO, that is correct.

I did just notice I was using an older version of the resource.
I will get the latest available and will re-run my tests, as there is a minor difference in the Set-TargetResource.

**Comment by DdenBraver** [comment]
I will close this issue, since it works fine with the latest version. 
I thought i was using the latest one however it seems I copied an older from my own file-share. (v 2.4.0.0)

**Comment by PlagueHO** [comment]
Oh right! No worries - I do recall we fixed something like this a few versions back - so that would explain it. Thanks!
